### ISSUE TITLE
Visual Studio code Dev Containers Using deprecated property to check version

### ISSUE THREAD

**Issue by muziekklas** [containerd/nerdctl#1027]
### What is the problem you're trying to solve

I am attempting to use Nerdctl for VSC Dev Containers, to completely replace Docker Desktop.
I was able to change the executable in VSC to nerdctl but I hit the following issue:

`level=fatal msg="template: :1:9: executing "" at <.Server.APIVersion>: can't evaluate field APIVersion in type *dockercompat.ServerVersion"`

If you take a look at the dockercli implementation of the API, they expose the APIVersion property without digging through the Components array, but marked them as deprecated:
https://github.com/moby/moby/blob/v20.10.8/api/types/types.go#L128

### Describe the solution you'd like

I wonder, whether you guys could add these obsolete properties to the ServerVersion type https://github.com/containerd/nerdctl/blob/2b4e3bde28d67d08c85bcf15fef23d973bae590f/pkg/inspecttypes/dockercompat/info.go#L95 and populate them (I think here: 
https://github.com/containerd/nerdctl/blob/2b4e3bde28d67d08c85bcf15fef23d973bae590f/pkg/infoutil/infoutil.go#L122-L139
)
?

**Comment by AkihiroSuda** [comment]
containerd doesn't implement Docker REST API, so it doesn't make sense to fulfill `.Server.APIVersion`.

**Comment by AkihiroSuda** [comment]
Could you ask the VSCode developers to ignore that field for nerdctl?

**Comment by muziekklas** [comment]
> containerd doesn't implement Docker REST API, so it doesn't make sense to fulfill `.Server.APIVersion`.

Understandable... I was thinking more in line just to expose the version to 'please' the devcontainer extension in VSC. But I understand your point of view.



> Could you ask the VSCode developers to ignore that field for nerdctl?

I have contacted them too, hoping that they might be able to do something to support nerctl. Though, their work arround is to switch away from containerd to dockerd. Maybe they can do anything in their extension

**Comment by AkihiroSuda** [comment]
Maybe we can fulfill an obviously fake value such as "v9999.0.0" if it is enough to let VScode interact with nerdctl.
If this is not enough I'd still suggest to change the VSCode side.

**Comment by muziekklas** [comment]
Indeed, that was my initial thought process, But I lack the know-how of Go to do this.
