### ISSUE TITLE
nerdctl run -p,portmap isn't running

### ISSUE THREAD

**Issue by mayday0208** [containerd/nerdctl#1030]
### Description

ubuntu 18.04 ,nerdctl version:0.19
when i start a container,i can't find the portmap .

### Steps to reproduce the issue

1.sudo nerdctl run -it --rm --gpus '"capabilities=compute,utility,video"' -v /home/:/host -p 9526:8080 --name rtsp_test 8eba317006a6 /bin/bash
2. nerdctl container ls
![image](https://user-images.githubusercontent.com/53076890/166854345-94a9f171-2e33-4fce-97c6-9dac7ffebb0b.png)
3.sudo iptables -vnL -t nat
![image](https://user-images.githubusercontent.com/53076890/166854408-f70a4275-f873-4b7b-87ae-41f277e2bf40.png)
i can't find the port 9526:8080
4.in container:ifconfig
![image](https://user-images.githubusercontent.com/53076890/166854567-08267bd2-d6f0-40e0-945e-f491c9c5b96d.png)

### Describe the results you received and expected

portmap doesn't run

### What version of nerdctl are you using?

0.19,release

**Comment by AkihiroSuda** [comment]
What’s your CNI portmap plugin version and where is the installation path of the plugin binary?

**Comment by AkihiroSuda** [comment]
Please try installing plugins v1.1.1 to /opt/cni/bin
https://github.com/containernetworking/plugins/releases

**Comment by mayday0208** [comment]
> 




> What’s your CNI portmap plugin version and where is the installation path of the plugin binary?

I download nerdctl-full-0.19.0-linux-amd64.tar.gz(include cni?),and install it with the following commands:
tar Cxzvvf /usr/local nerdctl-full-0.19.0-linux-amd64.tar.gz.
the cni version is 1.1.1
![image](https://user-images.githubusercontent.com/53076890/166867932-be7b68e3-6ba8-43a4-8f8a-3949bd21bab5.png)

**Comment by fahedouch** [comment]
@mayday0208  are you setting `CNI_PATH` to cni old plugins ?

**Comment by mayday0208** [comment]
> @mayday0208 are you setting `CNI_PATH` env var? this may pointing to cni old plugins ?

yes，env is setting cni_path,and i  didn't download the old version

**Comment by mayday0208** [comment]
I reboot my pc，and discover the port with " 'iptables -vnL -t nat'"
but i can't receive anything from port 9521.
![image](https://user-images.githubusercontent.com/53076890/167051120-564e53f4-6943-4639-9744-6f149bea9475.png)

**Comment by mayday0208** [comment]
Portmap：Data can be received on the same computer and can't on the diff

**Comment by AkihiroSuda** [comment]
Is https://github.com/containerd/nerdctl/issues/1048 same as this?

**Comment by mayday0208** [comment]
> 

yes,it's the same issue
