### ISSUE TITLE
Move from github.com/AkihiroSuda to github.com/containerd

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#105]
Proposed in https://github.com/containerd/project/issues/69

**Comment by fahedouch** [comment]
Hi @AkihiroSuda ,

happy to hear this. And request to be a maintainer of nerdctl.

Have a nice day

**Comment by AkihiroSuda** [comment]
Moved the repo to https://github.com/containerd/nerdctl/ .

@fahedouch Thanks, I'd like to see more contributions toward that.
