### ISSUE TITLE
cp should also work on created containers

### ISSUE THREAD

**Issue by ondrej-smola** [containerd/nerdctl#1058]
### What is the problem you're trying to solve

Improve feature compatibility with podman and docker

### Describe the solution you'd like

Allow cp command to work with created containers, not just running.

### Additional context

We are using containers that cannot be easily run to just copy data from inside.

**Comment by zgfh** [comment]
same problem.
Allow cp command to work with exited containers, not just running.

find this may help:  https://github.com/containerd/containerd/issues/2044#issuecomment-359893164

**Comment by vsiravar** [comment]
Hit this problem today, [aws-cdk ](https://github.com/aws/aws-cdk/tree/main) copies files to and from stopped containers for asset bundling.

**Comment by vsiravar** [comment]
As [suggested](https://github.com/containerd/containerd/issues/2044#issuecomment-359893164) by @zgfh , if it's acceptable, I can make a PR to fix this using [containerd snapshot service](https://github.com/containerd/containerd/blob/main/api/services/snapshots/v1/snapshots.proto#L29) to copy files to and from created containers in addition to  running containers. I tried this locally on a stopped container to copy files out of it to the host filesystem. 

```
conn, err := grpc.Dial("unix:///run/containerd/containerd.sock", grpc.WithInsecure())
...
// Error handling code clipped 

	// Create a new Snapshots client
	client := snapshotsapi.NewSnapshotsClient(conn)

	// Call the Mounts method
	req := &snapshotsapi.MountsRequest{
		Snapshotter: <snapshotter>, // or whatever snapshotter you're using
		Key:         <containeid>,
	}
	resp, err := client.Mounts(ctx, req)
	// More error handling

	mounts := make([]mount.Mount, len(resp.Mounts))
	for i, m := range resp.Mounts {
		mounts[i] = mount.Mount{
			Type:    m.Type,
			Source:  m.Source,
			Options: m.Options,
		}
	}

	// Mount the snapshot
	tempDir := "/tmp/mount-snapshot"
	if err := mount.All(mounts, tempDir); err != nil {
		panic(err)
	}
	defer mount.Unmount(tempDir, 0)
	// Now the snapshot is mounted and its files are accessible locally
```
@AkihiroSuda lmk what you think?

**Comment by AkihiroSuda** [comment]
Looks good, but tempDir has to be randomized
