### ISSUE TITLE
Proposition: Support a more open Containerfile in addition to Dockerfile

### ISSUE THREAD

**Issue by Kitanotori** [containerd/nerdctl#1084]
### What is the problem you're trying to solve

`nerdctl build` expects **Dockerfile** by default and ignores **Containerfile**.

### Describe the solution you'd like

As Dockerfile has evolved from a Docker-specific technology to a general purpose container image build format, it would be appropriate to also support more general naming, like e.g. [buildah](https://github.com/containers/buildah/issues/1853) has already done.

Also, while at it, it might also be good to drop _docker_ from code base naming unless particular logic is actually docker-specific.

### Additional context

Ref: https://github.com/containerd/nerdctl/blob/master/pkg/buildkitutil/buildkitutil.go#L43

**Comment by fahedouch** [comment]
We are using buildkitd under the hood to build docker image so this should be addressed to buildkit before https://github.com/moby/buildkit

**Comment by Kitanotori** [comment]
> We are using buildkitd under the hood to build docker image so this should be addressed to buildkit before https://github.com/moby/buildkit. I will close this issue for the moment feel free to add comments later :)

I don't think buildkit makes assumptions regarding name of the file, so the necessary change is only at nerdctl side.

**Comment by manugupt1** [comment]
Can I work on this?
Thanks

**Comment by manugupt1** [comment]
Hi @Kitanotori 

Why wont simplify providing `-f Containerfile` work?

When a user does not specify a file, should the behavior be to:
1. use Dockerfile only
2.use Containerfile Only?
3. look for Dockerfile first (if it is present use it); then  use Containerfile later?
4. look for Containerfile first(if it is present use); then use Dockerfile?
5. What should we do when both are present (in the weird edge case); should we prefer Dockerfile / Containerfile

**Comment by Kitanotori** [comment]
@manugupt1 I'm not proposing removing Dockerfile; I'm proposing to support also Containerfile. Ideally first check Containerfile and if not found then Dockerfile. But the order doesn't really matter, as it is unlikely both exist at the same time.

**Comment by manugupt1** [comment]
Thanks!
I think we should keep Dockerfile as default and if it does not exist Containerfile should be checked for. THis is because moving from Dockerfile to Containerfile is a breaking change.

 @AkihiroSuda @fahedouch @junnplus can you tell me which approach would you prefer? thanks!

**Comment by junnplus** [comment]
> should keep Dockerfile as default and if it does not exist Containerfile should be checked for

SGTM

**Comment by fahedouch** [comment]
fixed by https://github.com/containerd/nerdctl/pull/1219
