### ISSUE TITLE
Can't push an encrypted image to docker hub private repository

### ISSUE THREAD

**Issue by joaopfg** [containerd/nerdctl#1094]
### Description

I can push a non-encrypted image without problems to my private repository on docker hub. However, when trying to push an encrypted image (encrypted using nerdctl's encrypt command), it does not work. 

### Steps to reproduce the issue

For example, consider an image generated by the following very simple Dockerfile:

`FROM python:3.9`

```
1. sudo nerdctl login
2. sudo nerdctl build -t test .
3. openssl genrsa -out mykey.pem
4. openssl rsa -in mykey.pem -pubout -out mypubkey.pem
5. sudo nerdctl image encrypt --recipient=jwe:mypubkey.pem --platform=linux/amd64,linux/arm64 test <my-dockerhub-username>/<my-dockerhub-repository-name>:encrypted
6. sudo nerdctl push <my-dockerhub-username>/<my-dockerhub-repository-name>:encrypted
```

### Describe the results you received and expected

I am receiving the following error:

`FATA[0001] failed commit on ref "manifest-sha256:a10dfff1ee02b2b644b4382bd210c5cf4e4fca5ca8e983014a53619cd5bdaa22": unexpected status from PUT request to https://registry-1.docker.io/v2/<my-dockerhub-username>/<my-dockerhub-repository-name>/manifests/encrypted: 403 Forbidden`.

### What version of nerdctl are you using?

0.20.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

No

### Host information

```
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v1.6.4
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: json-file
  Storage: aufs native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-44-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.576GiB
 Name: <my-computer-name>
 ID: db2396ff-441a-4445-8ddd-e70805ba1bf6
```

**Comment by AkihiroSuda** [comment]
This might be an issue of Docker Hub?
Can you push the encrypted image to other registries such as GHCR?

**Comment by joaopfg** [comment]
It works with GHCR, thanks for answer.

About the non-support for docker hub, I'm a bit confused. Shouldn't be up to nerdctl to adapt to docker hub's API instead of docker hub's API to adapt to nerdctl ? Do you have an idea about where the problem appears in the source code ? I can try to give a look.

**Comment by AkihiroSuda** [comment]
> Shouldn't be up to nerdctl to adapt to docker hub's API instead of docker hub's API to adapt to nerdctl ? 

s/nerdctl/ocicrypt/, and Docker Hub should support OCIcrypt media types

> Do you have an idea about where the problem appears in the source code ?

It is likely that Docker Hub does not support non-Docker media types, but their source code is not open AFAICS
