### ISSUE TITLE
The argument --memory-swap not supported in nerdctl run

### ISSUE THREAD

**Issue by reich80** [containerd/nerdctl#1105]
### What is the problem you're trying to solve

The --memory-swap is useful in practice but not supported by nerdctl run.

[root@Cc6Apc ~]# 
[root@Cc6Apc ~]# nerdctl run -it --privileged --memory-swap=4096000 registry.servicemgr.apc:5000/gatk3 ls /
FATA[0000] unknown flag: --memory-swap                  
[root@Cc6Apc ~]# 
[root@Cc6Apc ~]# 

### Describe the solution you'd like

support it and be compatible with docker

**Comment by ningmingxiao** [comment]
will fix in https://github.com/containerd/nerdctl/issues/1105
