### ISSUE TITLE
[Rancher Desktop for Windows] nerdctl cp does not work

### ISSUE THREAD

**Issue by alfclement** [containerd/nerdctl#1143]
### Description

unable to copy file in or out of running container

### Steps to reproduce the issue

A running container:

$ nerdctl ps
CONTAINER ID    IMAGE                                 COMMAND      CREATED
  STATUS    PORTS    NAMES
f7b464d19902    docker.io/library/vlang_web:latest    "/bin/sh"    4 hours ago
  Up                 vlang_web-f7b46

Ls into the container:
$ nerdctl exec f7b464d19902 ls -l /opt/vlang/v
-rwxr-xr-x    1 root     root       4107040 Jun 19 09:19 /opt/vlang/v

But copy fails:
$ nerdctl cp f7b464d19902:/opt/vlang/v v
WARN[0000] failed to inspect NetNS                       error="failed to Statfs
 \"/proc/12486/ns/net\": no such file or directory" id=f7b464d1990283fc1437f95db
7e80e9e607a3103d5d5716225fa1cbb0bced098
WARN[0000] "/bin/tar" does not seem GNU tar
FATA[0000] stat /proc/12486/root/opt/vlang/v: no such file or directory

### Describe the results you received and expected

File should be copied.

### What version of nerdctl are you using?

Rancher Desktop 1.4.1
nerdctl version 0.20.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Rancher Desktop for Windows

### Host information

$ nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.4
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: json-file
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Rancher Desktop WSL Distribution
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 12.36GiB
 Name: DESKTOP-S0QGM9H
 ID: d422bf5e-7fe9-4fda-8582-0765c474a1eb

**Comment by fahedouch** [comment]
We are not supporting windows for cp command, how rancher can invoke this on windows platform :/ !?

**Comment by alfclement** [comment]
With cygwin or in a cmd prompt?!
I am using all nerdctl via cygwin under Windows. cp command should work to copy files in and out.

**Comment by fahedouch** [comment]
@alfclement are you using rootfull or rooltless mode ?
Does this path exist on the host /proc/12486/root/opt/vlang/v ?

Looks like ir related to permission regarding virtual fs /proc

**Comment by alfclement** [comment]
It seems nerdctl looks on it's own host in /proc ... but maybe it needs to look in WSL2 in /proc for the PID , right?

**Comment by AkihiroSuda** [comment]
Could you report to https://github.com/rancher-sandbox/rancher-desktop/issues

**Comment by apostasie** [comment]
@alfclement this is fixed by the PR on rancher, right?

**Comment by apostasie** [comment]
@AkihiroSuda suggesting we close as Rancher fixed it.
