### ISSUE TITLE
container create failed and error message is "FATA[0000] open /run/systemd/resolve/resolv.conf: no such file or directory"

### ISSUE THREAD

**Issue by Bevisy** [containerd/nerdctl#1145]
### Description

The container creation failed, reporting the following error:
```sh
❯ sudo nerdctl run --rm --name test --namespace k8s.io --runtime io.containerd.runc.v2 --privileged docker.io/library/busybox:1.31.1 test sh
FATA[0000] open /run/systemd/resolve/resolv.conf: no such file or directory
```

### Steps to reproduce the issue

1. The host close systemd-resolved service, so file /run/systemd/resolve/resolv.conf doesn't exist.
```sh
❯ sudo systemctl status systemd-resolved
● systemd-resolved.service - Network Name Resolution
     Loaded: loaded (/lib/systemd/system/systemd-resolved.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
❯ ls -lsh /run/systemd/resolve/resolv.conf
ls: cannot access '/run/systemd/resolve/resolv.conf': No such file or directory
```
2. use nerdctl to create container
```sh
❯ sudo nerdctl run --rm --name test --namespace k8s.io --runtime io.containerd.runc.v2 --privileged docker.io/library/busybox:1.31.1 test sh
FATA[0000] open /run/systemd/resolve/resolv.conf: no such file or directory
```

### Describe the results you received and expected

The host has file /etc/resolv.conf, so I Think creating shouldn't be failed.
```sh
❯ cat /etc/resolv.conf
nameserver 127.0.0.53
```

### What version of nerdctl are you using?

❯ sudo nerdctl version
Client:
 Version:	v0.21.0
 OS/Arch:	linux/amd64
 Git commit:	9ddf5226eabcbb7b4b43987f3b0f8d53d86d3bca

Server:
 containerd:
  Version:	1.6.6
  GitCommit:	10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1

### Host information

❯ sudo nerdctl info
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: 1.6.6
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file
  Storage: aufs native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-48-generic
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.45GiB
 Name: zbb-pc
 ID: 7b822ed6-3964-4d28-ac96-75434c455458

**Comment by AkihiroSuda** [comment]
What daemon is serving 127.0.0.53 ?

**Comment by Bevisy** [comment]
> What daemon is serving 127.0.0.53 ?

I use coredns to listen 0.0.0.0:53.

**Comment by junnplus** [comment]
> The host has file /etc/resolv.conf, so I Think creating shouldn't be failed.

If `/etc/resolv.conf` contains `127.0.0.53` as the only nameserver, will use `/run/systemd/resolve/resolv.conf`, see https://github.com/containerd/nerdctl/blob/master/pkg/resolvconf/resolvconf.go#L60-L70

**Comment by Bevisy** [comment]
> > The host has file /etc/resolv.conf, so I Think creating shouldn't be failed.
> 
> If `/etc/resolv.conf` contains `127.0.0.53` as the only nameserver, will use `/run/systemd/resolve/resolv.conf`, see https://github.com/containerd/nerdctl/blob/master/pkg/resolvconf/resolvconf.go#L60-L70
> 
> So you should guarantee the systemd-resolved service works or add an extra nameserver to `/etc/resolv.conf`.

Got it. But it seems like a sloppy solution, at least to determine if systemd-resolved exists, for example, if I use coredns instead of systemd-resolved, I can't get nerdctl to be used here.

**Comment by junnplus** [comment]
Looks like we should have a DNS as default if resovconf is not found.
