### ISSUE TITLE
nerdctl ps lacks "-s" / "--size" option

### ISSUE THREAD

**Issue by ensonic** [containerd/nerdctl#1176]
### Description

```
> docker ps --help | grep size
  -s, --size            Display total file sizes
```
This in particular shows containers that write to their ephemeral layer. This option is missing in nerdctl (0.21.0).

### Steps to reproduce the issue

1. nerdctl ps --help | grep size

### Describe the results you received and expected

Support for the flag, but is is missing.

### What version of nerdctl are you using?

0.21.0

**Comment by liubin** [comment]
@AkihiroSuda @junnplus I'd like to add this feature, can you assign this to me?
