### ISSUE TITLE
TestRunWithJsonFileLogDriver is flaky

### ISSUE THREAD

**Issue by manugupt1** [containerd/nerdctl#1222]
### Description

=== PAUSE TestRunStdin
=== RUN   TestRunWithJsonFileLogDriver
    run_test.go:237: the maximum number of old log files to retain exceeded 2 files
--- FAIL: TestRunWithJsonFileLogDriver (3.42s)

https://github.com/containerd/nerdctl/runs/7312918520?check_suite_focus=true

### Steps to reproduce the issue

N/A

### Describe the results you received and expected

Test should pass.

### What version of nerdctl are you using?

built on master

### Host information

Fedora 36

**Comment by AkihiroSuda** [comment]
=== RUN   TestRunWithJsonFileLogDriver
    run_test.go:237: the maximum number of old log files to retain exceeded 2 files, got: [/var/lib/nerdctl/1935db59/containers/nerdctl-test/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4-json.log /var/lib/nerdctl/1935db59/containers/nerdctl-test/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4-json.log.1 /var/lib/nerdctl/1935db59/containers/nerdctl-test/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4-json.log.2 /var/lib/nerdctl/1935db59/containers/nerdctl-test/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4-json.log.22 /var/lib/nerdctl/1935db59/containers/nerdctl-test/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4-json.log.3 /var/lib/nerdctl/1935db59/containers/nerdctl-test/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4-json.log.4 /var/lib/nerdctl/1935db59/containers/nerdctl-test/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4-json.log.5 /var/lib/nerdctl/1935db59/containers/nerdctl-test/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4/76fbdf10f050749b2d84e4bb136cc4c8f02dddeb302b30244e33cc2c61fe01f4-json.log.6]
--- FAIL: TestRunWithJsonFileLogDriver (3.35s)


https://github.com/containerd/nerdctl/runs/7314776208?check_suite_focus=true

**Comment by fahedouch** [comment]
Looks like an issue with `go-logrotate` , I will take a look

**Comment by manugupt1** [comment]
In this case.
```
=== RUN   TestRunWithJsonFileLogDriver
    run_test.go:237: the maximum number of old log files to retain exceeded 2 files, got: []
--- FAIL: TestRunWithJsonFileLogDriver (3.44s)
```
https://github.com/containerd/nerdctl/runs/7319449412?check_suite_focus=true

**Comment by manugupt1** [comment]
I got another failure:
https://github.com/manugupt1/nerdctl/runs/7366257926?check_suite_focus=true#step:5:695

Test summary: https://github.com/manugupt1/nerdctl/actions/runs/2679791706

**Comment by junnplus** [comment]
Doesn't seem to be fully fixed.
```
=== RUN   TestRunWithJsonFileLogDriver
    run_test.go:237: the maximum number of old log files to retain exceeded 2 files, got: []
--- FAIL: TestRunWithJsonFileLogDriver (3.36s)
```

**Comment by fahedouch** [comment]
OK I am investigating

**Comment by fahedouch** [comment]
making log message more specific  https://github.com/containerd/nerdctl/pull/1241/files

**Comment by djdongjin** [comment]
This one seems frequent recently:

https://github.com/containerd/nerdctl/actions/runs/3343599257/jobs/5536985776

https://github.com/containerd/nerdctl/actions/runs/3438150819/jobs/5733839743

https://github.com/containerd/nerdctl/actions/runs/3019700424/jobs/4855888202

**Comment by AkihiroSuda** [comment]
- https://github.com/containerd/nerdctl/pull/1650
