### ISSUE TITLE
Flaky test: TestExecWithDoubleDash (`expected "success\n", got ""`)

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1231]
```
=== CONT  TestExecWithDoubleDash
    exec_test.go:46: container nerdctl-testexecwithdoubledash is now running
    exec_test.go:48: assertion failed: error is not nil: expected "success\n", got ""
--- FAIL: TestExecWithDoubleDash (0.97s)
```

https://github.com/containerd/nerdctl/runs/7353495895?check_suite_focus=true

https://github.com/containerd/nerdctl/blob/b89f0aa0b1701acb376b2706396b4df329f8dc1a/cmd/nerdctl/exec_test.go#L38-L49

Something seems wrong with the stdio pipes

**Comment by apostasie** [comment]
@AkihiroSuda this is working now, right?
