### ISSUE TITLE
Enhance install instructions with BuildKit steps

### ISSUE THREAD

**Issue by dhiltgen** [containerd/nerdctl#124]
While I'd love to see native OS packages (deb/rpm) so it's easier to stay up to date, the install instructions on the releases page are super helpful to get folks up and running quickly using the `full` tar file.

The one piece that's missing is further instructions on how to get BuildKit running properly so build works.

I followed the Quickstart Rootful instructions on 0.7.1, got hello world run to work, but build doesn't

```
% nerdctl build -t test .
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): stat /run/user/1000/containerd-rootless: no such file or directory
```

I think `build` will be a key use case for a lot of people coming from the docker ecosystem, so it would be nice to help them along the journey.

**Comment by AkihiroSuda** [comment]
Please try this (https://github.com/containerd/nerdctl/blob/master/docs/rootless.md)


```
containerd-rootless-setuptool.sh install

containerd-rootless-setuptool.sh install-buildkit
```

**Comment by dhiltgen** [comment]
I was hoping to find and doc the "easy path" to set up buildkit with the rootful setup.  My assumption is that's what most folks coming from the Docker ecosystem will be familiar with.  FWIW, on my Linux VM, the rootless setup script failed initially and looks like it will require additional setup steps to get working.

If BuildKit is only supported for rootless, perhaps that could be called out more explicitly in the instructions.

**Comment by AkihiroSuda** [comment]
```
$ sudo systemctl enable --now buildkit
$ sudo nerdctl build -t foo .
```
