### ISSUE TITLE
Typo: `:1` vs `::1` (IPv6 localhost)

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1242]
https://github.com/containerd/nerdctl/blob/820391725fe3ae110eca31780e51a934f65b2fc7/pkg/dnsutil/hostsstore/updater.go#L135

**Comment by AkihiroSuda** [comment]
This is not a recent regression.
Seems to have been broken since the beginning 😞 
https://github.com/containerd/nerdctl/commit/674530033cf02b16ef440897b89d721d929293c5#diff-c080efad515234c7b3838385ae9f4abebae63941a1166fe1e644353053959f19R131

**Comment by Zheaoli** [comment]
This would be fixed in #1232
