### ISSUE TITLE
`nerdctl container inspect` lacks labels

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1261]
### Description

`nerdctl container inspect` lacks labels

### Steps to reproduce the issue

Docker:
```console
$ docker run -d --name foo --label foo=bar alpine sleep infinity
$ docker container inspect foo | jq .[0].Config.Labels
{
  "foo": "bar"
}
```

nerdctl:
```console
$ nerdctl run -d --name foo --label foo=bar alpine sleep infinity
$ nerdctl container inspect foo | jq .[0].Config.Labels

```

### Describe the results you received and expected

Received: no labels
Expected: labels to be set

### What version of nerdctl are you using?

v0.22.0

**Comment by TianZong48** [comment]
can I take this?  :D
