### ISSUE TITLE
cannot work with k3s

### ISSUE THREAD

**Issue by thomasdba** [containerd/nerdctl#128]
Hello 

K3s is running ,but there is no output from nerdctl .

./nerdctl --address /run/k3s/containerd/containerd.sock ps 
CONTAINER ID    IMAGE    COMMAND    CREATED    STATUS    PORTS    NAMES

Thanks !

**Comment by AkihiroSuda** [comment]
You need to specify --namespace=k8s.io

```
nerdctl --address /run/k3s/containerd/containerd.sock --namespace k8s.io ps
```

**Comment by alwinmark** [comment]
Is there a way I can put the --address parameter into a config file or do I need to create a wrapper or set an alias?

**Comment by AkihiroSuda** [comment]
> Is there a way I can put the --address parameter into a config file or do I need to create a wrapper or set an alias?

Adding `export CONTAINERD_ADDRESS=/run/k3s/containerd/containerd.sock` to `.bash_profile` should work.

nerdctl v0.16 will support `nerdctl.toml` file too https://github.com/containerd/nerdctl/blob/master/docs/config.md
