### ISSUE TITLE
nerdctl build  image by Dockerfil failed (`exit code: 139`)

### ISSUE THREAD

**Issue by GodYao1995** [containerd/nerdctl#1282]
### Description

[root@g10 temps]# nerdctl build -t ng:nerdctl -f Dockerfile .
[+] Building 5.0s (5/5) FINISHED
 => [internal] load build definition from Dockerfile                                    0.0s
 => => transferring dockerfile: 141B                                                    0.0s
 => [internal] load .dockerignore                                                       0.0s
 => => transferring context: 2B                                                         0.0s
 => [internal] load metadata for docker.io/library/nginx:latest                         4.8s
 => CACHED [1/2] FROM docker.io/library/nginx:latest@sha256:bd06dfe1f8f7758debd49d3876  0.0s
 => => resolve docker.io/library/nginx:latest@sha256:bd06dfe1f8f7758debd49d3876023992d  0.0s
 => ERROR [2/2] RUN echo "Hello World"                                                  0.1s
------
 > [2/2] RUN echo "Hello World":
------
Dockerfile:3
--------------------
   1 |     FROM nginx:latest
   2 |
   3 | >>> RUN echo "Hello World"
   4 |
   5 |
--------------------
error: failed to solve: process "/bin/sh -c echo \"Hello World\"" did not complete successfully: exit code: 139
FATA[0005] unrecognized image format
[root@g10 temps]#

### Steps to reproduce the issue

1. nerdctl build -t ng:nerdctl -f Dockerfile .
3.
4.

### Describe the results you received and expected

Dockerfile cmd. "RUN" can not success

BUT COPY is ok

[root@g10 temps]# nerdctl build -t ng:nerdctl -f Dockerfile .
[+] Building 3.6s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                    0.0s
 => => transferring dockerfile: 125B                                                    0.0s
 => [internal] load .dockerignore                                                       0.0s
 => => transferring context: 2B                                                         0.0s
 => [internal] load metadata for docker.io/library/nginx:latest                         1.3s
 => [internal] load build context                                                       0.2s
 => => transferring context: 40.58MB                                                    0.2s
 => CACHED [1/2] FROM docker.io/library/nginx:latest@sha256:bd06dfe1f8f7758debd49d3876  0.0s
 => => resolve docker.io/library/nginx:latest@sha256:bd06dfe1f8f7758debd49d3876023992d  0.0s
 => [2/2] COPY . .                                                                      0.0s
 => exporting to oci image format                                                       2.0s
 => => exporting layers                                                                 1.1s
 => => exporting manifest sha256:eea985dafb3147ff1e213b9864cf1268222ce2bbc969e52a5d51b  0.0s
 => => exporting config sha256:3a196b08f7bdac6d7c8cd45f7ce27c1f639d422581ca02987d09151  0.0s
 => => sending tarball                                                                  0.9s
unpacking docker.io/library/ng:nerdctl (sha256:eea985dafb3147ff1e213b9864cf1268222ce2bbc969e52a5d51bad4fbd4a0bc)...done

### What version of nerdctl are you using?

[root@g10 temps]# nerdctl version
Client:
 Version:	v0.22.0
 OS/Arch:	linux/arm64
 Git commit:	8e278e2aa61a89d4e50d1a534217f264bd1a5ddf
 buildctl:
  Version:	v0.10.3
  GitCommit:	c8d25d9a103b70dc300a4fd55e7e576472284e31

Server:
 containerd:
  Version:	v1.6.6
  GitCommit:	10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:	1.1.2
  GitCommit:	v1.1.2-0-ga916309f
[root@g10 temps]#

### Host information

[root@g10 temps]# nerdctl info
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v1.6.6
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.11.12-300.el8.aarch64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 4.295GiB
 Name: g10
 ID: 11bb3da9-55b4-410e-9964-0bfbdfa64b6b

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by GodYao1995** [comment]
check buildkitd  find :

Jul 31 13:05:47 g10 buildkitd[2453]: time="2022-07-31T13:05:47+08:00" level=warning msg="using host network as the default"
Jul 31 13:05:47 g10 buildkitd[2453]: time="2022-07-31T13:05:47+08:00" level=info msg="found worker \"sltzqyqx5nd5y55iwku2j4uqr\", labels=map[org.moby>
Jul 31 13:05:47 g10 buildkitd[2453]: time="2022-07-31T13:05:47+08:00" level=info msg="found 1 workers, default=\"sltzqyqx5nd5y55iwku2j4uqr\""
Jul 31 13:05:47 g10 buildkitd[2453]: time="2022-07-31T13:05:47+08:00" level=warning msg="currently, only the default worker can be used."
Jul 31 13:05:47 g10 buildkitd[2453]: time="2022-07-31T13:05:47+08:00" level=info msg="running server on /run/buildkit/buildkitd.sock"
Jul 31 13:07:10 g10 buildkitd[2453]: time="2022-07-31T13:07:10+08:00" level=error msg="/moby.buildkit.v1.Control/Solve returned error: rpc error: cod

**Comment by AkihiroSuda** [comment]
Does `sudo buildctl build --frontend dockerfile.v0 --local dockerfile=. --local context=.` work?

**Comment by GodYao1995** [comment]
[root@g10 temps]# cat Dockerfile
FROM nginx:alpine

RUN echo "Hello World"


[root@g10 temps]# buildctl build --frontend dockerfile.v0 --local dockerfile=. --local context=.
[+] Building 0.5s (5/5) FINISHED
 => [internal] load build definition from Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 141B                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                            0.0s
 => => transferring context: 2B                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/nginx:alpine                                                                              0.3s
 => CACHED [1/2] FROM docker.io/library/nginx:alpine@sha256:9c2030e1ff2c3fef7440a7fb69475553e548b9685683bdbf669ac0829b889d5f                 0.0s
 => => resolve docker.io/library/nginx:alpine@sha256:9c2030e1ff2c3fef7440a7fb69475553e548b9685683bdbf669ac0829b889d5f                        0.0s
 => ERROR [2/2] RUN echo "Hello World"                                                                                                       0.1s
------
 > [2/2] RUN echo "Hello World":
------
Dockerfile:3
--------------------
   1 |     FROM nginx:alpine
   2 |
   3 | >>> RUN echo "Hello World"
   4 |
   5 |
--------------------
error: failed to solve: process "/bin/sh -c echo \"Hello World\"" did not complete successfully: exit code: 139
[root@g10 temps]#

**Comment by GodYao1995** [comment]
find the same issue:

RHEL8 VM environment: error: failed to solve: process /bin/sh . exit code : 139 #2705
https://github.com/moby/buildkit/issues/2705

**Comment by GodYao1995** [comment]
anyway, I download  v0.10.3 version and try agian.
it works;
