### ISSUE TITLE
nerdctl run not support --pid=container:xxxx and --ipc=container:xxx but docker is  supported

### ISSUE THREAD

**Issue by ibayue** [containerd/nerdctl#1293]
### Description

nerdctl run not support --pid=container:xxxx and --ipc=container:xxx but docker is  supported

![image](https://user-images.githubusercontent.com/11729209/182340337-a8aeeaeb-d160-43eb-baaf-d90530958c1b.png)

![image](https://user-images.githubusercontent.com/11729209/182340814-05cf8f46-fc6c-447c-b9f2-3c300219ecb7.png)

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

Using nerdctl to create a new container can share pid ipc with other containers

### What version of nerdctl are you using?

 0.22.2

**Comment by fahedouch** [comment]
`joins another container's PID namespace` is not yet supported , same thing for `ipc`

**Comment by minuk-dev** [comment]
I think this issue was resolved by https://github.com/containerd/nerdctl/pull/2757, https://github.com/containerd/nerdctl/pull/1411. Could you check it?

**Comment by djdongjin** [comment]
Close as completed by #2757
