### ISSUE TITLE
run nerdctl with --group-add report error group not found 

### ISSUE THREAD

**Issue by reich80** [containerd/nerdctl#1299]
### Description

I run the nerdctl with following version:

[root@Cc5Apc ~]# nerdctl --version
nerdctl version 0.22.2

[root@Cc5Apc ~]# containerd --version
containerd containerd.io 1.6.6 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1

and run a container with --group-add parameter, it failed and report message to show that group not found. The details are as follows:

[root@Cc5Apc ~]# id nerdtest
uid=15024(nerdtest) gid=15024(nerdtest) 组=15025(nerdgroup1),15026(nerdgroup2),15024(nerdtest)

[root@Cc5Apc ~]# nerdctl -H unix:///run/containerd/containerd.sock run --cpu-shares 10 --memory 67108864 -v /home/zhao:/home/zhao:rw -v /home/wenjie/scripts:/home/wenjie/scripts:rw --net none --hostname Cc5Apc --entrypoint /bin/bash --name srm-60e29ac1-681c-467d-9dc5-28bafddbf995 --workdir=/home/zhao --user=15024:15024 --group-add=15026 --group-add=15025 -v /var/run:/var/run registry.servicemgr.apc:5000/gatk3 -c /home/wenjie/scripts/test-bash.sh

FATA[0000] mount callback failed on /run/user/0/containerd-mount3203707728: unable to find group 15026 

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

the group-add feature should work exactly as docker

### What version of nerdctl are you using?

nerdctl version 0.22.2

**Comment by junnplus** [comment]
`--group-add` flag requires the image have corresponding user groups instead of host.

Please check the `/etc/group` file in the image.

**Comment by reich80** [comment]
That doesn't work in ldap cases.  If the host authenticate users via ldap, then /etc/group in image or host definitely doesn't have all the groups.  Why does docker work in this case?  It is reasonable to behave the same way as docker.

**Comment by reich80** [comment]
It is reasonable to check the user/group relation at the time running the "nerdctl run" command.  It is not necessary to check it in the container.  Otherwise, any container which is launched by nerdctl need have ldap installed inside it. It places heavy burden on the end user who created the docker image, which discourage users to use docker/nerdctl in the production environment.

**Comment by junnplus** [comment]
https://github.com/containerd/containerd/pull/7257
