### ISSUE TITLE
TestRunCopyingUpInitialContentsOnDockerfileVolume is flaky

### ISSUE THREAD

**Issue by manugupt1** [containerd/nerdctl#1305]
### Description

https://github.com/containerd/nerdctl/runs/7736362053?check_suite_focus=true

Error logs

```
    run_mount_linux_test.go:162: assertion failed: error is not nil: expected "hi\n", got ""
```

**Comment by apostasie** [comment]
Have not seen this fail in recent memory.

Given we rewrote the volume store code to handle concurrency, I would think this got fixed?
@manugupt1 @junnplus @AkihiroSuda should we close this?
