### ISSUE TITLE
Support SOCI snapshotter

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1329]
https://github.com/awslabs/soci-snapshotter

**Comment by Zheaoli** [comment]
I'm interested about this feature, maybe I can make a try(

**Comment by djdongjin** [comment]
@Zheaoli I'd like to work on this if you haven't started :)

**Comment by Zheaoli** [comment]
> @Zheaoli I'd like to work on this if you haven't started :)

Sorry about this，I have worked on it already ：）

**Comment by djdongjin** [comment]
np :) let me know if you need a review when the PR is out and I'd like to learn more about it

**Comment by ningziwen** [comment]
@AkihiroSuda Do you think we can just package SOCI in nerdctl-full at the same time of supporting soci pull and run? SOCI is around 20MB now. https://github.com/awslabs/soci-snapshotter/releases

**Comment by CodeChanning** [comment]
@AkihiroSuda  Hi, I'm working on #2347 to support soci in pull and run. I'm also wondering if SOCI could be packaged in nerdctl-full.

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda Do you think we can just package SOCI in nerdctl-full at the same time of supporting soci pull and run? SOCI is around 20MB now. https://github.com/awslabs/soci-snapshotter/releases

I fear that we will end up including every third party snapshotter in the nerdctl-full bundle, so I'm not inclined to do that.

This is still negotiable, but if we are going to including SOCI (and other snapshotters) in the `nerdctl-full` bundle, probably we should rename the current `nerdctl-full` to something like `nerdctl-large`.
Lima will use `nerdctl-large` by default, but Finch may use the new `nerdctl-full` by default.

**Comment by ningziwen** [comment]
@AkihiroSuda Sounds good. For the current change., we will just exclude SOCI from nerdctl distribution.

I think other dependencies like Cosign, Notation are in the same situation.

In the future, we can potentially include them in `nerdctl-full` and keep current one as `nerdctl-large or nerdctl-core`.

Letting downstream manage the dependencies by themselves is also not bad. (Package their own nerdctl tar and overwrite in Lima local archive) This can offload the logic of nerdctl distribution.

**Comment by ningziwen** [comment]
@AkihiroSuda Should we resolve the issue?
