### ISSUE TITLE
Support filter in `nerdctl volume ls` command

### ISSUE THREAD

**Issue by Zheaoli** [containerd/nerdctl#1330]
### What is the problem you're trying to solve

Just following #54, to support the filter argument in `nerdctl volume ls` command 

- [ ] filtering by label
- [ ] filtering by name

### Describe the solution you'd like

Support filter in `nerdctl volume ls` command

**Comment by Retrospection** [comment]
I'd like to fix this.

**Comment by yuchanns** [comment]
Assign to me plz.
