### ISSUE TITLE
Support filter argument in `nerdctl container ls` command

### ISSUE THREAD

**Issue by Zheaoli** [containerd/nerdctl#1339]
### What is the problem you're trying to solve

Just following the #54 to support filter argument in `nerdctl container ls` command.

FYI https://github.com/moby/moby/blob/master/daemon/list.go#L20

### Describe the solution you'd like

- [ ] before
- [ ] existed
- [ ] id
- [ ] label
- [ ] name
- [ ] status
- [ ] since
- [ ] volume
- [ ] network

**Comment by yuchanns** [comment]
I'd like to fix it
