### ISSUE TITLE
`nerdctl compose run` should randomize the container name

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1345]
> Found a minor incompatibility: `docker compose run` randomize container name (`compose-wordpress_db_run_cca27158caa2 `) but `nerdctl compose run` does not (`compose-wordpress_db_1).

_Originally posted by @AkihiroSuda in https://github.com/containerd/nerdctl/issues/1340#issuecomment-1232668700_

**Comment by minuk-dev** [comment]
I could not find any documentation about the container's name in `compose run`.

Can we just implement it to make it work like that?

**Comment by AkihiroSuda** [comment]
> I could not find any documentation about the container's name in compose run.

https://github.com/docker/compose/blob/v2.10.2/pkg/compose/run.go#L63-L66
