### ISSUE TITLE
Support `syslog` driver for nerdctl 

### ISSUE THREAD

**Issue by Zheaoli** [containerd/nerdctl#1353]
### What is the problem you're trying to solve

Based on the fact that docker has supported the `syslog` driver, and the syslog is one of the most popular logging ways for developers and is also supported in go std-lib

I think it's good to support syslog as an extension of #1039 

FYI https://docs.docker.com/config/containers/logging/configure/#supported-logging-drivers

### Describe the solution you'd like

- [ ] support syslog driver

**Comment by yuchanns** [comment]
I would like to have a try

**Comment by fahedouch** [comment]
can track logging driver enhancement on this ticket plz https://github.com/containerd/nerdctl/issues/1039
