### ISSUE TITLE
FATA[0000] unknown flag: --filter (Unable to use -f/--filter option with nerdctl ps)

### ISSUE THREAD

**Issue by ChandraReddy** [containerd/nerdctl#1364]
### Description

FATA[0000] unknown flag: --filter (Unable to use -f/--filter option with **nerdctl ps**)

We have option called -f/--filter in the **docker ps**, same here I have tried but getting FATA error.

Command: nerdctl ps -f "name=an_gnodeb", nerdctl ps --filter "name=an_gnodeb"
Error: FATA[0000] unknown flag: --filter

Could you help me on this?

### Steps to reproduce the issue

1. Execute nerdctl ps command with -f option 
2. Look for error - FATA[0000] unknown shorthand flag: 'f' in -f
3.

### Describe the results you received and expected

Docker ps -f option gives us filtered container name, same here also expecting.

### What version of nerdctl are you using?

Version:       v0.22.2
 OS/Arch:       linux/amd64

### Host information

 OS/Arch:       linux/amd64

**Comment by AkihiroSuda** [comment]
Please try the master branch or just wait until v0.23

- https://github.com/containerd/nerdctl/pull/1342
