### ISSUE TITLE
Make it possible to set the zstd compression level

### ISSUE THREAD

**Issue by paolobarbolini** [containerd/nerdctl#1367]
### What is the problem you're trying to solve

I'm recompressing my images using `nerdctl image convert --oci --zstdchunked`. Unfortunately looking at the code it seems to use the default zstd compression level of 3, which is too low for my needs. The resulting zstd images are almost the same size as the gzipped ones.

### Describe the solution you'd like

Have a flag that allows setting the zstd compression level.

### Additional context

If I `nerdctl save` my images, get the layers out of the `.tar` generated by it, decompress them and recompress them with `zstd --ultra -22 -k` I almost halve the layer size for an acceptable compression time increase.

**Comment by djdongjin** [comment]
@paolobarbolini can you share where you find the default zstd compression level is 3? 🤔 I thought it was 9.

Also, it seems all `estargz` flags work for `zstd` (`estargz-compression-level`, `estargz-chunk-size`, etc) [link](https://github.com/containerd/nerdctl/blob/78de68a78b24afe97d07e9c9b1fccdca76c8a63d/cmd/nerdctl/image_convert.go#L156), though the naming is indeed confusing. I guess maybe by sepcifying `estargz-compression-level` with `zstdchunked`, you can make it work probably.

**Comment by AkihiroSuda** [comment]
> Also, it seems all estargz flags work for zstd (estargz-compression-level, estargz-chunk-size, etc) [link](https://github.com/containerd/nerdctl/blob/78de68a78b24afe97d07e9c9b1fccdca76c8a63d/cmd/nerdctl/image_convert.go#L156), though the naming is indeed confusing.

Looks like a bug
cc @ktock
