### ISSUE TITLE
Support `version` subcommand to `compose`

### ISSUE THREAD

**Issue by callahad** [containerd/nerdctl#1368]
### What is the problem you're trying to solve

I'd like write a script that invokes `docker compose` and works with both Docker and Nerdctl.

To do so reliably, I need to detect whether the `compose` command is supported (e.g., `docker compose` is provided by an optional plugin, so I can't assume anything and must explicitly check).

An easy way to detect support would be to run a safe command like `docker compose version` and check its exit status. This would let me know if I can proceed to calling `docker compose up -d`, or if I need to print out additional help text for the user.

### Describe the solution you'd like

Running `nerdctl compose version` should print the nerdctl version and exit successfully.

### Additional context

None of nerdctl's supported `compose` commands appear completely safe to invoke with no risk of having side effects or depending on the surrounding environment, so I can't substitute a different, existing command at this point in time.

**Comment by yardenshoham** [comment]
I'll take this

**Comment by callahad** [comment]
Thank you very much, @yardenshoham and @AkihiroSuda
