### ISSUE TITLE
add support for `diff` on running container

### ISSUE THREAD

**Issue by ndeloof** [containerd/nerdctl#1376]
### What is the problem you're trying to solve

Please add support for `docker diff` to inspect changes to files or directories on a running container

### Describe the solution you'd like

```
$ nerdctl diff <container>
C /etc
D /etc/profile
A /foo
```

**Comment by djdongjin** [comment]
Not sure if this doable in nerdctl/containerd. I think even `docker` cannot calcuate this kind of diff when snapshotter is used (if I track the `docker` cli call correctly, the below func is used when `docker diff` is callled):

https://github.com/moby/moby/blob/3df160a410b33b3253c7aff814a85322a0883274/daemon/changes.go#L23-L25

**Comment by AkihiroSuda** [comment]
> Not sure if this doable in nerdctl/containerd. I think even `docker` cannot calcuate this kind of diff when snapshotter is used (if I track the `docker` cli call correctly, the below func is used when `docker diff` is callled):
> 
> https://github.com/moby/moby/blob/3df160a410b33b3253c7aff814a85322a0883274/daemon/changes.go#L23-L25


They have the `diff` implementation in the `rumpl/moby` tree:
- https://github.com/rumpl/moby/pull/91
(The current implementation seems specific to the overlayfs snapshotter?)

**Comment by laurazard** [comment]
> They have the diff implementation in the rumpl/moby tree:
> 
> https://github.com/rumpl/moby/pull/91
(The current implementation seems specific to the overlayfs snapshotter?)

I just tried it and the implementation in the `rumpl/moby` fork seems to work fine with other snapshotters (at least `stargz`).

**Comment by islishude** [comment]
https://github.com/moby/moby/pull/44964

it's merged

**Comment by nrvnrvn** [comment]
Does it mean next release of nerdctl will support this?

**Comment by AkihiroSuda** [comment]
> it's merged

Not merged into nerdctl

**Comment by islishude** [comment]
Landed in 1.7.1 :)

this issue can be closed now.
