### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1396]
I think we are in a good state to release v1.0 (or v24).

I was initially planning to include the following issue in v1.0, but none of them is a blocker:
- #317
- #1187

cc @containerd/nerdctl-maintainers

**Comment by ktock** [comment]
SGTM

**Comment by yardenshoham** [comment]
I'd say #317 is not a blocker but #1187 is a blocker. I have used `-d` with `--rm` before.

**Comment by fahedouch** [comment]
SGTM

**Comment by Zheaoli** [comment]
I perfer release v1.0 after #1187

**Comment by AkihiroSuda** [comment]
@yardenshoham @Zheaoli 

How is `-d --rm` expected to be used?
How to get the logs and the exit code with `-d --rm` ?

**Comment by Zheaoli** [comment]
> How to get the logs and the exit code with `-d --rm` ?

Actually, we don't.

The `--rm -d` is used in some one-time containers. We don't need to reuse this container, and we need to run it in the background. We always collect the log using some log drivers such as fluentd or others.

**Comment by estesp** [comment]
This was an early request in the Docker engine and finally was added in v1.13.0 (2016) by moving the handling of `--rm` to the daemon side; curious whether an implementation in `nerdctl` would effectively require containerd core changes to mark a container resource as "please delete me when I exit": https://github.com/moby/moby/pull/20848

**Comment by yardenshoham** [comment]
> This was an early request in the Docker engine and finally was added in v1.13.0 (2016) by moving the handling of `--rm` to the daemon side; curious whether an implementation in `nerdctl` would effectively require containerd core changes to mark a container resource as "please delete me when I exit": [moby/moby#20848](https://github.com/moby/moby/pull/20848)

As this seems like a very big effort, I'm OK with dropping #1187 for v1.0

**Comment by AkihiroSuda** [comment]
I'm planning to ship the next release soon, right after bumping up dependencies such as BuildKit

@containerd/nerdctl-maintainers Should it be v1.0, or still v0.23.1 ?

**Comment by AkihiroSuda** [comment]
@ktock @Zheaoli Thanks for your SGTM/LGTM in https://github.com/containerd/nerdctl/pull/1454

@fahedouch @jsturtevant @junnplus PTAL

**Comment by AkihiroSuda** [comment]
Released 🎉 
https://github.com/containerd/nerdctl/releases/tag/v1.0.0
