### ISSUE TITLE
`nerdctl build` should accept `--output <DIR`> as an alias of `--output type=local,dest=<DIR>`

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1422]
### Description

`nerdctl build` should accept `--output <DIR`> as an alias of `--output type=local,dest=<DIR>`, as in `docker build`.

### Steps to reproduce the issue

`nerdctl build --output . .`

### Describe the results you received and expected

Received: `error: invalid value .`
Expected: Should work as `--output type=local,dest=$(pwd)`

### What version of nerdctl are you using?

nerdctl version 0.23.0-26-g67c0f59

**Comment by Zheaoli** [comment]
I think this can be a good first issue?  cc @AkihiroSuda

**Comment by yuchanns** [comment]
Assign me plz
