### ISSUE TITLE
`nerdctl compose down` with orphan container should keep the same behavior with docker

### ISSUE THREAD

**Issue by stillfox-lee** [containerd/nerdctl#1425]
### What is the problem you're trying to solve

When we execute `nerdctl compose down`. nerdctl does not check is three any other containers still in the network and just remove it.

### Describe the solution you'd like

While `docker compose down` will return error and not remove the network. We should keep the same behavior with it.

### Additional context

The orphan container [scenario](https://github.com/containerd/nerdctl/issues/1344#issuecomment-1241475088)

**Comment by Retrospection** [comment]
I'd like to try to solve this~
