### ISSUE TITLE
cant install with brew 

### ISSUE THREAD

**Issue by ehsanpo** [containerd/nerdctl#1439]
### Description

Was trying to install nerdcli on Macos Monterey 12.6 using the command

`brew install nerdctl`

Got this error massage :
```
❯ brew install nerdctl
nerdctl: Linux is required for this software.
Error: nerdctl: An unsatisfied requirement failed this build.
```

### Describe the results you received and expected

Be able to install on osx.

### What version of nerdctl are you using?

--

**Comment by AkihiroSuda** [comment]
Expected behavior.
Please try Lima, Rancher Desktop, or Colima to run nerdctl on macOS (via a Linux virtual machine)

> 
> ### Does nerdctl run on macOS ?
> 
> Yes, via a Linux virtual machine.
> 
> [Lima](https://github.com/lima-vm/lima) project provides Linux virtual machines for macOS, with built-in integration for nerdctl.
> 
> ```console
> $ brew install lima
> $ limactl start
> $ lima nerdctl run -d --name nginx -p 127.0.0.1:8080:80 nginx:alpine
> ```
> 
> [Rancher Desktop for Mac](https://rancherdesktop.io/) and [colima](https://github.com/abiosoft/colima) also provide custom Lima machines with nerdctl.
> 
>
