### ISSUE TITLE
[Planned on Nov 4, 2022] switch to main as default branch

### ISSUE THREAD

**Issue by fahedouch** [containerd/nerdctl#1444]
### What is the problem you're trying to solve

Hello,

Most of  nerdctl related project(s) default branches have been changed to `main` eg..: `containerd core project`. So it is confusing  to work with `master` branch

### Describe the solution you'd like

rename default branch to `main`

### Additional context

Why renaming to main ?  https://github.com/github/renaming#why-main
take consideration of this points:  https://github.com/github/renaming#whats-already-changed

**Comment by Zheaoli** [comment]
SGTM

**Comment by junnplus** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
SGTM, but can we have a couple of weeks as a grace period?

**Comment by fahedouch** [comment]
> SGTM, but can we have a couple of weeks as a grace period?

For sure.

**Comment by AkihiroSuda** [comment]
Let's do this two weeks later (Nov 4)

**Comment by fahedouch** [comment]
> Let's do this two weeks later (Nov 4)

@AkihiroSuda Why are you postponing the switch ?  shall I start working on this (switch content reference to `main`) or I have to wait for (Nov 4)

**Comment by AkihiroSuda** [comment]
To minimize possibility of breaking somebody's environments, let's have two weeks of grace period

**Comment by AkihiroSuda** [comment]
Done
