### ISSUE TITLE
[compose] Add argument to build/push specific service(s)

### ISSUE THREAD

**Issue by Sebor** [containerd/nerdctl#1450]
### What is the problem you're trying to solve

Some docker-compose files may have multiple services, but you don't want to build/push all of them

### Describe the solution you'd like

The command should look something like

```bash
nedrctl compose build [SERVICE...]
nerdctl compose push [SERVICE...]
```

(like in original [docker-compose](<https://docs.docker.com/engine/reference/commandline/compose_build/>))

**Comment by yuchanns** [comment]
Leave it to me.

**Comment by djdongjin** [comment]
@yuchanns hi have you started working on this? otherwise I'd like to give it a try. thanks.

**Comment by yuchanns** [comment]
> @yuchanns hi have you started working on this? otherwise, I'd like to give it a try. thanks.

It's yours.
