### ISSUE TITLE
CI: switch away from Docker Hub

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#146]
https://github.com/containerd/nerdctl/blob/ed8eec8dbb8a62e9f1634137be6a1bc6cdc4b34c/pkg/testutil/testutil.go#L276-L282

Docker Hub has rate limit, and OTOH `mirror.gcr.io` seems unstable:
```
docker: Error response from daemon: manifest for mirror.gcr.io/library/nginx:1.19-alpine not found: manifest unknown: Failed to fetch "1.19-alpine" from request "/v2/library/nginx/manifests/1.19-alpine".
```

We are currently using ~`mirror.gcr.io`~ (EDIT: switched back to plain old Docker Hub: https://github.com/containerd/nerdctl/pull/148)  but should switch to something else.

Requirements:
- No rate limit
- Stable
- Provides multi-arch images for `alpine:3.13`, `nginx:1.19-alpine`, and `registry:2`

**Comment by AkihiroSuda** [comment]
@ktock 
Do you think we can use `org` images under `ghcr.io/stargz-snapshotter`? (Are they guaranteed to be multi-arch?)

**Comment by ktock** [comment]
>  Do you think we can use org images under ghcr.io/stargz-snapshotter? (Are they guaranteed to be multi-arch?)

Makes sense.
They are copied using `crane` by ggcr so the entire image (including all platforms) is copied.

**Comment by AkihiroSuda** [comment]
I switched back from mirror.gcr.io to plain old Docker Hub in https://github.com/containerd/nerdctl/pull/148.

I'll use `ghcr.io/stargz-snapshotter/<IMAGE>:<TAG>-org` if we hit rate limit again.

**Comment by fahedouch** [comment]
we can specify credentials for container downloading: https://github.blog/changelog/2020-09-24-github-actions-private-registry-support-for-job-and-service-containers/  and increase the rate limit

**Comment by AkihiroSuda** [comment]
Not seeing rate limit on macOS on GHA recently, closing

**Comment by AkihiroSuda** [comment]
Seeing rate limit again

``        
521
        Stderr:   time="2021-04-13T10:55:12Z" level=fatal msg="failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/alpine/manifests/sha256:ec14c7992a97fc11425907e908340c6c3d6ff602f5f13d899e6b7027c9b4133a: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
522
``

**Comment by ktock** [comment]
I've copied images listed in the above issue description into `ghcr.io/stargz-containers`:

- `alpine:3.13-org`: https://github.com/orgs/stargz-containers/packages/container/alpine/2004710
- `nginx:1.19-alpine-org`: https://github.com/orgs/stargz-containers/packages/container/nginx/2004741
- `registry:2-org`: https://github.com/orgs/stargz-containers/packages/container/registry/2004762

Please feel free to use them.

**Comment by AkihiroSuda** [comment]
Thanks, we now also need wordpress and mariadb

**Comment by fahedouch** [comment]
thank you @ktock 

@AkihiroSuda  did you see the rate limit in jobs other than cgroupv2 ( it looks like it is not running on  GA runners) because GitHub has reached a deal with docker to avoid the pull limits : https://github.com/actions/virtual-environments/issues/1445#issuecomment-729675520  ?

**Comment by AkihiroSuda** [comment]
> did you see the rate limit in jobs other than cgroupv2

no
