### ISSUE TITLE
The CIDR of the bridge can't be changed (`network with name bridge already exists`)

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1490]
>   I tried to modify the network config with just `nerdctl`, but it looks like there is no way to edit an existing network, and I can't delete the `bridge` network; it is being recreated right away:
> 
> ```console
> $ nerdctl network rm bridge
> bridge
> $ nerdctl network create bridge --gateway 10.10.10.1 --subnet 10.10.10.0/24
> FATA[0000] network with name bridge already exists
> $ nerdctl network inspect bridge
> [
>     {
>         "Name": "bridge",
>         "Id": "17f29b073143d8cd97b5bbe492bdeffec1c5fee55cc1fe2112c8b9335f8b6121",
>         "IPAM": {
>             "Config": [
>                 {
>                     "Subnet": "10.4.0.0/24",
>                     "Gateway": "10.4.0.1"
>                 }
>             ]
>         },
>         "Labels": {}
>     }
> ]
> ```

_Originally posted by @jandubois in https://github.com/rancher-sandbox/rancher-desktop/issues/3365#issuecomment-1308233426_
      

Seems regression in v0.22.1
- https://github.com/containerd/nerdctl/pull/1245

**Comment by Zheaoli** [comment]
like https://github.com/containerd/nerdctl/issues/1425, If we allow people to change the CIDR of a network configuration, I think it would be better to validate if there is any container existed related with this network

**Comment by AkihiroSuda** [comment]
> like #1425, If we allow people to change the CIDR of a network configuration, I think it would be better to validate if there is any container existed related with this network

Yes, it should be validated

**Comment by fahedouch** [comment]
I believe that we have to exclude  `e.ensureDefaultNetworkConfig()`  From `NewCNIEnv(cniPath, cniConfPath string)`. I take this ticket

**Comment by fahedouch** [comment]
closed by https://github.com/containerd/nerdctl/pull/1554
