### ISSUE TITLE
FATA[0003] error saving credentials: error storing credentials - err: exit status 22, out: ``

### ISSUE THREAD

**Issue by bernardoforcillo** [containerd/nerdctl#1510]
### Description

error generated login to docker repository

### Describe the results you received and expected

The expected result is succefully logged in. But i'n not.

### What version of nerdctl are you using?

Client:
 Version:       v0.23.0
 OS/Arch:       linux/amd64
 Git commit:    660680b7ddfdebc1q2ud34rkq786qneq4gxzjydw8l3zvycpmlcelnx
 buildctl:
  Version:      v0.10.4
  GitCommit:    a2ba6869bc1q2ud34rkq786qneq4gxzjydw8l3zvycpmlcelnx

Server:
 containerd:
  Version:      v1.6.8
  GitCommit:    9cdbc1q2ud34rkq786qneq4gxzjydw8l3zvycpmlcelnx
 runc:
  Version:      1.1.4
  GitCommit:    5fd4c4dbc1q2ud34rkq786qneq4gxzjydw8l3zvycpmlcelnx

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Rancher Desktop for Windows

### Host information

Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.8
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Rancher Desktop WSL Distribution
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 3.306GiB
 Name: PORTATILE-BERNARDO
 ID: b447fa47-633f-4afa-8dca-ca23f62350ce

**Comment by AkihiroSuda** [comment]
> Steps to reproduce the issue

Please provide this

**Comment by bernardoforcillo** [comment]
`nerdctl login -u bernardoforcillo -p {my_password}`
