### ISSUE TITLE
new Logo design for nerdctl

### ISSUE THREAD

**Issue by developer-guy** [containerd/nerdctl#1542]
### What is the problem you're trying to solve

The OpenSSF organization has announced the new [landscape](https://landscape.openssf.org/) design. In that landscape, there is a [tab](https://landscape.openssf.org/sigstore) for the Sigstore community, which helps people add tools signed with Sigstore tooling or integrate with Sigstore tooling. As we integrate cosign tool with the nerdctl, I thought that we could add nerdctl to the landscape, but there is no logo design available for nerdctl yet.

### Describe the solution you'd like

create a new logo design for nerdctl

**Comment by Dentrax** [comment]
> If we are going to create the logo, I'd expect the containerd logo (Just `d` would be fine) to be embedded in the nerdctl logo.

As non-graphical expect at logo design, we tried to design a simple logo with @developer-guy. 

Design steps:
1. Rotate containerd logo CW
2. Place 2 black placeholders at top/bottom in the center of right-rotated `d`
3. Add black block to lower `t`'s tail (cut in the middle)
4. Append `l` approximately same size

Idea is to respect official `d` logo, if we about to rotate our head CW, we should barely see the `d` logo.

Here are some simple versions:

![nerdctl-logo-v1](https://user-images.githubusercontent.com/16493751/203716120-3ea2a8ed-289f-47ba-be9e-258673c4f639.png)

![nerdctl-logo-v2](https://user-images.githubusercontent.com/16493751/203716132-b7dfb476-c18d-459c-bc92-2b26c56216fe.png)

**Comment by AkihiroSuda** [comment]
That logo just reads "ctl" or "cll"

What about:

![image](https://user-images.githubusercontent.com/9248427/203720641-8b213da6-a13b-4368-9222-0540660f2006.png)

**Comment by developer-guy** [comment]
What is the next step, then? May I create a folder called `artwork` or something like that to store the png and SVG contents? @AkihiroSuda

**Comment by developer-guy** [comment]
Any ideas to make high-quality SVG vectors @dentrax ?

**Comment by AkihiroSuda** [comment]
Needs to discuss with core committees and maybe CNCF for usage of the altered containers logo.

Also we might need to adjust the  spaces and the font of "l' .

**Comment by Dentrax** [comment]
> What about:
> 
> ![image](https://user-images.githubusercontent.com/9248427/203720641-8b213da6-a13b-4368-9222-0540660f2006.png)

IMHO, I'm slightly -1 with long form of logos that contains texts. (I don't imply this is bad, actually it's nice!) Since it'd be hard to draw and remember in the first place. The logo would be much great if it's in much clear, and rememberable form. (Since I'm not a graphical artist, you can completely ignore this! Core committees would make better decision as you said.)

**Comment by developer-guy** [comment]
> Needs to discuss with core committees and maybe CNCF for usage of the altered containers logo.
> 
> Also we might need to adjust the spaces and the font of "l' .

Who can we ping to start generating the nerdctl logo in the CNCF? Any names?

**Comment by developer-guy** [comment]
kindly ping @AkihiroSuda 👋
