### ISSUE TITLE
[CentOS 7] cannot delete container /var/cache/ after with build  use USER <username>

### ISSUE THREAD

**Issue by mengxifl** [containerd/nerdctl#1543]
### Description

cannot delete container /var/cache/ after with build  use USER <username>

### Steps to reproduce the issue

1.dockerfile is 
```
# FROM alpine
# RUN apk add --no-cache bash && \
#   addgroup -S testuser && adduser -S testuser -G testuser

FROM centos:centos7.9.2009
RUN yum install -y bash && \
  adduser testuser

WORKDIR /data
USER testuser

CMD ["sleep", "100000000"]
```
2. nerdctl build -t test:test .
3. nerdctl run --rm --name=test test:tes
4. nerdctl exec -it --user=root test /bin/bash
5. rm -rf /var/cache/
rm: cannot remove '/var/cache/ldconfig': Directory not empty
rm: cannot remove '/var/cache/yum/x86_64/7/base/gen': Directory not empty
rm: cannot remove '/var/cache/yum/x86_64/7/extras/gen': Directory not empty
rm: cannot remove '/var/cache/yum/x86_64/7/updates/gen': Directory not empty

### Describe the results you received and expected

use root user  I can delete it . May be I lost some parms ?

### What version of nerdctl are you using?

1.0

### Host information

centos7.9 
3.10.0-1160.el7.x86_64

**Comment by apostasie** [comment]
centos is discontinued - so, tried with Debian.

I cannot reproduce. Things are working correctly for me.

@mengxifl could you try again with nerdctl v2.0-rc and confirm that this is fixed?

Thanks!

**Comment by apostasie** [comment]
@AkihiroSuda suggesting we close.
