### ISSUE TITLE
network create flag --ipv6 support

### ISSUE THREAD

**Issue by Tapasdgp** [containerd/nerdctl#1547]
### What is the problem you're trying to solve

I am trying to implement containerd network with ipv6 traffic which is not supported currently is there any plan to address this?

### Describe the solution you'd like

if you support similar kind of feature like docker deamon or support nerdctl network create --ipv6 flag support it will help us resolve ipv6 traffic flow issue within contrainer.

**Comment by yuchanns** [comment]
Let me handle it.
