### ISSUE TITLE
[Proposal] Track the relationship between the container and the cni network

### ISSUE THREAD

**Issue by Zheaoli** [containerd/nerdctl#1560]
### What is the problem you're trying to solve

In some circumstances, we need to track the relationship between the container and the CNI network like #1490 #1425

So I propose adding a new feature to maintain the relationship 

### Describe the solution you'd like

First, we need to add the command `nerdctl network containers` to let people get the container associate with network.

Second, we can use the static file to track the relationship, here's the detail

1. For now, we maintain the network configuration in `/etc/cni/net.d/` (`~/.config/cni/net.d` for rootless). So we can add a directory to let different cni network maintain their relationship. The format is `/etc/cni/net.d/${network_name}/containers`.
2. When the container has been created, we add a new record file to the directory, named `/etc/cni/net.d/${network_name}/containers/${${namespace}-${containerId}}`
3. When the container has been removed(like `run --rm`, `rm` etc), we remove the old file

**Comment by AkihiroSuda** [comment]
- What is "relationship"?
- What is the issue that will be solved by this proposal? How is the issue addressed in other container engines, such as Podman?
- How is this relevant to #1490?
- The `net.d` directory is dedicated for CNI, and I don't think we are allowed to create other files there.

**Comment by Zheaoli** [comment]
1. The relationship means how many containers use a network configuration.
2. Before we can change the network CIDR or CRUD network configuration, we need to check if there is any running container on the network configuration. If we don't do this, I think there will be an extra issues here.

**Comment by fahedouch** [comment]
the link between the container its network(s) is maintained by the label : `"nerdctl/networks": "[\"bridge\"]",`

**Comment by Zheaoli** [comment]
> the link between the container its network(s) is maintained by the label : `"nerdctl/networks": "[\"bridge\"]",`

seems enough to add validation on network CRUD action.

**Comment by fahedouch** [comment]
> > the link between the container its network(s) is maintained by the label : `"nerdctl/networks": "[\"bridge\"]",`
> 
> seems enough to add validation on network CRUD action.

@Zheaoli are you planning to add `validation` on network CRUD ?

**Comment by Zheaoli** [comment]
> > > the link between the container its network(s) is maintained by the label : `"nerdctl/networks": "[\"bridge\"]",`
> > 
> > 
> > seems enough to add validation on network CRUD action.
> 
> @Zheaoli are you planning to add `validation` on network CRUD ?

Yes, I have already make a PR, ptal #1569

**Comment by fahedouch** [comment]
> > the link between the container its network(s) is maintained by the label : `"nerdctl/networks": "[\"bridge\"]",`
> 
> seems enough to add validation on network CRUD action.

regarding your above comment I will this proposal. thks
