### ISSUE TITLE
containers can't intercommunicate using portmap

### ISSUE THREAD

**Issue by Eucliddd** [containerd/nerdctl#1561]
### Description

I have a prometheus container and a cadvisor container, and they are using following portmap:
prometheus: 7070 => 9090
cadvisor: 9090 => 8080
I get into prometheus using `nerdctl exec -it prometheus sh` and try to access cadvisor using `wget host ip:9090/metrics`, but the connection timeout.

Containers can communicate with others without portmap using host-ip:port.
Remote machine can access containers using portmap.
ONLY containers can't access other containers using portmap.

### Steps to reproduce the issue

```
1. nerdctl run -p 9090:8080 cadvisor
2. nerdctl run -p 7070:9090 prometheus
3. nerdctl exec -it prometheus sh
4. wget host-ip:9090/metrics
```

### Describe the results you received and expected

I get connection timeout inside the container, but it should get the same result as in my remote machine

Following is what i get inside the container:
<img width="649" alt="截屏2022-11-27 20 10 09" src="https://user-images.githubusercontent.com/49647564/204134703-89dbd2da-699b-40e8-b0fd-caca4d7661e8.png">

Following is what i get in my remote machine: 
<img width="612" alt="截屏2022-11-27 20 09 05" src="https://user-images.githubusercontent.com/49647564/204134643-e0fd6cc5-1c29-4911-b6fb-8c2819be2e11.png">

### What version of nerdctl are you using?

root@yongxisui:~/docker/prometheus# nerdctl version
WARN[0000] unable to determine buildctl version: exec: "buildctl": executable file not found in $PATH 
Client:
 Version:       v1.0.0
 OS/Arch:       linux/amd64
 Git commit:    c00780a1f5b905b09812722459c54936c9e070e6
 buildctl:
  Version:

Server:
 containerd:
  Version:      1.6.10
  GitCommit:    770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:      1.1.4
  GitCommit:    v1.1.4-0-g5fd4c4d

### Host information

root@yongxisui:~/docker/prometheus# nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: 1.6.10
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.0-19-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.669GiB
 Name: yongxisui
 ID: 48bd4f03-1111-4d87-a7f0-192411df39c5

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by Zheaoli** [comment]
Would you mind to tell us run the container in rootless or root mode?

**Comment by Eucliddd** [comment]
> Would you mind telling us whether you run the container in rootless or root mode?

in root mode

**Comment by Zheaoli** [comment]
Sorry, I can not reproduce this issue in root mode

**Comment by apostasie** [comment]
Cannot reproduce either - rootless or rootful.

@Eucliddd would you be able to confirm if this is still an issue with recent nerdctl?

Thanks a lot.

**Comment by apostasie** [comment]
@AkihiroSuda suggesting we close.
