### ISSUE TITLE
cannot delete network by ID

### ISSUE THREAD

**Issue by fahedouch** [containerd/nerdctl#1568]
### Description

please check the title :-D!

### Steps to reproduce the issue

1.  `nerdctl network create deleteme --gateway 10.10.11.1 --subnet 10.10.11.0/24`
2.   `nerdctl network ls`
```
root@6518fb9254d2:/home/containerd/nerdctl# _output/nerdctl network ls
NETWORK ID      NAME        FILE
17f29b073143    bridge      /etc/cni/net.d/nerdctl-bridge.conflist
f9d6cec6deab    deleteme    /etc/cni/net.d/nerdctl-deleteme.conflist
                host        
                none  
````
4. `nerdctl network rm f9d6cec6deab`
````
FATA[0000] no such network: f9d6cec6deab
````

### Describe the results you received and expected

expectation:
delete network by ID.

### What version of nerdctl are you using?

[v1.0.0](https://github.com/containerd/nerdctl/releases/tag/v1.0.0)

**Comment by Mihai22125** [comment]
Hello @fahedouch, I would be happy to give it a shoot. Can you assign it to me, please?
