### ISSUE TITLE
Flaky test: TestRunWithJsonFileLogDriverAndLogPathOpt

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1580]
```
=== RUN   TestRunWithJsonFileLogDriverAndLogPathOpt
    run_test.go:287: assertion failed: error is not nil: open /tmp/TestRunWithJsonFileLogDriverAndLogPathOpt348967069/001/nerdctl-testrunwithjsonfilelogdriverandlogpathopt/nerdctl-testrunwithjsonfilelogdriverandlogpathopt-json.log: no such file or directory
--- FAIL: TestRunWithJsonFileLogDriverAndLogPathOpt (3.38s)
```

**Comment by fahedouch** [comment]
@AkihiroSuda  this never occurs in my local :/ . Unit and integration tests [log-rotate](https://github.com/fahedouch/go-logrotate/blob/main/logrotate_test.go) seems to be stable. I am using GH CI to reproduce the error (which is random) so this will take more than expected time. Sorry for that.

**Comment by AkihiroSuda** [comment]
- https://github.com/containerd/nerdctl/pull/1650
