### ISSUE TITLE
Print usage output with `nerdctl cp` command

### ISSUE THREAD

**Issue by aman556** [containerd/nerdctl#1585]
### What is the problem you're trying to solve

Currently on running just `nerdctl COMMAND`(ex: nerdctl cp) command without arguments then the command is failing with standard `cobra.ExactArgs()` function error.
`FATA[0000] accepts 2 arg(s), received 0 `

Along with this usage message can be printed that include use `nerdctl COMMAND --help`.

### Describe the solution you'd like

We can create a function [here](https://github.com/containerd/nerdctl/tree/main/pkg/errutil)(can discuss the most accurate location for the function) and that will take care above problem.

**Comment by Zheaoli** [comment]
@aman556 Of cause!

**Comment by djdongjin** [comment]
This can be closed as #1606 is merged.
