### ISSUE TITLE
Deleting multiple networks stops at first delete fail

### ISSUE THREAD

**Issue by Mihai22125** [containerd/nerdctl#1587]
### Description

`nerdctl network rm NETWORK [NETWORK...]` stops executing at first network delete fail and prints the error message instead of trying to delete all networks from the list.

### Steps to reproduce the issue

1. `nerdctl network create deleteme --gateway 10.10.11.1 --subnet 10.10.11.0/24`
2. `nerdctl network ls`
```
root@6518fb9254d2:/home/containerd/nerdctl# _output/nerdctl network ls
NETWORK ID      NAME        FILE
17f29b073143    bridge      /etc/cni/net.d/nerdctl-bridge.conflist
f9d6cec6deab    deleteme    /etc/cni/net.d/nerdctl-deleteme.conflist
                host        
                none  
```
3. `nerdctl network rm test deleteme`
```
FATA[0000] no such network test 
```

### Describe the results you received and expected

Result received: 
- error message from deleting the first network from the list

Result expected:
- error message from deleting the first network from the list
- output of deleting the second network from the list

### What version of nerdctl are you using?

[v1.0.0](https://github.com/containerd/nerdctl/releases/tag/v1.0.0)

**Comment by fahedouch** [comment]
closed by https://github.com/containerd/nerdctl/pull/1618#event-8000632354
