### ISSUE TITLE
nerdctl load output is messed up for multi-image files

### ISSUE THREAD

**Issue by hholierhoek** [containerd/nerdctl#1596]
### Description

Commit https://github.com/containerd/nerdctl/commit/0bcedac04e22208eda6889ead48f682a62443189 messed up the output of the load command. The print statement 'Loaded image: xxx' needs a newline at the end; currently the next 'unpacking' log is written at the end of the previous 'Loaded image' log.

So the output is formatted as:
`unpacking docker.io/lib/my-app1:1.2.3 (sha256:xxxx)...
Loaded image: docker.io/lib/my-app1:1.2.3unpacking docker.io/lib/my-app2:2.3.4 (sha256:yyyy)...`

### Steps to reproduce the issue

1. create a tar bundle containing multiple images
2. run 'nerdctl load -i <tar file>'

### Describe the results you received and expected

Separate lines in the output, or revert to the old output.

### What version of nerdctl are you using?

1.0.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

RHEL8.6

**Comment by hholierhoek** [comment]
Note that, despite checking in preview before submitting, the sample output didn't formatted right. 'Loaded image:' is actually on the next line.

**Comment by airmelt** [comment]
Could you assign this bug to me? I am new here and working on this. Thanks!

**Comment by fahedouch** [comment]
closed by https://github.com/containerd/nerdctl/pull/1613
