### ISSUE TITLE
FATA[0040] unsupported restart policy "unless-stopped", supported policies are: []

### ISSUE THREAD

**Issue by shivabohemian** [containerd/nerdctl#1605]
### What is the problem you're trying to solve

FATA[0040] unsupported restart policy "unless-stopped", supported policies are: []

### Describe the solution you'd like

It should be same as docker.

**Comment by AkihiroSuda** [comment]
This is already supported, but you need containerd v1.7 (beta)
- https://github.com/containerd/containerd/pull/6744

**Comment by shivabohemian** [comment]
Good job! By the way, when will containerd v1.7 official be released?

**Comment by shivabohemian** [comment]
Got it~
