### ISSUE TITLE
imcompatible with docker cli regarding port mapping (docker run -p 7000-7005:7000-7005)

### ISSUE THREAD

**Issue by tuananh** [containerd/nerdctl#163]
this works in docker cli

```
docker run -p 7000-7005:7000-7005 myimage
```

however, with nerdctl, i got this error

```
FATA[0000] strconv.Atoi: parsing "7000-7005": invalid syntax
```

it seems that nerdctl does dedup str slice for port `portSlice := strutil.DedupeStrSlice(clicontext.StringSlice("p"))` but doesn't take into account this case.

**Comment by AkihiroSuda** [comment]
implemented in #173

**Comment by ushuz** [comment]
Is there a limit on the size of the range?

`-p 7000-7050:7000-7050` is OK,  while `-p 7000-7055:7000-7055` gives:

```
FATA[0000] create container failed validation: containers.Labels: label key and value greater than maximum size (4096 bytes), key: nerdctl/po: invalid argument
```

**Comment by fahedouch** [comment]
In containerd, there is a size limit for label and annotation size (4096 chars). (the range of ports is include in container labels)
