### ISSUE TITLE
'compose up' should start the containers in the dependency order

### ISSUE THREAD

**Issue by jessehu** [containerd/nerdctl#1658]
### Description

'compose up' does not start the containers in the dependency order. Same to 'compose restart'. While 'compose down' stop the containers in the reverse dependency order which is as expected.

### Steps to reproduce the issue

1. Download harbor
2. Run 'nerdctl compose up'
3. Run 'nerdctl compose down'

You will see 'compose down' stop the containers one by one in the reverse dependency order, but 'compose up' does not follow any dependency order.

```
$ nerdctl compose up -d
... ...
INFO[0000] Creating container nginx
INFO[0000] Creating container registry
INFO[0000] Creating container registryctl
INFO[0000] Creating container harbor-portal
INFO[0000] Creating container harbor-db
INFO[0000] Creating container redis
INFO[0000] Creating container harbor-core
INFO[0000] Creating container harbor-jobservice

$ nerdctl compose down
INFO[0000] Removing container nginx
INFO[0000] Removing container harbor-jobservice
INFO[0001] Removing container harbor-portal
INFO[0001] Removing container harbor-core
INFO[0002] Removing container redis
INFO[0003] Removing container registry
INFO[0003] Removing container harbor-db
INFO[0004] Removing container registryctl
INFO[0004] Removing network harbor_harbor
INFO[0004] Removing network harbor_default
```

Related code is https://github.com/containerd/nerdctl/blob/v1.1.0/pkg/composer/up_service.go#L48-L72. It starts all containers in go routines in parallel.

### Describe the results you received and expected

I'd expect the containers are started or restarted in the dependency order defined in docker-compose.yaml.

Refer to https://docs.docker.com/compose/startup-order/
`You can control the order of service startup and shutdown with the [depends_on](https://docs.docker.com/compose/compose-file/compose-file-v3/#depends_on) option. Compose always starts and stops containers in dependency order, where dependencies are determined by depends_on, links, volumes_from, and network_mode: "service:..."`

### What version of nerdctl are you using?

1.1.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by djdongjin** [comment]
I'll take a look and fix this.

**Comment by jessehu** [comment]
Thank you 👍
