### ISSUE TITLE
unrecognized image format ( failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to add snapshot x0je4kq7o7yz8r0hc66djbuxn to lease: unknown method AddResource for service containerd.services.leases.v1.Leases: not implemented)

### ISSUE THREAD

**Issue by zjcnew** [containerd/nerdctl#171]
> [root@localhost ks-apiserver]# nerdctl build -t test .
[+] Building 0.0s (1/2)                                                                                                                                   
 => ERROR [internal] load build definition from Dockerfile                                                                                           0.0s
 > [internal] load build definition from Dockerfile:
error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to add snapshot x0je4kq7o7yz8r0hc66djbuxn to lease: unknown method AddResource for service containerd.services.leases.v1.Leases: not implemented
FATA[0000] unrecognized image format                    
[root@localhost ks-apiserver]# 

[root@localhost ks-apiserver]# cat Dockerfile 
FROM alpine:3.11

ARG HELM_VERSION=v3.5.2

RUN apk add --no-cache ca-certificates
RUN wget https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz && \
    tar xvf helm-${HELM_VERSION}-linux-amd64.tar.gz && \
    rm helm-${HELM_VERSION}-linux-amd64.tar.gz && \
    mv linux-amd64/helm /usr/bin/ && \
    rm -rf linux-amd64
COPY  ks-apiserver /usr/local/bin/

EXPOSE 9090
CMD ["sh"]

**Comment by AkihiroSuda** [comment]
- Please format the issue markdown

- How do you run buildkitd? With OCI worker? With containerd worker?

- Version of nerdctl, containerd, and buildkitd

**Comment by zjcnew** [comment]
with containerd worker
nerdctl-full-0.7.3-linux-amd64.tar.gz
buildkit-v0.8.2.linux-amd64.tar.gz
containerd.io-1.2.13-3.1.el7.x86_64

**Comment by AkihiroSuda** [comment]
Please use containerd 1.4 or later.

AddResource needs containerd 1.3 at least.

https://github.com/containerd/containerd/commit/8a388d6238b6aa1d52f53b77892c7e991cdd0328

**Comment by zjcnew** [comment]
This is indeed the reason, it is now working

**Comment by aMohammadEmami** [comment]
@AkihiroSuda I have a containerd 1.6 but keep getting this error:
error adding content digest to lease: sha256:ab022bccabd6519110473fecf7c24f52aa395f845d2c8da3b77be6aef92509ff: unknown method AddResource: not implemented

would you be so kind telling me how to fix it?

the command is this:
docker pull fluent/fluentd:edge-debian

some info:
**docker version**

Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:42 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.4
  GitCommit:        e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
 runc:
  Version:          1.2.4
  GitCommit:        6635b4f0c6af3810594d2770f662f34ddc15b40d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


**docker info**

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.21.0)

Server:
 Containers: 33
  Running: 0
  Paused: 0
  Stopped: 33
 Images: 37
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
 runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-16-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.67GiB
 Name: debian
 ID: 7JAX:LK5G:XPDX:INTR:UEAW:64PM:QPER:R5DW:HW3F:GPCN:FUYC:ZT4P
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://dockerhub.ir/
 Live Restore Enabled: false

WARNING: No swap limit support

**Comment by AkihiroSuda** [comment]
> I have a containerd 1.6
> ...
> containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e

This is 1.2.4 https://github.com/containerd/containerd/commit/e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
