### ISSUE TITLE
changing buildkit output from Docker tarball to containerd store 

### ISSUE THREAD

**Issue by fahedouch** [containerd/nerdctl#176]
Hello,

in order to accelerate nerdctl build I am thinking about making `containerd image store` as a buildkit output rather then exporting to a docker tarball and loading it.

        buildctlCmd := exec.Command(buildctlBinary, buildctlArgs...)
	buildctlCmd.Env = os.Environ()

	buildctlStdout, err := buildctlCmd.StdoutPipe()
	if err != nil {
		return err
	}
	buildctlCmd.Stderr = clicontext.App.ErrWriter

	if err := buildctlCmd.Start(); err != nil {
		return err
	}

	if err = loadImage(buildctlStdout, clicontext); err != nil {
		return err
	}

To do that we need to use containerd worker and change buildkit namespace from `buildkit`  to `default`.

can we have a regression with that ?

**Comment by AkihiroSuda** [comment]
The default behavior shouldn't change until we can get https://github.com/moby/buildkit/pull/2074 merged.

Also, rootless buildkit doesn't support containerd worker yet. (Shouldn't be hard)

**Comment by AkihiroSuda** [comment]
And we will want a library to copy images across containerd namespaces efficiently, without ending up copying the whole blobs.

**Comment by AkihiroSuda** [comment]
This was implemented in nerdctl 0.18.
Needs BuildKit (>= 0.10) to be running in the containerd worker mode.
https://github.com/containerd/nerdctl/blob/master/docs/build.md
