### ISSUE TITLE
Refactor the compose ps command flagging process

### ISSUE THREAD

**Issue by HanquanHq** [containerd/nerdctl#1770]
### What is the problem you're trying to solve

According to #1680, I want to refactor the compose ps command flagging process. Since #1702 is marked invalid, I open this issue for tracking purposes.

### Describe the solution you'd like

 1. Create a file in `pkg/api/types/${cmd}_types.go`, and define the CommandOption for this command
 2. Create some file in `pkg/api/cmd/${cmd}`, and move the command entry point in real into this package
 3. Create new docs in `docs/reference/api/${cmd}_types.md`, and describe the field in CommandOption

**Comment by yuchanns** [comment]
Please go ahead.

**Comment by AkihiroSuda** [comment]
Let me close one and track all commands in #1680
