### ISSUE TITLE
nerdctl build helptext is incorrect

### ISSUE THREAD

**Issue by Liqs-v2** [containerd/nerdctl#1778]
# Problem
I am still new to using nerdctl and often rely on the documentation and helptext that comes with the commandline tools.
## Expectation
When I follow the usage pattern suggested by the helptext of a commandline tool, the program is supplied with all **required** parameters and will run.
## Current state
When checking the helptext for build `nerdctl build --help` I get the following output:
![grafik](https://user-images.githubusercontent.com/9247500/209812891-0dcbde0c-266e-48fb-8bff-d789b8a6185d.png)

Clearly the **usage pattern suggests** that `nerdctl build -f local.Dockerfile` should run without issue, but it results in:
`FATA[0000] context needs to be specified`

Running: `nerdctl build . --file local.Dockerfile` runs as expected.

## Fix
I would suggest updating the usage pattern to:
`nerdctl build <path_to_folder> [flags]`

to accurately reflect the parameters actually required for the program.

## Metainformation

- Nerdctl Version: 1.0.0
- Windows 10
- Powershell Version: 5.1.19041.2364

**Comment by maddy020** [comment]
Hey @AkihiroSuda  
I would like to work over this issue

**Comment by vvejell1** [comment]
Hi @AkihiroSuda , @djdongjin
I have been looking into this for a while now, and I'll modify the Build usage pattern.

**Comment by AkihiroSuda** [comment]
This has been fixed in v1.1.0:
- https://github.com/containerd/nerdctl/pull/1523
