### ISSUE TITLE
CI: test-integration often hits the 30min limit

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1811]
https://github.com/containerd/nerdctl/blob/bbe5c052660000e4ef65c715c6b9e6bba25a9fdb/.github/workflows/test.yml#L61-L63

We could just increase the timeout, but optimizing the tests to shorten the time might be more preferable

**Comment by yuchanns** [comment]
I've found that some tests can be run in parallel with `t.Parallel()`, this might be helpful.

**Comment by amarlearning** [comment]
I'd like to take on this issue. I'll start working on it and keep you updated on my progress.

**Comment by djdongjin** [comment]
@amarlearning thanks, please go ahead :)

**Comment by fahedouch** [comment]
> I've found that some tests can be run in parallel with `t.Parallel()`, this might be helpful.

Please be careful when setting `t.Parallel()` this may introduce indirect deps between tests which can lead to test failing.

**Comment by djdongjin** [comment]
Some sample time consuming tests observed from [CI](https://github.com/containerd/nerdctl/actions/runs/3904774683/jobs/6670984959):

```
PASS cmd/nerdctl.TestIPFSComposeUp/overlayfs (65.52s)
PASS cmd/nerdctl.TestIPFSComposeUp/stargz (227.56s)
PASS cmd/nerdctl.TestIPFSComposeUp/ipfs-address (33.36s)
PASS cmd/nerdctl.TestIPFSComposeUp (331.73s)
PASS cmd/nerdctl.TestIPFSComposeUpBuild (22.58s)
PASS cmd/nerdctl.TestLoginWithPlainHttp (28.60s)
PASS cmd/nerdctl.TestSyslogFacilities (26.98s)
PASS cmd/nerdctl.TestRunPort (28.14s)
PASS cmd/nerdctl.TestRunRestartWithOnFailure (20.43s)
PASS cmd/nerdctl.TestRunRestartWithUnlessStopped (20.78s)
PASS cmd/nerdctl.TestUpdateRestartPolicy (20.71s)
```

**Comment by amarlearning** [comment]
@djdongjin Even I saw the CI to find out which test was taking a long time and based on that I tried parallelizing `TestIPFSComposeUp` on my PR.

Thanks for sharing other tests which were taking longer time 👍🏻

**Comment by amarlearning** [comment]
As of now, our test-integration job takes ~8-10 mins just to prepare the environment. I am also finding out if there is a way to cache common docker images across all OS and Containerd versions.

Let me know if anyone has any input.

**Comment by djdongjin** [comment]
The actual timeout for `go test` is 20 minutes. And it seems this one is usually first reached before the `workflow` timeout (30 mins), especially for rootless (e.g. https://github.com/containerd/nerdctl/actions/runs/3942266822/jobs/6745714728)

Maybe we can increase `go test` to 30 mins and `workflow` to 40 mins, while we're making optimizations.

Rootful:

https://github.com/containerd/nerdctl/blob/66be3c85133945c9f2a596d1e6c70c39680fa283/Dockerfile#L300

Rootless:

https://github.com/containerd/nerdctl/blob/66be3c85133945c9f2a596d1e6c70c39680fa283/Dockerfile#L326

**Comment by amarlearning** [comment]
Do we need [this](https://github.com/containerd/nerdctl/pull/1835) PR anymore?

**Comment by djdongjin** [comment]
Hi @amarlearning I think we still need to figure out how to speed up these tests. Increasing timeout is just a workaround to unblock other PRs before we figure it out (that's why the issue still open :)).

Parallelizing `IPFSComposeUp` will probably still cause port conflict sometimes since different tests share the same port mapping here:

https://github.com/containerd/nerdctl/blob/1ee4e570e118d1862830cdbcdaf676f72ca3bf09/cmd/nerdctl/ipfs_compose_linux_test.go#L82

**Comment by amarlearning** [comment]
@djdongjin yes, I understand. 

I believe `t.Parallel()` will not be of much help, I am looking for a different solution. I will profile the tests and find out what all tests are taking longer time and why so using. And will optimize them.
