### ISSUE TITLE
docker daemon ipv6 support

### ISSUE THREAD

**Issue by fahedouch** [containerd/nerdctl#182]
hello, 

GA seems to supports ipv6 in docker daemon. before merging this PR https://github.com/containerd/nerdctl/pull/127

we should fix `TestContainerInspectContainsPortConfig` test by adding a condition on the binary or skipping it

**Comment by AkihiroSuda** [comment]
Unrelated to this repo?

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/nerdctl/pull/185
