### ISSUE TITLE
Support `profiles` in nerdctl compose

### ISSUE THREAD

**Issue by djdongjin** [containerd/nerdctl#1831]
### What is the problem you're trying to solve

compose spec uses `profiles` to group services within a `docker-compose.yml` (each service can belong to multiple profiles, e.g., test, debug, etc). 

This allows users to put all services (debug, test, prod) in one `docker-compose.yml` and share other configs (volumns, networks, etc. `profiles` only applies to services). Users can enable specific groups/profiles when running compose command. all profiles are enabled by default if no `profile` is given via flag/env (basically, the current behavior).

```shell
# syntax may not correct, just for demo
#
# no profile is given, all profiles are enabled (so all services up)
$ nerdctl compose up -d

# only services with a `test` or `debug` profile attached are up
$ nerdctl --profile test,debug compose up -d
$ COMPOSE_PROFILES=test,debug nerdctl compose up -d
```

Notice that:

1. If a service name(s) is passed as arguments, all profiles they belong to are enabled automatically.
2. `profiles` are just a limitation on which services are visible/in-scope, and shouldn't handle dependencies etc.

```shell
# suppose svc0 belongs to p0 and depends on svc1, whereas svc1 belongs to p1 not p0
# this should fail because svc1 should up as a dependency of svc0, but p1 is not enabled.
$ nerdctl compose up -d svc0
# this should succeed because p1 is enabled, so as p0 (enabled automatically by svc0 being a arg)
$ nerdctl --profile p1 compose up -d svc0
```

### Describe the solution you'd like

1. Support the `profiles` field in `docker-compose.yml`, which specifies which service belongs to which profiles.
2. Support the `profile` compose flag and `COMPOSE_PROFILES` env variable, which explicitly specifies which profiles are enabled.

### Additional context

[docker compose profile example](https://docs.docker.com/compose/profiles/)

[`profiles` in compose spec](https://github.com/compose-spec/compose-spec/blob/master/spec.md#profiles)

**Comment by tranngoclam** [comment]
+1

**Comment by katlol** [comment]
https://github.com/adsblol/feed/blob/main/bin/adsblol-init A really bad workaround for this feature. Please consider adding this! ❤️

**Comment by danishprakash** [comment]
@djdongjin mind If I take a look at this?

**Comment by djdongjin** [comment]
@danishprakash please go ahead
