### ISSUE TITLE
Support logs in namespace `k8s.io`

### ISSUE THREAD

**Issue by zhaojizhuang** [containerd/nerdctl#1844]
### What is the problem you're trying to solve

Currently `nerdctl logs` do not support containers in namespace `moby` and `k8s.io` 

We can support`nerdctl logs` in namespace `k8s.io`( or container created via CRIPlugin)

### Describe the solution you'd like

Refer to this commit https://github.com/zhaojizhuang/nerdctl/commit/c8c2a66e74725e01029c9b30fe64ec950f2a1637

1. get LogPath from `containerMetadataExtension`(which only use in container created by CRI)
2. add text logdriver
3. tail `LogPath`,and redirect `stdout`、`stderr` in logfile to `os.stdout` `os.stderr`

**Comment by AkihiroSuda** [comment]
Thanks, left comments in https://github.com/zhaojizhuang/nerdctl/commit/c8c2a66e74725e01029c9b30fe64ec950f2a1637

**Comment by zhaojizhuang** [comment]
@AkihiroSuda OK，Thanks, I will create a PR for it
