### ISSUE TITLE
Should we move the `Command Reference` to a separate doc

### ISSUE THREAD

**Issue by djdongjin** [containerd/nerdctl#1865]
### What is the problem you're trying to solve

Currently the `Command reference` is part of the `README.md`. Although it makes the `command reference` more visible, I feel it has several drawbacks:

1. It makes the `README` very long, and makes other sections less visible. For example, 
    1. Sometimes new contributors have to read README carefully to notice [how to test nerdctl](https://github.com/containerd/nerdctl#test-suite).
    2. It makes other documents less visible: [other document](https://github.com/containerd/nerdctl#additional-documents) is after the long command reference in README. Without a heading TOC, it's hard to notice there is an other document section at the end.
    3. It makes [unimplemented commands](https://github.com/containerd/nerdctl#unimplemented-docker-commands) less visible: e.g., https://github.com/containerd/nerdctl/issues/1854
2. We don't have a single page/link that can direct users to nerdctl command document.
    1. Although we have a [README header link](https://github.com/containerd/nerdctl#command-reference), the same page has many sections that are not relevant to end-users (i.e. not nerdctl developers/contributors).

### Describe the solution you'd like

We shoud have a `command-reference.md` in `nerdctl/docs` (similar to [faq](https://github.com/containerd/nerdctl/blob/main/docs/faq.md)) that are only for command reference/doc. We should hightlight the reference doc in the beginning of README, and probably put the link in the `About` section of the repo.

### Additional context

cc @containerd/nerdctl-maintainers

**Comment by AkihiroSuda** [comment]
SGTM

**Comment by AkihiroSuda** [comment]
If there is a possibility that we may want to split the command reference into multiple files, maybe it should be placed in a directory like `docs/command-reference/README.md`

**Comment by djdongjin** [comment]
> If there is a possibility that we may want to split the command reference into multiple files, maybe it should be placed in a directory like docs/command-reference/README.md

Currently I feel a single md should serve us/users well given that we use the markdown preview for visualization/navigation, and the single file can be used as the link to our command reference.

We can split and place in a directory if later we decide to build a website for command reference, maybe something similar to docker reference

https://docs.docker.com/engine/reference/commandline/docker/
https://github.com/docker/cli/tree/master/docs/reference/commandline

**Comment by suyanhanx** [comment]
If decide to build a website, it can be a part of containerd docs IMO.
