### ISSUE TITLE
Add unittest for MergeEnvFileAndOSEnv

### ISSUE THREAD

**Issue by suyanhanx** [containerd/nerdctl#1884]
### What is the problem you're trying to solve

There is currently a GenerateEnvs function in `cmd/nerdctl/run.go`, which is used in commands, `run` and `exec`. This function may also be used elsewhere in the future. We can probably extract it to flagutil.

https://github.com/containerd/nerdctl/blob/main/cmd/nerdctl/run.go#L1314-L1334

### Describe the solution you'd like

Extract this function and its dependencies into flagutil and add some tests for it.

**Comment by Zheaoli** [comment]
SGTM, I think this function is used in `run` and `exec` commands. Maybe you can split it into `envutil` package

**Comment by suyanhanx** [comment]
> SGTM, I think this function is used in `run` and `exec` commands. Maybe you can split it into `envutil` package

How about putting it here?  
/cc @djdongjin 

https://github.com/containerd/nerdctl/blob/c2c648c5ef7bad5ebbcb05dcdef9247f31892efe/pkg/flagutil/flagutil.go

**Comment by Zheaoli** [comment]
@suyanhanx Would you mind to PR this issue first?

**Comment by suyanhanx** [comment]
@Zheaoli It's OK. I'm handling it.

**Comment by djdongjin** [comment]
@suyanhanx can you modify the issue to `Add unittest for MergeEnvFileAndOSEnv`? Since it's already extracted to flagutil & renamed, only unittest is left.

https://github.com/containerd/nerdctl/blob/d39e9c8137837398395e8af62db0d879ee69b13b/pkg/flagutil/flagutil.go#L127

**Comment by suyanhanx** [comment]
> @suyanhanx can you modify the issue to `Add unittest for MergeEnvFileAndOSEnv`? Since it's already extracted to flagutil & renamed, only unittest is left.
> 
> https://github.com/containerd/nerdctl/blob/d39e9c8137837398395e8af62db0d879ee69b13b/pkg/flagutil/flagutil.go#L127

Sure. Done.
