### ISSUE TITLE
[Proposal] Release v1.2.0 

### ISSUE THREAD

**Issue by Zheaoli** [containerd/nerdctl#1903]
### What is the problem you're trying to solve

There is more than a month since v1.1.0 was released. During this month, we make 100 PR for v1.2.0; see also https://github.com/containerd/nerdctl/milestone/25

For now, the refactoring process has been completed by almost 80%; the rest of the commands are a little bit complicated. So I think it's better to release it in v1.3.0

### Describe the solution you'd like

So, I propose to lock on the time window for the new PR and prepare for releasing v1.2.0:

1.  The time window would be closed at 2023-01-25 00:00 UTC+0, **any new PR or WIP PR or draft PR** except security PR and dependency update PR after this time point should not be released in v1.2.0
2. The v1.2.0 will be released after all PR in the v1.2.0 milestone has been merged.

**Comment by Zheaoli** [comment]
cc @containerd/nerdctl-maintainers @containerd/nerdctl-committers

**Comment by AkihiroSuda** [comment]
> The time window would be closed at 2023-01-25 00:00 UTC+0, any PR except security PR and dependency update PR after this time point should not be released in v1.2.0

SGTM, after the time window I'll open a PR to update deps and then release v1.2.0.

**Comment by AkihiroSuda** [comment]
We have to wait for this to be cherry-picked into BuildKit (and nerdctl)
- https://github.com/containerd/containerd/issues/7972

**Comment by Zheaoli** [comment]
> We have to wait for this to be cherry-picked into BuildKit (and nerdctl)
> 
> * ["failed to copy: io: read/write on closed pipe" on `ctr images push` while pushing large images containerd#7972](https://github.com/containerd/containerd/issues/7972)

SGTM

**Comment by Zheaoli** [comment]
> We have to wait for this to be cherry-picked into BuildKit (and nerdctl)
> 
> * ["failed to copy: io: read/write on closed pipe" on `ctr images push` while pushing large images containerd#7972](https://github.com/containerd/containerd/issues/7972)

It seems this PR has been cherry-picked into buildkit now. Maybe we can prepare to release v1.2.0?

**Comment by AkihiroSuda** [comment]
Wait for
- https://github.com/containerd/containerd/pull/8016

**Comment by AkihiroSuda** [comment]
This regression is terrible, so I'd like to get this fixed before v1.2.0
- https://github.com/containerd/nerdctl/issues/1942
