### ISSUE TITLE
Make `image prune` remove dangling images by default

### ISSUE THREAD

**Issue by djdongjin** [containerd/nerdctl#1922]
Currently `nerdctl image prune` requires `--all` to be specified. Since dangling image is supported, we should remove this restriction and remove dangling images by default and remove all unused if `--all` is specified.

`nerdctl image prune`: https://github.com/containerd/nerdctl/blob/main/docs/command-reference.md#whale-nerdctl-image-prune

dangling support: https://github.com/containerd/nerdctl/pull/1919

`docker image prune`: https://docs.docker.com/engine/reference/commandline/image_prune/

**Comment by suyanhanx** [comment]
I'd like to take this.

**Comment by suyanhanx** [comment]
Will do this with #1680 @djdongjin
