### ISSUE TITLE
Support Notation image signing

### ISSUE THREAD

**Issue by ningziwen** [containerd/nerdctl#1974]
### What is the problem you're trying to solve

Notation is a tool for signing and verifying signatures based on Notary V2 standard. Nerdctl already supports cosign for signing feature. I’d like to see nerdctl also supporting notation so users have one more option to use for signing and signature verification.

Keyless is specific to cosign today so we will skip discussing keyless by default in the following discussion.

### Describe the solution you'd like

The current [cosign](https://github.com/containerd/nerdctl/blob/main/docs/cosign.md) signing and verification interfaces of nerdctl are like these:

```
nerdctl push --sign=cosign --cosign-key cosign.key devopps/hello-world
nerdctl pull --verify=cosign --cosign-key cosign.pub devopps/hello-world-bad
```

Making it generic, the interfaces will be:

```
nerdctl push --sign=<signing-tool-enum> TOOL_SPECIFIC_ARGS IMAGE
nerdctl pull --verify=<verifying-tool-enum> TOOL_SPECIFIC_ARGS IMAGE
```

The interfaces of [cosign](https://github.com/sigstore/cosign#sign-a-container-and-store-the-signature-in-the-registry) are

```
cosign sign --key cosign.key $IMAGE_URI_DIGEST
cosign verify --key cosign.pub $IMAGE_URI
```

So it is intuitive to add `--cosign-key` as `TOOL_SPECIFIC_ARGS` in existing cosign support.

However, the interface of [notation](https://notaryproject.dev/docs/quickstart/) is much different.

In notation, the private key must be added by notation key command first to be used by notation sign, and the private key can only be added with plugins. Based on notation’s [response](https://github.com/notaryproject/notation/discussions/533#discussioncomment-4862369), the only supported plugin today is Azure Key Vault. The notation key command actually manages [signing-keys.json](https://notaryproject.dev/docs/how-to/notation-config-file/#sample-of-signingkeysjson) file in notation store. The users can also put local keys in signing-keys.json manually. The local keys are just not supported in command yet. ([Issue](https://github.com/notaryproject/notation/issues/539))

```
notation key add --plugin <plugin_name> [flags] <key_name>
notation sign --key <key_name> <reference>
```

To validate the signature, instead of using public key, users need to add the cert to the trust policy. notation verify will directly use the cert in trust policy to verity the image.

```
cat <<EOF > $HOME/.config/notation/trustpolicy.json
{
    "version": "1.0",
    "trustPolicies": [
        {
            "name": "wabbit-networks-images",
            "registryScopes": [ "$REGISTRY/$REPO" ],
            "signatureVerification": {
                "level" : "strict" 
            },
            "trustStores": [ "$STORE_TYPE:$STORE_NAME" ],
            "trustedIdentities": [
                "x509.subject: $CERT_SUBJECT"
            ]
        }
    ]
}
EOF

notation verify $IMAGE
```

### Signing

For signing, there are multiple options.

**Recommended solution**
Users will do any operations before notation sign by themselves. nerdctl push only integrates notation sign.
The experience will be

```
notation key add --plugin <plugin_name> [flags] <key_name> # or change the signing-keys.json
nerdctl push --sign=notation --notation-key <key_name> devopps/hello-world
```

The concern is that adding any non-nerdctl steps to be part of workflow is not ideal. However, considering the operation is actually managing signing-keys.json, it is consistent with managing trust policy in verification. Notation users will also expect the additional steps required.

**Alternative thoughts**

1. Users will do any operations before notation key by themselves. nerdctl push integrates notation key and notation sign.

The experience will be

```
nerdctl push --sign=notation --notation-plugin <plugin_name> PLUGIN_ARGS devopps/hello-world
```

The concern is there will be some logic to clean up the keys, which will cause race conditions for concurrent pushes.

1. Similar to recommended option, but add a nerdctl command to manage key.

```
nerdctl <notation-key> add --plugin <plugin_name> [flags] <key_name>
nerdctl push --sign=notation --notation-key <key_name> devopps/hello-world
```

It will an additional command outside regular container development command set. And it will be only useful for one signing option of signing feature (cosign doesn’t need it).

1. Integrate plugin calls to nerdctl command. There may be multiple plugins in the future, so it is good to keep plugin calls flexible and managed by users.

### Signature verification

For signature verification, the only option is, users will do any operations before notation verify by themselves. nerdctl pull only integrates notation verify. It is not possible to change the trust policy for them because we need to support users running multiple nerdctl pull in parallel. Changing the trust policy for them will cause race conditions if they are pulling images with different public keys/certs. 

```
# Configure trust policy first

nerdctl pull --verify=notation devopps/hello-world-bad
```

**Comment by suyanhanx** [comment]
Can we close this? @ningziwen @djdongjin

**Comment by arnaldo2792** [comment]
@ningziwen, this can be closed, right?
