### ISSUE TITLE
Resolve special IP host-gateway

### ISSUE THREAD

**Issue by ningziwen** [containerd/nerdctl#1979]
### What is the problem you're trying to solve

Resolve host-gateway when adding it as ip in --add-host.

Today nerdctl can't resolve it.
```
nerdctl run --add-host name:host-gateway -it public.ecr.aws/amazonlinux/amazonlinux:2 bash
# cat/etc/hosts
...
host-gateway    name
...
```

In Docker, host-gateway can be resolved to the host gateway ip in docker config or a default bridge ip.

```
docker run --add-host name:host-gateway -it public.ecr.aws/amazonlinux/amazonlinux:2 bash
# cat /etc/hosts
...
192.168.65.2	name
...
``` 

### Describe the solution you'd like

Created a draft [PR](https://github.com/containerd/nerdctl/pull/1978) for discussion. I will complete the change when we finalize the decisions.

The recommended solution is adding a host gateway in nerdctl config and resolve host-gateway to it. 

In docker, the default bridge ip is returned when the host gateway ip is not configured by users. The bridge CNI plugin that nerdctl uses seems different. The IP is [returned](https://github.com/containerd/nerdctl/blob/main/pkg/ocihook/ocihook.go#L416) on OCI hook "createRuntime". So I think it is not deterministic in nerdctl layer. I recommend failing it when the host gateway ip is not configued in nerdctl config.

______________

Based on Akihiro's suggestion, the host IP will be returned as default.

### Additional context

In Docker,
```
docker run --add-host name:host-gateway -it public.ecr.aws/amazonlinux/amazonlinux:2 bash
# cat /etc/hosts
...
192.168.65.2	name
...
```
https://github.com/runfinch/finch/issues/209

**Comment by fahedouch** [comment]
> The IP is [returned](https://github.com/containerd/nerdctl/blob/main/pkg/ocihook/ocihook.go#L416) on OCI hook "createRuntime". So I think it is not deterministic in nerdctl layer

Why ?

**Comment by ningziwen** [comment]
@fahedouch 
From my understanding, in `nerdctl run`, these will happen:
resolve the default IP -> put default IP in global flag "host-gateway-ip" -> set up ocihook -> ...

Asynchronously, when the container is created on runtime (when "[createRuntime](https://github.com/containerd/nerdctl/blob/main/pkg/ocihook/ocihook.go#L88)" event is received), [cni.setup()](https://github.com/containerd/nerdctl/blob/main/pkg/ocihook/ocihook.go#L402) returns the deterministic IP. But it is in an asynchronous process triggered by the main thread.

**Comment by fahedouch** [comment]
> @fahedouch From my understanding, in `nerdctl run`, these will happen: resolve the default IP -> put default IP in global flag "host-gateway-ip" -> set up ocihook -> ...
> 
> Asynchronously, when the container is created on runtime (when "[createRuntime](https://github.com/containerd/nerdctl/blob/main/pkg/ocihook/ocihook.go#L88)" event is received), [cni.setup()](https://github.com/containerd/nerdctl/blob/main/pkg/ocihook/ocihook.go#L402) returns the deterministic IP. But it is in an asynchronous process triggered by the main thread.

ok for [rootless containers ](https://github.com/containerd/nerdctl/pull/1978#discussion_r1102345149) 👍 .

But sorry @ningziwen still can't understand why the  nerdctl flow to fill the container `etc/hosts` do not fit the use of  container bridge IP as `host-gateway` ip . could you please share a case when this may attribute a bad adresse or fail please.

**Comment by ningziwen** [comment]
It is not about to fail. The case is that the IP is assigned by CNI bridge when creating container in low level runtime (OCI hook "createRuntime), [cni.setup()](https://github.com/containerd/go-cni/blob/6603d5bd8941d7f2026bb5627f6aa4ff434f859a/cni.go#L155) returns the assigned IP in Result.raw. But cni.setup() is called on OCI hook "createRuntime". But in nerdctl the default gateway ip needs to be assigned at the beginning of `nerdctl run` which is "[initRootCmdFlags()](https://github.com/containerd/nerdctl/blob/17b61660106cd243ae5e26f4dc50253293cbe9af/cmd/nerdctl/main.go#L136)", when the IP is not assigned yet. Docker libnetwork has a static bridge ip but CNI bridge does not.

**Comment by ningziwen** [comment]
Closing the issue as the PR is merged. https://github.com/containerd/nerdctl/pull/1978
