### ISSUE TITLE
[Question] how to exit the containerd-shim-runc-v2 processes?

### ISSUE THREAD

**Issue by c-goes** [containerd/nerdctl#198]
After a few exited containers there are a lot of these processes. Is there a nerdctl command to terminate them?

nerdctl run -it alpine sh
exit

**Comment by AkihiroSuda** [comment]
Seems a bug, could you post the full repro steps and version (nerdctl info, nerdctl version)

**Comment by c-goes** [comment]
```
 # nerdctl version
Client:
 Version:       v0.9.0
 Git commit:    39a46444754c581e020fffa63261f2a859c16bac

Server:
 containerd:
  Version:      v1.5.2
  Revision:     36cc874494a56a253cd181a1a685b44b58a2e34a
```


```
# nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.5.2
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: json-file
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.128-microsoft-standard
 Operating System: openSUSE Leap 15.3
 OSType: linux
 Architecture: x86_64
 Name: USER
 ID: fcac3782-68a8-4fa6-b7ed-c20738dc77d1
```


Repro:

1. Install full amd64 from https://github.com/containerd/nerdctl/releases
2. Start containerd
3. run `nerdctl run -ti alpine sh`
4. run `exit`
5. process `containerd-shim-runc-v2` is still running

**Comment by AkihiroSuda** [comment]
This is now being discussed in https://github.com/containerd/nerdctl/pull/229
