### ISSUE TITLE
Why can't I reuse the mirror function of containerd

### ISSUE THREAD

**Issue by jiaweicheng77** [containerd/nerdctl#199]

**Comment by jiaweicheng77** [comment]
我在/etc/containerd/config.toml文件中，配置了镜像仓库
![image](https://user-images.githubusercontent.com/29253186/116585582-20a11100-a94b-11eb-894c-37ad900ce016.png)
使用crictl pull 可以生效；使用nerdctl pull却无法生效

**Comment by fahedouch** [comment]
Seems related to containerd, could you reproduce steps and post version of containerd and nerdctl plz.

**Comment by jiaweicheng77** [comment]
[root@localhost ~]# containerd --version
containerd containerd.io 1.4.4 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
[root@localhost ~]#
[root@localhost ~]#
[root@localhost ~]# nerdctl version
Client:
 Version:       v0.8.0
 Git commit:    d57846db4a90540bc41e4683cd1a9f1e9e99170a

Server:
 containerd:
  Version:      1.4.4
  Revision:     05f951a3781f4f2c1911b05e61c160e9c30eaa8e

**Comment by AkihiroSuda** [comment]
nerdctl现在不支持镜像配置。
因为nerdctl不用CRI API，nerdctl不读CRI的配置文件。
