### ISSUE TITLE
nerdctl --user flag with volume mount does not behave the same as docker

### ISSUE THREAD

**Issue by austinarbor** [containerd/nerdctl#2026]
### Description

When adding a bind mount using docker cli, when the `--user` flag is passed in, the user is assigned as owner of the mount. In nerdctl, the owner of the mount is still the root

### Steps to reproduce the issue

1. `docker run -it -v /tmp:/remote/dir --user 61000 busybox:latest ash`
2. `sudo nerdctl run -it -v /tmp:/remote/dir --user 61000 busybox:latest ash`

### Describe the results you received and expected

Using nerdctl, I would expect the owner of the mounted volume inside the container to be the specified user
```shell
 ❯ docker run -it -v /tmp:/remote/dir --user 61000 busybox:latest ash
~ $
~ $ cd /remote
/remote $ ls -lrt
total 0
drwxrwxrwt   12 61000    root           384 Feb 17 15:56 dir
```

```shell
$ sudo nerdctl run -it -v /tmp:/remote/dir --user 61000 busybox:latest ash
~ $ 
~ $ cd /remote
/remote $ ls -lrt
total 24
drwxrwxrwt   30 root     root         20480 Feb 17 16:01 dir

```

### What version of nerdctl are you using?

1.2.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

parallels@ubuntu-linux-20-04-desktop:~/Downloads/nerd$ sudo ./bin/nerdctl info
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: 1.5.9-0ubuntu3.1
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.15.0-60-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 3.82GiB
 Name: ubuntu-linux-20-04-desktop
 ID: e1bc2c73-e713-4ca9-9a5f-eda7429bf51e

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by AkihiroSuda** [comment]
> When adding a bind mount using docker cli, when the --user flag is passed in, the user is assigned as owner of the mount.

I can't confirm this.
Tried Docker 23.0.1 and 20.10.23 on Linux.

**Comment by austinarbor** [comment]
@AkihiroSuda I was (stupidly) testing the docker command on my mac instead of on linux. The difference is probably due to the underlying filesystem. Sorry for the bad report, closing this out.
