### ISSUE TITLE
Proposal: Add Azure pipeline support to support IPV6 test.

### ISSUE THREAD

**Issue by Zheaoli** [containerd/nerdctl#2031]
### What is the problem you're trying to solve

For now, the GHA is not supported IPV6 for the GitHub Hosted Runner yet.

So maybe we need a platform to run an extra IPV6 tests.

### Describe the solution you'd like

For now, I recommend the Azure Pipeline. FYI https://azure.microsoft.com/en-us/products/devops/pipelines & https://azure.microsoft.com/en-us/updates/ipv6-for-azure-virtual-network-is-now-generally-available-2/

There are already some open source projects to use Azure Pipeline as CI/CD platform, such as CPython(FYI https://github.com/python/cpython/tree/main/.azure-pipelines)

**Comment by fahedouch** [comment]
@yuchanns are you blocked by this to test https://github.com/containerd/nerdctl/pull/1558 ?

**Comment by yuchanns** [comment]
@fahedouch Yes. The proposal is practically for it.

**Comment by manugupt1** [comment]
I think we should just have an Azure pipeline for ipv6 test only and let everything else run on GHA

**Comment by AkihiroSuda** [comment]
wondering if we can just use this
https://github.com/containerd/containerd/blob/e366facb876598d783e07ba6baa2b61e62e6808c/.github/workflows/windows-hyperv-periodic.yml#L20

**Comment by marosset** [comment]
CC @lachie83 who manages the Azure sub we run K8s and containerd tests in.

**Comment by yuchanns** [comment]
Kindly ping @lachie83 :-)

**Comment by lachie83** [comment]
Thanks for the ping. I would like to know a little more about the frequency that these tests will be run, how long they will run for, and what resources you need (eg. single VM and what size?)

**Comment by Zheaoli** [comment]
> Thanks for the ping. I would like to know a little more about the frequency that these tests will be run, how long they will run for, and what resources you need (eg. single VM and what size?)

Thanks for the comment.

Here are the requirement for this project:

1. each PR should run the test on the Azure IPV6 machine
2. The total for each test should not be over 20mins.
3. I think maybe we need two 2C4G machines. cc @AkihiroSuda 

Feel free to comment if you got any issues. thanks! @lachie83

**Comment by yuchanns** [comment]
> I think we should just have an Azure pipeline for ipv6 test only and let everything else run on GHA

I shared the same idea as well.

**Comment by yuchanns** [comment]
ping @lachie83

**Comment by lachie83** [comment]
Please proceed with adding these tests.

**Comment by yuchanns** [comment]
@lachie83 We already got a PR (#1558) with requiring IPv6 support.

**Comment by lachie83** [comment]
Great! Do you need anything else from me?

**Comment by yuchanns** [comment]
@lachie83  Yes. In order to run IPv6-related integration tests, I need access to the Azure instance and make it the CI of this repository. As mentioned above said that you are managing the Azure sub to run K8s and containerd tests in, I would like to know what should we do to obtain this capability for nerdctl.

**Comment by yuchanns** [comment]
ping @lachie83

**Comment by AkihiroSuda** [comment]
What's current status of this?
@yuchanns @lachie83

**Comment by yuchanns** [comment]
Closed as #1558 is merged.
