### ISSUE TITLE
The unsupported restart policy message is not showing the supported value (when no capabilities are found, and the default "always" is set)

### ISSUE THREAD

**Issue by brunohenriquy** [containerd/nerdctl#2034]
### Description

The unsupported restart policy message is not showing the supported value (when no capabilities are found, and the default "always" is set):
---
<img width="665" alt="Screenshot 2023-02-20 at 02 26 14" src="https://user-images.githubusercontent.com/8320519/220016419-62432432-73bb-42e2-a733-75fcc061befa.png">

### Steps to reproduce the issue

1. Use an unsupported restart policy

### Describe the results you received and expected

Received:
<img width="665" alt="Screenshot 2023-02-20 at 02 26 14" src="https://user-images.githubusercontent.com/8320519/220016419-62432432-73bb-42e2-a733-75fcc061befa.png">

Expected:
<img width="737" alt="Screenshot 2023-02-20 at 02 26 06" src="https://user-images.githubusercontent.com/8320519/220016451-e48404d9-78ae-49e8-acd8-c1463e810e69.png">

### What version of nerdctl are you using?

1.2.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Rancher desktop, but I am compiling the main branch of nerdctl.

### Host information
MacBook M1.

**Comment by AkihiroSuda** [comment]
What's your daemon version?

**Comment by brunohenriquy** [comment]
> What's your daemon version?

Sorry, what do you mean? How do I discover it?

**Comment by suyanhanx** [comment]
> > What's your daemon version?
> 
> Sorry, what do you mean? How do I discover it?

You can use `nerdctl system info`.

**Comment by brunohenriquy** [comment]
> > > What's your daemon version?
> > 
> > 
> > Sorry, what do you mean? How do I discover it?
> 
> You can use `nerdctl system info`.

```
❯ nerdctl system info                                                                                                                                         
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.6.8
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.78-0-virt
 Operating System: Alpine Linux v3.16
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 5.786GiB
 Name: lima-rancher-desktop
 ID: 19421722-8793-4554-8547-e448d05e6100

**Comment by brunohenriquy** [comment]
@AkihiroSuda you meant containerd version? I guess it's 1.6.8
I am using RancherDesktop 1.7.0 which is using nerdctl 1.0.0, but I am compiling the nerdctl main branch locally and using it's binaries.

**Comment by fahedouch** [comment]
closed by https://github.com/containerd/nerdctl/pull/2033
