### ISSUE TITLE
nerdctl cannot restart the container

### ISSUE THREAD

**Issue by omaidb** [containerd/nerdctl#204]
![image](https://user-images.githubusercontent.com/18365223/117521085-75ddc200-afde-11eb-84ee-e5561319f0d3.png)

哪位英语好的大佬可以帮我翻译一下嘛
I want to restart the container.
  The usage of docker is:
     'docker restart container name';
But when I want to restart the container, I execute the following command:
'nerdctl restart container name';
nerdctl prompts not to use this restart command.
I found that when nerdctl cannot use the'restart' command,

Try to execute'nerdctl stop container name', wait for the container name to stop, and then execute'nerdctl start container name' to manually realize the role of `nerdctl restart container name' in this way.

After executing'nerdctl stop container name', the container name stopped working.
Then execute the command:
'nerdctl start container name';

nerdctl reported an error, but in fact the container has indeed restarted.

The prompt given by start is wrong, and the container has resumed from the suspended state.
The "restart" in the docker can restart the container very conveniently. It is recommended that nerdctl can provide the nerdctl restart command.
中文:
docker中的'docker restart 容器名'用来重启运行中的容器非常方便.
当我使用'nerdctl restat 容器名' 来重启运行中的容器时,发现nerdctl 提示没用restart 命令.

我手动执行'nerdctl stop 容器名',让这个容器停止,再用'nerdctl start 容器名'尝试让容器恢复运行.

输入完'nerdctl start 容器名'之后,nerdctl 提示了一个错误.
但暂停的容器 却恢复工作了.
我认为这是一个bug.如果bug得到确认,请修复它.

docker中的'docker restart  容器名' 这个命令能快速重启容器,希望nerdctl 增加这个功能.

![image](https://user-images.githubusercontent.com/18365223/117521153-e684de80-afde-11eb-979d-60bac52f55fe.png)

**Comment by AkihiroSuda** [comment]
Full reproducer please

**Comment by AkihiroSuda** [comment]
请试试 nerdctl version 和 nerdctl info （跟docker version和docker info一样）

**Comment by omaidb** [comment]
> 请尝试nerdctl版本和nerdctl info（跟docker version和docker info一样）
执行结果如下
![image](https://user-images.githubusercontent.com/18365223/117773953-86ef3300-b26b-11eb-86aa-908f70283f7f.png)

**Comment by AkihiroSuda** [comment]
Please try the latest version (0.14), and feel free to reopen if this is still an issue.
