### ISSUE TITLE
Snapshotters: use containerd's AppendInfoHandlerWrapper

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#2040]
https://github.com/containerd/nerdctl/blob/v1.2.0/pkg/imgutil/snapshotter.go should be replaced with:
- https://github.com/containerd/containerd/pull/8036

**Comment by danishprakash** [comment]
I can see this is tagged expert, does that mean it's out of bounds for external contributors? I'd like to look into this.

**Comment by AkihiroSuda** [comment]
> I can see this is tagged expert, does that mean it's out of bounds for external contributors? I'd like to look into this.

Thanks, contribution is welcome from anybody, but needs to be familiar with stargz, nydus, overlaybd, etc.
