### ISSUE TITLE
Support State.Error field in inspect command

### ISSUE THREAD

**Issue by ningziwen** [containerd/nerdctl#2052]
### What is the problem you're trying to solve

`nerdctl inspect` cannot return State.Error field today.

```
$ nerdctl run -d public.ecr.aws/amazonlinux/amazonlinux:2
2fd4c9d197320279055bfca5a109433935e762fc91bcbe371815a6cf7f39fe03
$ nerdctl inspect --format {{.State.Status}}:{{.State.Error}} 2fd4c9d197320279055bfca5a109433935e762fc91bcbe371815a6cf7f39fe03
WARN[0000] failed to inspect NetNS                       error="failed to Statfs \"/proc/4058/ns/net\": no such file or directory" id=2fd4c9d197320279055bfca5a109433935e762fc91bcbe371815a6cf7f39fe03
FATA[0000] 1 errors: [template parsing error: template: :1:26: executing "" at <.State.Error>: map has no entry for key "Error"]
```

### Describe the solution you'd like

State.Error exists in the inspect response, and it is an existing TODO in comment. https://github.com/containerd/nerdctl/blob/e09d7f8a419ee2d1152386ab654afc55f6e2201b/pkg/inspecttypes/dockercompat/dockercompat.go#L170

### Additional context

https://github.com/runfinch/finch/issues/242

**Comment by fahedouch** [comment]
container `exit error` is rendered when the container process exit : 
https://github.com/containerd/containerd/blob/v1.6.19/process.go#L44

we need to store it in container metadata so we can retrieve it later

I will take this ticket :)

**Comment by fahedouch** [comment]
Closed by https://github.com/containerd/nerdctl/pull/2073
