### ISSUE TITLE
`Sign()` should receive the digest from `Push()`

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#2135]
https://github.com/containerd/nerdctl/blob/8a1f2278ac4b1615625b1099367b4b6900c9d969/pkg/cmd/image/push.go#L151

>> not related to this PR. Just notice when pushing an image, sign (line 152) happens **after** push (line 133-150). Is this expected?

> IIUC signing after pushing is ok (for cosign, at least), but the current implementation is wrong anyway; the `Sign()` function should receive the digest from the `Push()` function to prohibit TOCTOU.
>
> (I'm mentioning this bug publicly because the cosign integration is still experimental for nerdctl)

_Originally posted by @AkihiroSuda in https://github.com/containerd/nerdctl/pull/2132#discussion_r1150932060_

**Comment by AkihiroSuda** [comment]
cc @developer-guy

**Comment by developer-guy** [comment]
yes, you are right we should rely on digests, not on the tags. I'll fix this
