### ISSUE TITLE
--insecure-registry do not effect

### ISSUE THREAD

**Issue by p0mp0k0** [containerd/nerdctl#2148]
### Description

I pulled the rancher image from a http registry, I used option --insecure-registry, but it do not effect, the pull operation always used https and got 403 error 
nerdctl --insecure-registry pull hub-mirror.c.163.com/rancher/rancher
WARN[0000] skipping verifying HTTPS certs for "hub-mirror.c.163.com"
FATA[0000] failed to resolve reference "hub-mirror.c.163.com/rancher/rancher:latest": unexpected status from HEAD request to https://hub-mirror.c.163.com/v2/rancher/rancher/manifests/latest: 403 Forbidden

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

pull the image

### What version of nerdctl are you using?

1.2.1

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Rancher Desktop for Windows

**Comment by nmreadelf** [comment]
I executed the command in issue and the pull operation succeeded. However, I believe the issue may be related to a network problem on your end.
May I inquire as to whether you have attempted to utilize an alternative registry mirror.

**Comment by fahedouch** [comment]
` nerdctl --insecure-registry`  need a http support in the registry side . Multiple registries enforce `https`  protocol.
