### ISSUE TITLE
nerdctl run does not allow for binding a named pipe

### ISSUE THREAD

**Issue by bhaeussermann** [containerd/nerdctl#2199]
### Description

I'm trying to bind the named pipe for the containerd socket to a container on Windows using the following command:

```
nerdctl run -it --rm -v \\.\pipe\containerd-containerd:\\.\pipe\containerd-containerd mydockerhub/my-image my-container
```

This yields the following error:

```
time="2023-04-24T07:10:13Z" level=fatal msg="error while parsing \"\\\\\\\\.\\\\pipe\\\\containerd-containerd:\\\\\\\\.\\\\pipe\\\\containerd-containerd\": failed to get volume \"\\\\\\\\.\\\\pipe\\\\containerd-containerd\": malformed name \\\\.\\pipe\\containerd-containerd: identifier \"\\\\\\\\.\\\\pipe\\\\containerd-containerd\" must match ^[A-Za-z0-9]+(?:[._-](?:[A-Za-z0-9]+))*$: invalid argument"
```

When running the image on a machine with Docker using the Docker CLI, this kind of command works, only using `\\.\pipe\docker_engine` for the name of the pipe:

```
docker run -it --rm -v \\.\pipe\docker_engine:\\.\pipe\docker_engine mydockerhub/my-image my-container
```

Clearly the regular expression used in nerdctl to check the volume name does not account for a named pipe. Is this an oversight or is it intentional for some reason?

### Steps to reproduce the issue

1. Run the command:
```
nerdctl run --rm -v \\.\pipe\containerd-containerd:\\.\pipe\containerd-containerd hello-world
```

### Describe the results you received and expected

The container should run successfully and be bound to the containerd named pipe.

### What version of nerdctl are you using?

1.3.1

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by TinaMor** [comment]
@AkihiroSuda I'd like to investigate this further.
