### ISSUE TITLE
support of nerdctl inspect {imagename}

### ISSUE THREAD

**Issue by mviereck** [containerd/nerdctl#222]
>    nerdctl inspect - Return low-level information on objects. Currently, only supports container objects.

Currently nerctl does not support to inspect images.
Will that be added in future?

Background:
Yet I am adding support for nerdctl in [x11docker](https://github.com/mviereck/x11docker). For several features I need to inspect the image. The most important informations are `ENTRYPOINT` and `CMD`.  Further checks are done for `WORKDIR`, `USER` and the image architecture (mostly amd64).

Is there another way to get information about `ENTRYPOINT` and `CMD` before starting the container?

**Comment by AkihiroSuda** [comment]
PR is wanted

**Comment by mviereck** [comment]
I have no experience in go so I cannot provide a PR myself, unfortunately.

Is there another way to get information about ENTRYPOINT and CMD before starting the container?

`nerdctl inspect {container}` works; so if there would be a `nerdctl create` I could obtain the information from the non-running container. That would be a reasonable workaround. However, `nerdctl create` is not included yet, too. Any chance that you would include this?

**Comment by mviereck** [comment]
I've included a workaround in x11docker that allows all x11docker features if the user provides a container command himself. So my request is less urgent now, but still desirable.

(Another workaround is needed in x11docker because `nerdctl exec --user` is not supported. However, the impact is minor.)

**Comment by fahedouch** [comment]
@AkihiroSuda  @mviereck  I take this ticket

**Comment by fahedouch** [comment]
`nerdctl inspect {imagename}` is now available (https://github.com/containerd/nerdctl/pull/239)

TODO: refacto `ParseRepoTag`  function in `pkg/imgutil/imgutil.go` (related : https://github.com/containerd/nerdctl/pull/239#discussion_r653170808 https://github.com/containerd/nerdctl/pull/239#discussion_r653170870)

**Comment by mviereck** [comment]
Great, much thanks!
I hope it will be available in a release soon.

**Comment by AkihiroSuda** [comment]
Released v0.9.0 https://github.com/containerd/nerdctl/releases/tag/v0.9.0

**Comment by mviereck** [comment]
Thank you very much!
