### ISSUE TITLE
Support `--network` flag in nerdctl build

### ISSUE THREAD

**Issue by vsiravar** [containerd/nerdctl#2233]
### What is the problem you're trying to solve

Support adding network to RUN instructions in `nerdctl build` by supporting `--network` flag supported by BuildKit. 

----------------------------------
 Currently                 
```
$ nerdctl build --network=none . 
FATA[0000] unknown flag: --network 
```

### Describe the solution you'd like

Make `nerdctl build --network` flag compatible with docker i.e support `--network=host|none|default` based on BuildKit supported flag. https://github.com/docker/engine/blob/master/builder/builder-next/builder.go#L313.

**Comment by vsiravar** [comment]
@yuchanns are you actively working on this feature, I can contribute to a branch if you have one. Cheers!

**Comment by yuchanns** [comment]
@vsirava Sorry, kind of busy these months. You are welcome to start a thread on it if you'd like.

**Comment by vsiravar** [comment]
### Proposed implementation for improving feature compatibility with docker and podman

`buildkit` allows for setting up networks for build using `force-network-mode` [option](https://github.com/moby/buildkit/blob/ee8af2d80fa83271e817aa7cf0d7198c1a05f967/frontend/dockerui/config.go#L33). moby uses a similar logic to setup [networks for build](https://github.com/moby/moby/blob/193f16238bb5ce1eb87efd8da03dce41466ef8c4/builder/builder-next/builder.go#L332C3-L332C38). Ran some tests using these flags in `buildctl`. 


#### Test with  `force-network-mode=none`

```
sudo buildctl --addr=unix:///run/buildkit/buildkitd.sock build  --progress=auto  --frontend=dockerfile.v0 --local=context=/Users/siravara/workspace/buildkit-tests/. --output=type=image,unpack=true --local=dockerfile=/Users/siravara/workspace/buildkit-tests/ --opt=filename=Dockerfile --opt=force-network-mode=none
[+] Building 13.2s (5/6)                                                                                                                                                             
<Clipped>
------
Dockerfile:2
--------------------
   1 |     FROM alpine
   2 | >>> RUN apk add --no-cache curl
   3 |     RUN curl -I http://google.com
   4 |     
--------------------
error: failed to solve: process "/bin/sh -c apk add --no-cache curl" did not complete successfully: exit code: 1
 ```
Test fails as expected as there is no network for build, so cannot download curl and ping `google.com`. 

#### Test with  `force-network-mode=host` 

insecure entitlements in daemon `insecure-entitlements = [ "network.host", "security.insecure" ]`

```
 sudo buildctl --addr=unix:///run/buildkit/buildkitd.sock build  --progress=auto  --frontend=dockerfile.v0 --local=context=/Users/siravara/workspace/buildkit-tests/. --output=type=image,unpack=true --local=dockerfile=/Users/siravara/workspace/buildkit-tests/ --opt=filename=Dockerfile --opt=force-network-mode=host --allow=network.host --allow=security.insecure
[+] Building 8.3s (7/7) FINISHED                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                            0.0s
<Clipped>                                                                                                                                                      0.2s 
 => => exporting manifest sha256:a7f23552ef7507c088a27e7750628ebd3bbc4db8db46f46a20e5fee38f43d391                                                                               0.0s 
 => => exporting config sha256:2cd4d8da42f7afe5bfe1442a7531de7a54948da7fc9f36ba373fe6c2be3e6d44  
```

### Implementation details in nerdctl

- Add network to build options. 
- If network options are valid for buildkit, i.e host, none, invoke `buildctl build` by appending to `buildctlArgs`(i.e `--opt=force-network-mode=<network mode>` in [pkg/cmd/builder/build.go](https://github.com/containerd/nerdctl/blob/main/pkg/cmd/builder/build.go)


@AkihiroSuda lmk if this approach is okay. I can open a PR for it. Cheers!

**Comment by AkihiroSuda** [comment]
SGTM
