### ISSUE TITLE
nerdctl load -i busybox.tar（digest not found

### ISSUE THREAD

**Issue by mpv945** [containerd/nerdctl#225]
sudo nerdctl pull busybox:stable
sudo nerdctl save -o busybox.tar busybox:stable
sudo nerdctl rmi busybox:stable

sudo nerdctl load -i busybox.tar

FATA[0000] content digest sha256:9708dc541771170e42aadc4c3c4477ec15e91e595673493bbbb78b7c8b75b0b5: not found

**Comment by AkihiroSuda** [comment]
Should be resolved in https://github.com/containerd/nerdctl/pull/227

Thanks @fahedouch
