### ISSUE TITLE
depends_on in compose build and logs are not compatible with Docker

### ISSUE THREAD

**Issue by ningziwen** [containerd/nerdctl#2261]
### Description

In `nerdctl compose build`, when pointing specific service, the dependencies of it are also built.
In `nerdctl compose logs`, when pointing specific service, the logs of the dependencies of it are also printed.

Compose-spec only requires depends_on effective on runtime instead of build or logs. https://github.com/compose-spec/compose-spec/blob/master/spec.md#depends_on

In Docker, build and logs don't execute for dependencies.

### Steps to reproduce the issue

1.
```
$ cat Dockerfile
FROM nginx:1.19-alpine
RUN uname -m > /usr/share/nginx/html/index.html

$ cat docker-compose.yml
services:
  svc0:
    build: .
    image: public.ecr.aws/amazonlinux/amazonlinux:2 # replace with your registry
    ports:
    - 8080:80
  svc1:
    build: .
    image: public.ecr.aws/docker/library/ubuntu:latest # replace with your registry
    ports:
    - 8081:80
    depends_on:
    - svc0

```
2.
```
nerdctl compose build svc1
nerdctl compose up -d svc1
nerdctl compose logs svc1
```

### Describe the results you received and expected

Dependencies are executed for build, up and logs, but should not executed for build and logs for Docker compliance.

### What version of nerdctl are you using?

Latest main branch.

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by yankay** [comment]
It seems has fixed.
/close
