### ISSUE TITLE
`nerdctl create --restart=unless-stopped` behaviour is inconsistent with docker

### ISSUE THREAD

**Issue by wzshiming** [containerd/nerdctl#2270]
### Description

This behavior is inconsistent with docker when the container is created and started directly.

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

Containers are not started immediately after creation.

### What version of nerdctl are you using?

latest

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by AkihiroSuda** [comment]
I’m wondering if Docker’s behavior rather might be a bug, but if people are already depending on that “bug”, nerdctl should replicate the “bug” too.

**Comment by wzshiming** [comment]
For this behavior, I think docker's is correct

`create` should simply be created and should not be started.
`run` is created and started

and its behavior should not change with `--restart` args.

`nerdctl create --restart=no` just created
`nerdctl create --restart=unless-stopped` will create and start

**Comment by yankay** [comment]
The `nerdctl create --restart=always` has the same issue .
