### ISSUE TITLE
nerdctl push image can't show right rate  

### ISSUE THREAD

**Issue by cyxinda** [containerd/nerdctl#2279]
### Description

I push image local image to harbor with nerdctl ,the nerdctl show wrong upload rate .
```bash
root@ubuntu:~/tmp/tmp# nerdctl -n k8s.io push repository.knowdee.com/library/controller:v1.7.0
INFO[0000] pushing as a reduced-platform image (application/vnd.docker.distribution.manifest.list.v2+json, sha256:edce17b7affcfd0a09bb444e230b74875e935d60c5045f510bc7f7095532f068) 
index-sha256:edce17b7affcfd0a09bb444e230b74875e935d60c5045f510bc7f7095532f068:    done           |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:48cbda0f953e398cdcad7129aadb4fb0338a991299b6b466c778906dc39837ec: done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:0d4c0564c46586dec1712522231ff4b2dc2864ebbb46c9b9040b22e971819b05:   done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 44.5s                                                                    total:  13.4 K (308.0 B/s)      
```
![1111](https://github.com/containerd/nerdctl/assets/7237898/17fb8bf6-2cb0-4f15-a78e-767cfc9725a4)
The command line show the rate of upload is 308.0 B/s, But the actual upload speed is much greater.
I think what wrong happend about nerdctl .

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

nerdctl can show the upload speed in real time and correctly.

### What version of nerdctl are you using?

root@ubuntu:~/tmp/tmp# nerdctl --version
nerdctl version 1.4.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

root@ubuntu:~/tmp/tmp# uname -a
Linux ubuntu 5.19.0-43-generic #44~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon May 22 13:39:36 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by yankay** [comment]
It has been fixed in the containerd , so would we close it ?
/close
