### ISSUE TITLE
nerdctl can run a container with same name

### ISSUE THREAD

**Issue by yckaolalala** [containerd/nerdctl#2284]
### Description

nerdctl can run a container with same name .

### Steps to reproduce the issue

1. nerdctl run --name=hello --restart always -dt alpine:3.13 sleep infinity
2. nerdctl stop hello 
3. nerdctl run --name=hello --restart always -dt alpine:3.13 sleep infinity
4. nerdctl stop hello

```
FATA[0000] 1 errors:
multiple IDs found with provided prefix: hello 
```

### Describe the results you received and expected

In docker, return error when run a container with same name

1. docker run --name=hello --restart always -dt alpine:3.13 sleep infinity
2. docker stop hello
3. docker run --name=hello --restart always -dt alpine:3.13 sleep infinity

```
docker: Error response from daemon: Conflict. The container name "/hello" is already in use by container "84925e311c30914abd681dd835089ea17e75624448d7b9fdb120d2fb74497922". You have to remove (or rename) that container to be able to reuse that name.
```

### What version of nerdctl are you using?

1.4.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by yckaolalala** [comment]
nerdctl create has same issue .

**Comment by AkihiroSuda** [comment]
Thanks
