### ISSUE TITLE
`nerdctl run/create--restart always -dt` does not automatically restart (`-t` (tty) is the reason of the failure)

### ISSUE THREAD

**Issue by yankay** [containerd/nerdctl#2296]
### Description

The `nerdctl run/create --restart always -dt` with `tty` does not automatically restart

When I investigate the https://github.com/containerd/nerdctl/issues/2286 .
I found that the create and run commands are the same, and the '--tty' is the fail reason for the restart.

### Steps to reproduce the issue

1.  run in root user
2. test nerdctl run container and create container

```
nerdctl create --name=create-test-with-tty --restart always -t alpine:3.13 sleep infinity
nerdctl run --name=run-test-with-tty --restart always -dt alpine:3.13 sleep infinity
nerdctl create --name=create-test --restart always alpine:3.13 sleep infinity
nerdctl run --name=run-test --restart always -d alpine:3.13 sleep infinity
nerdctl ps -a |grep "sleep infinity"
```

```
[root@kay121 ~]# nerdctl ps -a |grep "sleep infinity"
1fc019640113    docker.io/library/alpine:3.13                                 "sleep infinity"          15 seconds ago    Created             create-test-with-tty
23384b4bccaa    docker.io/library/alpine:3.13                                 "sleep infinity"          15 seconds ago    Up                  create-test
638dbcd86708    docker.io/library/alpine:3.13                                 "sleep infinity"          15 seconds ago    Up                  run-test
b4db955949b0    docker.io/library/alpine:3.13                                 "sleep infinity"          15 seconds ago    Up                  run-test-with-tty
```

4. start the create-test-with-tty (to verify the restart policy later)
```
nerdctl start create-test-with-tty
nerdctl ps -a |grep "create-test-with-tty"
```
```
1fc019640113    docker.io/library/alpine:3.13                                 "sleep infinity"          About a minute ago    Up                  ```
```

5. kill the 'sleep' process to verify the restart policy

```
ps -ef|grep -v grep|grep sleep|awk -F' ' '{print $2}' |xargs kill -9
nerdctl ps -a |grep "sleep infinity"
```
```
1fc019640113    docker.io/library/alpine:3.13                                 "sleep infinity"          3 minutes ago     Created             create-test-with-tty
23384b4bccaa    docker.io/library/alpine:3.13                                 "sleep infinity"          3 minutes ago     Up                  create-test
638dbcd86708    docker.io/library/alpine:3.13                                 "sleep infinity"          3 minutes ago     Up                  run-test
b4db955949b0    docker.io/library/alpine:3.13                                 "sleep infinity"          3 minutes ago     Created             run-test-with-tty
```

### Describe the results you received and expected

`nerdctl run --restart -dt` with tty can work correctly like without tty.

### What version of nerdctl are you using?

Client:
 Version:       v1.4.0
 OS/Arch:       linux/amd64
 Git commit:    7e8114a82da342cdbec9a518c5c6a1cce58105e9
 buildctl:
  Version:

Server:
 containerd:
  Version:      v1.7.1
  GitCommit:    1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc:
  Version:      1.1.7
  GitCommit:    v1.1.7-0-g860f061b

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by yckaolalala** [comment]
Hi @yankay 

I found an issue (#317) where it is mentioned that currently the flags -i and -d cannot be specified together. This validation is implemented in the following files:
https://github.com/containerd/nerdctl/blob/main/cmd/nerdctl/container_exec.go#L73
https://github.com/containerd/nerdctl/blob/main/cmd/nerdctl/compose_run.go#L163
https://github.com/containerd/nerdctl/blob/main/cmd/nerdctl/compose_exec.go#L95
However, the validation is missing in
https://github.com/containerd/nerdctl/blob/main/pkg/cmd/container/create.go#L141
