### ISSUE TITLE
"No such file or directory" error occur in container after execute `nerdctl commit`

### ISSUE THREAD

**Issue by zhenxuanxin** [containerd/nerdctl#2312]
### Description

Cannot make directory or touch new file after execute `nerdctl commit` on a container. container filesystem been unwritable.

### Steps to reproduce the issue

1. `nerdctl run -td --name test ubuntu:18.04`
2. `nerdctl commit test committed:v1`
3. execute `mkdir /var/test` or `touch /var/test.txt` in `test` container that we created in step 1

### Describe the results you received and expected

the following error  may occur: `No such file or directory`

![image](https://github.com/containerd/nerdctl/assets/4496285/4c9705c3-8a41-4130-99ba-5343ed3c4e6f)

### What version of nerdctl are you using?

nerdctl version 1.2.1

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

`nerdctl info`

```txt
Client:
 Namespace:	k8s.io
 Debug Mode:	false

Server:
 Server Version: v1.6.19
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: aufs native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-112-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 27.47GiB
 Name: dev7-master1
 ID: 41dcaf6a-4251-4905-b13b-6dd59a8c0208
```

`containerd -v`

```txt
containerd github.com/containerd/containerd v1.6.19 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
```

`free -h`

```txt
              total        used        free      shared  buff/cache   available
Mem:            27G         10G        1.8G         38M         15G         20G
Swap:            0B          0B          0B
```

**Comment by yuchanns** [comment]
Looks like a problem of containerd `diff` after debugging it. Need further investigation here.

**Comment by yuan6711043** [comment]
I meet the same issue，it is can be reproduced stably after committing by nerdctl.
Can any one have some hints to resolve it?

**Comment by yankay** [comment]
HI @zhenxuanxin 

I have reproduced the issue at the containerd v1.6.19 
But the issue **cannot** be reproduced in containerd v1.7.1.

So it has been fix by the containerd v1.7.1 :-)

**Comment by yuchanns** [comment]
@yankay https://github.com/containerd/containerd/issues/6077 I think it's related. Fixed in https://github.com/containerd/containerd/pull/8259

**Comment by yankay** [comment]
> @yankay [containerd/containerd#6077](https://github.com/containerd/containerd/issues/6077) I think it's related. Fixed in [containerd/containerd#8259](https://github.com/containerd/containerd/pull/8259)
> 
> > And later for that container we observe this "undefined behavior" as the RootFS of that container becoming partially not-writable (an attempt to create a file results in "No such file or directory" error).

Thanks @yuchanns

**Comment by zhenxuanxin** [comment]
Thanks all, i will upgrade to v1.7.1 do more test

**Comment by zhenxuanxin** [comment]
@yankay Can use `>= v1.6.20` or `>= v1.7.1` to fix this issue, fix code already cherry picked in [containerd/containerd#8299](https://github.com/containerd/containerd/pull/8299) and [containerd/containerd#8300](https://github.com/containerd/containerd/pull/8300)

**Comment by yankay** [comment]
Thanks @zhenxuanxin  :-)

**Comment by oldthreefeng** [comment]
thanks @yankay  @zhenxuanxin
