### ISSUE TITLE
`nerdctl kill` container with restartPolicy behaviour is inconsistent with docker #2270

### ISSUE THREAD

**Issue by yankay** [containerd/nerdctl#2315]
### Description

This behavior is inconsistent with docker when killing the container with restartPolicy.

## In Docker
```
docker run -d --restart=on-failure --name haha nginx
docker kill --signal=SIGKILL haha
docker inspect haha |grep -A 10 State
```

The container is stopped:
```
"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2023-06-21T11:40:02.476183268Z",
```

## In Nerdctl

```
nerdctl run -d --restart=on-failure --name haha nginx
nerdctl kill --signal=SIGKILL haha
nerdctl inspect haha |grep -A 10 State
```

The container is been restarted:
```
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "Pid": 183337,
            "ExitCode": 0,
            "Error": "",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
```

### Describe the results you received and expected

The docker behavior is expected

### What version of nerdctl are you using?

Client:
 Version:       v1.4.0-71-ga8e34b6.m
 OS/Arch:       linux/amd64
 Git commit:    a8e34b661df4a7799bb8033ea6cd515802ffb6d9.m
 buildctl:
  Version:

Server:
 containerd:
  Version:      v1.7.1
  GitCommit:    1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc:
  Version:      1.1.7
  GitCommit:    v1.1.7-0-g860f061b

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by fahedouch** [comment]
closed by https://github.com/containerd/nerdctl/pull/2330
