### ISSUE TITLE
nerdctl inspect to show State.StartedAt

### ISSUE THREAD

**Issue by austinvazquez** [containerd/nerdctl#2335]
### What is the problem you're trying to solve

Docker CLI has both `Created` and `State.StartedAt` fields on inspect.

Currently nerdctl supports `Created` and `State.FinishedAt` but not `State.StartedAt`

### Describe the solution you'd like

It would be great to add this field to the information for objects.

**Comment by austinvazquez** [comment]
Dug a little deeper to understand the gap here. TLDR; containerd does not support `StartedAt` universally. Somewhat makes sense because it is a little difficult to maintain this state.

The CRI plugin supports this by taking the timestamp after `task.Start`. We could do something similar but would need to maintain that state somewhere.

Happy to close this as not planned unless others have another idea how to implement.

**Comment by AkihiroSuda** [comment]
Probably this should be implemented in the containerd daemon

**Comment by fahedouch** [comment]
IMO State can be easily maintained via `annotation`

**Comment by apostasie** [comment]
> IMO State can be easily maintained via `annotation`

@fahedouch Can you set annotations from inside ocihooks though?

**Comment by fahedouch** [comment]
> > IMO State can be easily maintained via `annotation`
> 
> @fahedouch Can you set annotations from inside ocihooks though?

no because it is happening before the startup of the container. I think the good place to handle this in the `containerd-shim` side

**Comment by apostasie** [comment]
> > > IMO State can be easily maintained via `annotation`
> > 
> > 
> > @fahedouch Can you set annotations from inside ocihooks though?
> 
> no because it is happening before the startup of the container. I think the good place to handle this is the `containerd-shim` .

Sure, that would be ideal if containerd would allow to query that.
We can do it here though, as proposed in the PR (inside ocihooks).

Totally understand if you would rather wait to see it implemented over there though.

**Comment by apostasie** [comment]
Fixed by #3003

@AkihiroSuda can you close this one?

**Comment by AkihiroSuda** [comment]
Thanks
