### ISSUE TITLE
Is it Possible To Login GCP Artifact Registry With Access Token

### ISSUE THREAD

**Issue by oguzhanoyan** [containerd/nerdctl#2356]
### What is the problem you're trying to solve

In [these](https://cloud.google.com/artifact-registry/docs/docker/pushing-and-pulling#pull-crictl) documentation, as I understood, we can log in to artifact registry with the access token in compute engine machine by getting oauth2accesstoken from metadata server, is it possible to login or push or pulling container image like just typing `nerdctl --login "oauth2accesstoken:ACCESS_TOKEN "` .

### Describe the solution you'd like

nerdctl login "oauth2accesstoken:ACCESS_TOKEN gcr.io"
nerdctl push image login "oauth2accesstoken:ACCESS_TOKEN " 
nerdctl pull image login "oauth2accesstoken:ACCESS_TOKEN "

**Comment by fahedouch** [comment]
```
gcloud auth print-access-token | nerdctl login --username oauth2accesstoken --password-stdin https://LOCATION-docker.pkg.dev
```
