### ISSUE TITLE
nerdctl support of HTTP Headers

### ISSUE THREAD

**Issue by sambabal19** [containerd/nerdctl#2375]
### What is the problem you're trying to solve

I'm using both docker and nerdctl, and with docker I can successfully use customized HTTP headers, however nerdctl does not seem to support this feature. https://docs.docker.com/engine/reference/commandline/cli/#custom-http-headers

nerdctl aims to be docker compatible. Is there a way we can add the Custom HTTP headers support ? 

If possible, how could we update nerdctl and implement this feature ?

### Describe the solution you'd like

Discussion and suggestions would be really appreciated.

https://github.com/containerd/nerdctl/blob/main/docs/config.md

**Comment by AkihiroSuda** [comment]
This should work?
https://github.com/containerd/containerd/blob/v1.7.2/docs/hosts.md#header-fields-in-the-toml-table-format
