### ISSUE TITLE
Support com.docker.compose.project label for unambiguously marking the project

### ISSUE THREAD

**Issue by TheDiveO** [containerd/nerdctl#241]
`docker-compose` attaches a label `com.docker.compose.project` to every service container created by it. This allows container diagnosis tools to clearly identify groups of containers belonging to the same composer project, without the need to resort to container name parsing heuristics. It would be beneficial for such tools if `nerdctl` would support either the existing `com.docker.compose.project` label or alternatively its own `nerdctl/project` label.

**Comment by fahedouch** [comment]
Hi @TheDiveO ,

we already attach labels to containers created by docker-compose

https://github.com/containerd/nerdctl/blob/cc7dfaed642fc335c46d4d5eed996e63dd620956/pkg/composer/serviceparser/serviceparser.go#L403-L409

but we must implement the `--filter` flag to be able to filter on these containers

I take the ticket :)

**Comment by TheDiveO** [comment]
From what I saw using a nerdctl version checked out the date of my issue I could not find any project label at the containerd API level. External diagnosis tools need the label at containerd's API level, not at nerdctl's CLI level. Am I overlooking some label here?

**Comment by AkihiroSuda** [comment]
The label is now set on containers (https://github.com/containerd/nerdctl/pull/250).

TODO: set labels on volumes and networks

**Comment by TheDiveO** [comment]
Thank you very much!

**Comment by AkihiroSuda** [comment]
Done in #274
