### ISSUE TITLE
Support for multiple machines?

### ISSUE THREAD

**Issue by vsoch** [containerd/nerdctl#2445]
Hi! Is it possible to run a setup across machines? My use case is wanting to be able to spin up rootless container orchestration, but spanning hosts. Thanks!

**Comment by yankay** [comment]
HI @vsoch 

It may be not.
The same as https://github.com/containerd/nerdctl/issues/473

**Comment by yuchanns** [comment]
Closed with duplicated

**Comment by AkihiroSuda** [comment]
Multi-node orchestration (like Docker Swarm) is out of the scope of the project, but it should be able to expose Kubernetes ports and VXLAN ports with `nerdctl run -p` to create a Kubernetes cluster inside multiple nerdctl hosts.


> The same as https://github.com/containerd/nerdctl/issues/473

Seems different.
