### ISSUE TITLE
Ability to Specify Container ID

### ISSUE THREAD

**Issue by austinarbor** [containerd/nerdctl#2448]
### What is the problem you're trying to solve

When creating a container, it would be nice to be able to specify the container id instead of using the generated ID. 

https://github.com/containerd/nerdctl/blob/3dd297466d56ab0d6c169016576ade4ff8ac98a0/pkg/cmd/container/create.go#L73

### Describe the solution you'd like

New flag added like `--container-id` which would be used instead of the generated ID when present

**Comment by yankay** [comment]
HI @austinarbor

The nerdctl is  Docker-compatible CLI , and there seens no `--container-id` args in Docker CLI. :-)

**Comment by AkihiroSuda** [comment]
Why do you need this?

**Comment by yuchanns** [comment]
The option `--name` is what you should use to specify the readable identity of the container. The container ID is not intended to be specified.

**Comment by austinarbor** [comment]
It's not really a necessity, just a "nice to have" and it looked like it would be an easy addition to the codebase. I am using `nerdctl` in combination with the low level golang client and having more friendly container ids improves the output of `ps` etc

@yankay the only change required would be using the passed in id instead of the generated id on the line I linked

**Comment by fahedouch** [comment]
Whenever possible, identify a container by its name and not by its ID.

The ID is not intended to be human friendly, but the name is.

**Comment by fahedouch** [comment]
feel free to reopen if needed
