### ISSUE TITLE
nerdctl version requires rootless containerd

### ISSUE THREAD

**Issue by arnaldo2792** [containerd/nerdctl#2455]
### Description

I don't know if this is intended, but `nerdctl version` requires rootless containerd to be running, is that the expected behavior?:

```bash
~ ❯ nerdctl --version
nerdctl version 1.5.0
~ ❯ nerdctl version
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): stat /run/user/1000/containerd-rootless: no such file or directory

```

### Steps to reproduce the issue

1. Run `nerdctl version`, without rootless containerd

### Describe the results you received and expected

I would expect that `nerdctl version` shows the version of whatever it is I'm running

### What version of nerdctl are you using?

1.5.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

Surprisingly, `nerctl info` also requires rootless containerd:

```bash
~   nerdctl info
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): stat /run/user/1000/containerd-rootless: no such file or directory
```
FWIW, I'm using Arch Linux, but even building from the tip of main, the error persists.

**Comment by yuchanns** [comment]
The sub commands `version` and `info` retrieve the server-side information so security privileges are required. You can run it after `sudo`. Otherwise, you should have rootless containerd running.
This is not a bug but an expected behavior.

**Comment by arnaldo2792** [comment]
Right, and in addition, a note in the main README(?).
