### ISSUE TITLE
test-integration-windows fails - missing zero-length list check ?

### ISSUE THREAD

**Issue by metux** [containerd/nerdctl#2458]
### Description

See here:
https://github.com/containerd/nerdctl/actions/runs/5952944195/job/16146057148?pr=2447

The failure really doesn't seem to be connected to the PR.

Crashing in container_list.go:213
The ListEntry's Name[] list is empty, but we're trying to retrieve the first element.
Looks like there's a container w/o a name assigned.

No idea whether this ever allowed to happen (obviously is *does* happen). But I believe there should be a sanity check, at least print out a warning and possibly exit w/ error code. IMHO, a client should never crash on broken replies from a server.

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

See https://github.com/containerd/nerdctl/actions/runs/5952944195/job/16146057148?pr=2447

### What version of nerdctl are you using?

master branch

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by metux** [comment]
Turns out, these tests fail on other targets, too:

https://github.com/containerd/nerdctl/actions/runs/5952944195/job/16146055831?pr=2447
https://github.com/containerd/nerdctl/actions/runs/5952944195/job/16146055311?pr=2447

**Comment by fahedouch** [comment]
thanks for raising this Bug , would please open a PR to address a fix.

We also need to investigate on the random behavior of the `TestCreateProcessContainer` test
