### ISSUE TITLE
Is it possible to run buildkitd as container in containerd system-namespace?

### ISSUE THREAD

**Issue by fuweid** [containerd/nerdctl#25]
nerdctl needs user to install buildkitd. So is it possible to support system-plugin as container running in specific container namespace? If so, the user doesn't need to care about buildkitd, nerdctl can help to install buildkitd as running container.

**Comment by AkihiroSuda** [comment]
Yes, this should be possible for OCI worker. This might be hard for containerd worker, but I guess we don't really need to use containerd worker.

**Comment by AkihiroSuda** [comment]
We are going to recommend using containerd worker (https://github.com/containerd/nerdctl/pull/858), so let me close this one
