### ISSUE TITLE
some flags of compose ps are missing

### ISSUE THREAD

**Issue by tanghaowillow** [containerd/nerdctl#2502]
Hi, maintainers. I find that `nerdctl compose ps` shows all containers by default instead of running ones, which is different with docker compose.  Then I notice that some other flags like `--quiet` and  `--status` are also missing after investigating the code. 
Sorry if this is as not planned.

**Comment by tanghaowillow** [comment]
@AkihiroSuda  May I take a stab at this since it has been marked as a good first issue :)

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda May I take a stab at this since it has been marked as a good first issue :)

Yes of course, thanks
