### ISSUE TITLE
compose: env substitution support is missing?

### ISSUE THREAD

**Issue by furkanmustafa** [containerd/nerdctl#252]
When an `.env` file is in place (near `docker-compose.yaml`), it supports this operation for example;

```
# .env file
SOURCE_ROOT=/home/myuser/sources
```

```yaml
version: "3.4"
services:
  myapi:
    build: $SOURCE_ROOT/api
```

basicly anything in docker-compose yaml is substituted with using the vars in `.env` file (probably before parsing yaml? not sure)

in `nerdctl`, we got this error;

```
WARN[0000] Ignoring: [Extensions]
WARN[0000] build.config should be relative path, got "/api"
INFO[0000] Building image dev_api_main
[+] Building 0.0s (0/0)
error: could not find /api: stat /api: no such file or directory
FATA[0000] unrecognized image format
FATA[0000] error while building image dev_api_main: exit status 1
```

**Comment by AkihiroSuda** [comment]
We will need to use this function  https://github.com/compose-spec/compose-go/blob/27a7f91ffd0a2cf4974058b7e5bfa23d16c06890/cli/options.go#L174

**Comment by ChristianCiach** [comment]
Referencing https://github.com/containerd/nerdctl/issues/215#issuecomment-853203554

**Comment by furkanmustafa** [comment]
> https://github.com/containerd/nerdctl/issues/215#issuecomment-853203554 @ChristianCiach 
> Bonus points for automatically picking up a `.env` file in the same folder as the docker-compose.yaml, just as docker-compose does.

One important catch, not sure if bug or spec, but `docker-compose` looks for `.env` file in the **current working directory**, not near docker-compose.yaml file. Caused so much confusion, because invoking `docker-compose up` etc. inside a subfolder partly works, but absence of `.env` file in CWD is silently causing difficult to debug problems, etc. (did not try with `docker compose` (docker's sub-command `compose`))

What would we the correct stance? Replicate the behavior exactly as docker-compose does? or have an opinionated stance, and "fix" the behavior when implementing ?

**Comment by AkihiroSuda** [comment]
We should always emulate docker-compose even when its behavior looks weird.

**Comment by ChristianCiach** [comment]
Please have a look at the recent release notes of docker-compose: https://github.com/docker/compose/releases/tag/1.28.6

> Make `--env-file` relative to the current working directory and error out for invalid paths. Environment file paths set
with `--env-file` are relative to the current working directory while the default `.env` file is located in the project
directory which by default is the base directory of the Compose file.

**Comment by fahedouch** [comment]
hello guys, it seems that the compose spec handles docker-compose 1.28.6 features as mentionned @AkihiroSuda  here https://github.com/containerd/nerdctl/issues/252#issuecomment-861191569 . I take this ticket

**Comment by AkihiroSuda** [comment]
Should have been solved in https://github.com/containerd/nerdctl/pull/305

Thanks @fahedouch
