### ISSUE TITLE
Replace logrus with `github.com/containerd/log`

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#2523]
Direct dependencies on `github.com/sirupsen/logrus` and `github.com/containerd/containerd/log` have to be replaced with https://github.com/containerd/log

**Comment by TinaMor** [comment]
@AkihiroSuda, I'd like to take up this task since it's marked as a good first issue.

**Comment by djdongjin** [comment]
@TinaMor please go ahead :)
