### ISSUE TITLE
Conflicts arise when multiple containers use -p :xxx to automatically assign ports

### ISSUE THREAD

**Issue by tces1** [containerd/nerdctl#2537]
### Description

Conflicts arise when multiple containers use -p :xxx to automatically assign ports.

### Steps to reproduce the issue

1. sudo nerdctl run -p :80 -p 90 -d nginx
2. sudo nerdctl run -p :80 -p 90 -d nginx
3. sudo nerdctl ps -a

### Describe the results you received and expected
v1.6.0:
26ffa8515b7a    docker.io/library/nginx:latest    "/docker-entrypoint.…"    22 seconds ago    Up        **0.0.0.0:49154**->80/tcp, 0.0.0.0:49155->90/tcp    nginx-26ffa
6caea51dbc93    docker.io/library/nginx:latest    "/docker-entrypoint.…"    29 seconds ago    Up        0.0.0.0:49153->80/tcp, **0.0.0.0:49154**->90/tcp    nginx-6caea

expected:
26ffa8515b7a    docker.io/library/nginx:latest    "/docker-entrypoint.…"    22 seconds ago    Up        0.0.0.0:49155->80/tcp, 0.0.0.0:49156->90/tcp    nginx-26ffa
6caea51dbc93    docker.io/library/nginx:latest    "/docker-entrypoint.…"    29 seconds ago    Up        0.0.0.0:49153->80/tcp, 0.0.0.0:49154->90/tcp    nginx-6caea

### What version of nerdctl are you using?

Client:
 Version:	v1.6.0
 OS/Arch:	linux/amd64
 Git commit:	5f39d76139344b8aac6fd03cbe0fa2fd50f89929
 buildctl:
  Version:

Server:
 containerd:
  Version:	v1.6.10
  GitCommit:	770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:	1.1.4
  GitCommit:	v1.1.4-0-g5fd4c4d1

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

Client:
 Version:	v1.6.0
 OS/Arch:	linux/amd64
 Git commit:	5f39d76139344b8aac6fd03cbe0fa2fd50f89929
 buildctl:
  Version:

Server:
 containerd:
  Version:	v1.6.10
  GitCommit:	770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:	1.1.4
  GitCommit:	v1.1.4-0-g5fd4c4d1
h3chen@host-192-168-0-22:~$ sudo nerdctl info
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v1.6.10
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: aufs native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-48-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 54.94GiB
 Name: host-192-168-0-22
 ID: 57ea4457-5d76-4df9-848c-3ed458b284bf

WARNING: No swap limit support

**Comment by AkihiroSuda** [comment]
Fixed in #2539
