### ISSUE TITLE
Multiple networks support

### ISSUE THREAD

**Issue by TheDiveO** [containerd/nerdctl#254]
At this time, nerdctl supports only specifying a single network for a composer project. I suspect that this already satisfies quite an amount of existing and future composer projects. Yet at least from what I see (that might be a narrow domain-specific view, or might not) there are also existing real-world composer projects that use multiple networks (usually using the bridge driver) to separate project-internal inter-service communication from front-facing services, where the front-facing services are not directly exposed on host ports but instead connected to a reverse proxy network -- or networks, depending on how much service network separation is demanded (a topic surely eligible for lengthy discussions *snicker*).

Please support multiple networks within the same composer project as well as sharing (bridge) networks across multiple composer projects. For the latter, one way to use them in deployment is to specify the same network in multiple projects, all with default and/or identical configuration settings (such as "internal"): composer today then takes a on-demand stance and creates the corresponding network the first time a project gets deployed defining this network. All projects deployed later will just reuse the already existing network, so no complaining in this situation.

**Comment by AkihiroSuda** [comment]
Multi-network compose is already supported in the master branch: https://github.com/containerd/nerdctl/pull/189

Will be included in nerdctl v0.9.0 (in a few days).

**Comment by AkihiroSuda** [comment]
Released v0.9.0 https://github.com/containerd/nerdctl/releases/tag/v0.9.0
