### ISSUE TITLE
Support labels for networks and volumes

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#258]
### Network labels

Should be stored as `NerdctlLabels` field, which will appear next to `NerdctlID` field
https://github.com/containerd/nerdctl/blob/3b63cac3a713987790479206b7ebb1865caec50d/pkg/netutil/netutil_linux.go#L32

### Volume labels
Should be stored as a JSON file like `/var/lib/nerdctl/volumes/default/foo/volume.json`

**Comment by fahedouch** [comment]
I take this ticket.

**Comment by AkihiroSuda** [comment]
Thanks

**Comment by AkihiroSuda** [comment]
Implemented in #274, thanks @fahedouch
