### ISSUE TITLE
add-host parameter not valid

### ISSUE THREAD

**Issue by hans511002** [containerd/nerdctl#2591]
### Description

nerdctl run -d --add-host=node01:172.16.148.76 --add-host=node02:172.16.148.77 --add-host=node03:172.16.148.78 --add-host=node04:172.16.148.79 XXX
![image](https://github.com/containerd/nerdctl/assets/6268058/abea5143-a3a2-4d6a-b0a3-405dfdc0d250)
add-host not added in container /etc/hosts
same add-host param run container , first container in nerdctl config file have it. but  container same not . all nerdctl config(meta.json) right. 

### Steps to reproduce the issue

1. run a contianer by nerdctl  width -d(--detach)  
2.check nerdctl config file(hosts,meta.json)
3.in contianer, check /etc/hosts

### Describe the results you received and expected

add-host params write to container /etc/hosts

### What version of nerdctl are you using?

contianerd-1.6.24 nerdctl 1.6.2

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Others

### Host information

centos7,

**Comment by yankay** [comment]
link to https://github.com/moby/moby/issues/22853
