### ISSUE TITLE
`nerdctl ps -a --filter label=io.x-k8s.kind.cluster --format '{{.Label "io.x-k8s.kind.cluster"}}'` behaviour is inconsistent with docker

### ISSUE THREAD

**Issue by yankay** [containerd/nerdctl#2598]
### Description

The docker ps --format is inconsistent with docker and fail with `{{.Label "io.x-k8s.kind.cluster"}}`

### Steps to reproduce the issue

1. root@kay201:~# nerdctl ps -a --filter label=io.x-k8s.kind.cluster --format '{{.Label "io.x-k8s.kind.cluster"}}'

FATA[0000] template: :1:2: executing "" at <.Label>: can't evaluate field Label in type container.ListItem

### Describe the results you received and expected

root@kay200:~# docker ps -a --filter label=io.x-k8s.kind.cluster --format '{{.Label "io.x-k8s.kind.cluster"}}'
kind
kind
kind

### What version of nerdctl are you using?

 nerdctl version
Client:
 Version:       v1.6.2-29-gcaea0f91.m
 OS/Arch:       linux/amd64
 Git commit:    caea0f9196edcb4e9d1cfb1d2803e867cb1115dd.m
 buildctl:
  Version:      v0.12.1
  GitCommit:    bb857a0d49f45aa0ce9cd554b78d4075553e20f9

Server:
 containerd:
  Version:      v1.7.1
  GitCommit:    1677a17964311325ed1c31e2c0a3589ce6d5c30d
 runc:
  Version:      1.1.7
  GitCommit:    v1.1.7-0-g860f061b

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by AkihiroSuda** [comment]
PR
- #2619
