### ISSUE TITLE
Compose tests: remove DockerIncompatible()

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#2622]
https://github.com/search?q=repo%3Acontainerd%2Fnerdctl%20DockerIncompatible&type=code

A lot of compose tests are marked as `DockerIncompatible()` because the CI was previously using Docker Compose v1, but most (not all) of them should be now compatible with Docker Compose v2.

**Comment by suyanhanx** [comment]
I want to have a try on this, please assign it to me.
