### ISSUE TITLE
Fix systeminfo sort bugs.

### ISSUE THREAD

**Issue by yanggangtony** [containerd/nerdctl#2656]
### Description

Fix systeminfo sort bugs.

### Steps to reproduce the issue

1. nerdctlsystem info --mode native
2. not sort anyway

### Describe the results you received and expected

Before is:
![image](https://github.com/containerd/nerdctl/assets/12080746/f78c8dfd-4029-41f3-be2b-f0338f75d968)

After is:
![image](https://github.com/containerd/nerdctl/assets/12080746/1ca90337-4ffd-41fc-988e-a36bfda60efd)

### What version of nerdctl are you using?

latest.

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by AkihiroSuda** [comment]
Fixed in #2655

**Comment by yanggangtony** [comment]
Pr 2655 has fix the sort problem .
