### ISSUE TITLE
Building with multiple tags only updates the first tag

### ISSUE THREAD

**Issue by weikequ** [containerd/nerdctl#2678]
### Description

First seen here: https://github.com/runfinch/finch/issues/707.

When running build while specifying multiple tags for the container, only the first tag is updated if the tags already exist.

### Steps to reproduce the issue

1. 
```bash 
echo 'FROM busybox
CMD ["echo", "1"]
' > Dockerfile
```

2. 
```bash
sudo nerdctl build . -t test:tag1 -t test:tag2 -q
```
3. 
```bash
sudo nerdctl run test:tag1
# 1
```
4. 
```bash
sudo nerdctl run test:tag2
# 1
```
5. 
```bash
echo 'FROM busybox
CMD ["echo", "2"]
' > Dockerfile
```
6. 
```bash
sudo nerdctl build . -t test:tag1 -t test:tag2 -q
```
7.
```bash
sudo nerdctl run test:tag1
# 2
```

8.
```bash
sudo nerdctl run test:tag2
# 1 (but should be 2)
```

### Describe the results you received and expected

See steps above.

### What version of nerdctl are you using?

1.7.1

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by weikequ** [comment]
Seems like this is the issue in the code. Does anyone have any context on why we decided to skip images that already exist if it's not the first image? Related/caused by [this conversation](https://github.com/containerd/nerdctl/pull/1174/files#r911533198).

```golang
if len(tags) > 1 {
...
		for _, targetRef := range tags[1:] {
			image.Name = targetRef
			if _, err := imageService.Create(ctx, image); err != nil {
				// if already exists; skip.
				if errors.Is(err, errdefs.ErrAlreadyExists) {
					continue
...
```
From https://github.com/containerd/nerdctl/blob/d993af567047c6c9a6efe9d06e451814e235c333/pkg/cmd/builder/build.go#L99

**Comment by AkihiroSuda** [comment]
Cc @manugupt1

**Comment by manugupt1** [comment]
I will look at this sometime this month and try to fix it. AFAIR, I did not think of this case.

**Comment by manugupt1** [comment]
This fixed. Closing.
