### ISSUE TITLE
/etc/resolv.conf and /etc/hosts is readonly in container when using --network=host

### ISSUE THREAD

**Issue by shilaidun** [containerd/nerdctl#2685]
### Description

/etc/resolv.conf and /etc/hosts is readonly in container when using --network=host

it shows `bash: /etc/hosts:Read-only file system`

### Steps to reproduce the issue

1.nerdctl run --network=host -v /etc/resolv.conf:/etc/resolv.conf -v /etc/hosts:/etc/hosts --privileged=true images:v1.0.0 --name=test
2.nerdctl exec -it test bash
3.echo "" >> /etc/hosts

### Describe the results you received and expected

above

### What version of nerdctl are you using?

1.7.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by xyt-xuyang** [comment]
+1

**Comment by yuhaoJustGo** [comment]
so good
