### ISSUE TITLE
Default HOSTNAME environment variable not set in nerdctl compose

### ISSUE THREAD

**Issue by simonebenati** [containerd/nerdctl#2693]
### Description

Hello,

When running nerdctl compose up of a compose file my container doesn't have the default HOSTNAME=<containerd id> env variable that is set by default.
Docker compose behaviour is, on the other hand spinning up the container with the HOSTNAME env variable set to the container ID.
Shouldn't  nerdctl replicate this behavior?

### Steps to reproduce the issue

1. create a compose file
2. run nerdctl compose and also docker compose of the same file
3. exec into the container and type 'printenv' or 'env' and you will see that there is no HOSTNAME env variable in nerdctl, whereas in docker compose there is.

### Describe the results you received and expected

I expect to have on both containers an environment variable "HOSTNAME", the received is only in docker compose there is

### What version of nerdctl are you using?

Version:       v1.7.1
 OS/Arch:       linux/amd64
 Git commit:    4692b3eaafc5dc3a3883d3b1cc0e70a35e3b5d32

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.7.1-k3s1
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs fuse-overlayfs stargz
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-91-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.82GiB
 Name: controller01-terragrunt-a
 ID: 208d58fd-771b-4b96-89d1-cd70f354727d

**Comment by haytok** [comment]
Hi, @AkihiroSuda 

I think the `nerdctl` client creates a container at the following location.
- https://github.com/containerd/nerdctl/blob/main/pkg/cmd/container/create.go#L295

If we add the following to set `HOSTNAME=<container ID>` for the environment variables, it would solve the problem in this issue.
- https://github.com/containerd/nerdctl/blob/main/pkg/cmd/container/create.go#L138C1-L142C40

Let me know your opinion.

**Comment by AkihiroSuda** [comment]
SGTM

**Comment by AkihiroSuda** [comment]
```console
$ nerdctl run -it --rm busybox
/ # env
SHLVL=1
HOME=/root
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
/ # echo $HOSTNAME
5f2f18d9f206
```

`echo $HOSTNAME` seems to already work, even though `HOSTNAME` is not present in `env` 🤔

**Comment by haytok** [comment]
Yes, the result of the `HOSTNAME` from `echo $HOSTNAME` or `hostname` command returns, but it cannot be read from printenv.

**Comment by haytok** [comment]
Yes, the result of `echo $HOSTNAME`, `cat /etc/hostname` or `hostname`, but it cannot be read from printenv. 

```
[haytok@lima-finch nerdctl]$ sudo _output/nerdctl run -it --rm busybox
/ # echo $HOSTNAME
784a61aa8556
/ # cat /etc/hostname
784a61aa8556
/ # hostname
784a61aa8556
```
