### ISSUE TITLE
hostname is always overwritten by container id in container when using --network=host

### ISSUE THREAD

**Issue by shilaidun** [containerd/nerdctl#2694]
### Description

Restart the container every time , `hostname` is always overwritten by container id in container when using --network=host，but the hostname in the container will change at any time, after restarting the container it changes to the container id AGAIN! 

### Steps to reproduce the issue

1.`nerdctl run --network=host -v /etc/resolv.conf:/etc/resolv.conf -v /etc/hosts:/etc/hosts -v /etc/hostname:/etc/hostname --privileged=true images:v1.0.0 --name=test `  
2.`nerdctl exec -it test bash`
3.`hostname` : it shows container id `a7e60e651786`
4.`echo 'myhost' > /etc/hostname && hostname 'myhost'`
5.restart the container 
6.`nerdctl exec -it test bash`
7.`hostname`: it shows container id `a7e60e651786`  AGAIN!  not named 'myhost'

### Describe the results you received and expected

hostname :  it shows `myhost` 

### What version of nerdctl are you using?

1.7.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment]
1. Restarting the container will reset the hostname as well with Docker, so, it is unlikely we would change the behavior of nerdctl.
2. the hostname in network=host should be by default the hostname of the host (and not the container id) - this part is definitely a bug
3. if you just want to override the hostname of a container, why not do `nerdctl run -ti --hostname hostnamelalafoo debian`?

@shilaidun ^
