### ISSUE TITLE
Support Compose Run

### ISSUE THREAD

**Issue by metaskills** [containerd/nerdctl#270]
First, this project is amazing!!!

Feature request. A lot of our Docker projects at Custom Ink leverage `docker-compose run` in various project bin files for local development. This allows us to use the compose file as a way to define a single place for environments, volumes, etc. Is `nerdctl compose run` anywhere in the future?

**Comment by starkmatt** [comment]
Agreed, this will be fantastic if this was added as a feature for Devs who are using the 3Mustketeers pattern

https://3musketeers.io/

**Comment by AkihiroSuda** [comment]
Contribution wanted.

A workaround is to use `nerdctl exec -it PROJECT_SERVICE_N`

**Comment by tragiclifestories** [comment]
Would also love `nerctl compose exec` which I guess would be closely related?

**Comment by ivellios** [comment]
`run` spawns separate container which may be useful when the container won't run before some pre-setup steps are taken explicitly by running some command (like bootstrapping with volumes attached). I know the images should be always run-ready, but there are some corner cases, where run is required and without compose context it will simply not work. `exec` would work only for properly running containers, which may not be the case without bootstrap first. This is edge case, so may not be worth pursuing tho.
