### ISSUE TITLE
Preventing nerdctl from pulling image from remote registry when exist locally

### ISSUE THREAD

**Issue by sanzenwin** [containerd/nerdctl#2739]
### What is the problem you're trying to solve

if an image exist locally, Preventing nerdctl from pulling it from remote registry.
```shell
nerdctl --version
```
nerdctl version 1.7.2

### Describe the solution you'd like

Just skip the pulling operation

**Comment by AkihiroSuda** [comment]
Could you elaborate?

**Comment by apostasie** [comment]
@sanzenwin 

Isn't this implemented with `--pull missing` on run?

```
docker tag debian you/test
docker push you/test
nerdctl run --pull missing you/test cat /etc/issue

docker tag busybox you/test
docker push you/test
nerdctl run --pull missing you/test cat /etc/issue
```

Also `pull missing` is the default behavior IIRC.

**Comment by apostasie** [comment]
@AkihiroSuda 
OP is unresponsive, and unless I am missing something, there is no issue here.
Should this be closed?
