### ISSUE TITLE
`nerdctl build` lacks `--attest`, `--sbom`

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#2745]

**Comment by Tejasker** [comment]
@AkihiroSuda , i see the issue  is a good first issue but no context regarding it.
I am new to open source contributions as well as CNCF landscape, will I be able to contribute to the issue mentioned if yes, can you just navigate me if possible
P.S: just doing my best to open up with people

**Comment by AkihiroSuda** [comment]
This should correspond to:
- https://github.com/docker/buildx/blob/v0.12.1/docs/reference/buildx_build.md#attest
- https://github.com/docker/buildx/blob/v0.12.1/docs/reference/buildx_build.md#sbom

I don't think this is a "good first issue".
