### ISSUE TITLE
failed to create default network

### ISSUE THREAD

**Issue by sacesare** [containerd/nerdctl#2748]
### Description

nerdctl tries to create "default" bridge network , not respecting ` --network` option for `run` command using existing network.

### Steps to reproduce the issue

Prerequisite: run nerdctl command without "default" bridge network.
1. choose some existing custom network from `nerdctl network ls`
2. run with selected network `nerdctl  run --network ...`

### Describe the results you received and expected

expected: sucessfully running container with selected custom network.
received: FATA[0001] failed to verify networking settings: failed to create default network

### What version of nerdctl are you using?

1.7.2

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by AkihiroSuda** [comment]
- Rootless or rootful?
- What's your host OS and version?
- What's your CNI plugins version? You may need a recent version.

**Comment by apostasie** [comment]
@sacesare would you be able to provide the requested info ^?

**Comment by apostasie** [comment]
@AkihiroSuda this is not actionnable without more info. I think we should close this since OP is unresponsive.
