### ISSUE TITLE
Avoid hard-coding 8.8.8.8 , 1.1.1.1

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#275]
https://github.com/containerd/nerdctl/blob/fde3eae7cc21f6b010e683026837cab11d544f9f/cmd/nerdctl/run.go#L112

Currently we are hard-coding 8.8.8.8 and 1.1.1.1 as the DNS, but we should propagate the DNS configuration from the host.

Note that parsing /etc/resolv.conf on the host isn't enough, as it may point to 127.0.0.53 which is not accessible from containers.

### Rootless

We can just use slirp4netns built-in DNS

```console
$ rootlessctl --socket $XDG_RUNTIME_DIR/containerd-rootless/api.sock info --json | jq .networkDriver.dns
[
  "10.0.2.3"
]
```

### Rootful

Parse `/run/systemd/resolve/resolv.conf`? Call some systemd API?

**Comment by mengxifl** [comment]
Thanks to the developers, today I can't modify the dns of the container under construction to download particularly slow, I hope to add an interface that can modify the dns when building images

**Comment by dharmab** [comment]
> Note that parsing /etc/resolv.conf on the host isn't enough, as it may point to 127.0.0.53 which is not accessible from containers.

Docker has a special case behavior for this where it looks at `/run/systemd/resolve/resolv.conf`. All other 127.0.0.1/8 resolvers are ignored. If no valid resolvers remain, it falls back on a public DNS service.

**Comment by hypnoce** [comment]
Docker does this inside the daemon that is guaranteed to be executed on the same machine as the container. On the other hand, nerdctl is not guaranteed to run on the same host. I see 2 options : 

- add an option `--dns=host` to make nerdctl lookup the DNS like docker does on the host it runs. The user must guarantee that the DNS nerdctl will resolve is accessible from the host containerd runs on.
- Change containerd to have the same behaviour as dockerd (not sure how feasible it is).

**Comment by gregorso** [comment]
In docker build you have only the option to --add-host=DNS:IP but this is also missing here right now.
The option --dns=host works in docker only for run.
I definitely need one of the options, otherwise i'm not able to build my images with nerdctl

**Comment by paleozogt** [comment]
Could `--dns=host` be the default?

**Comment by hypnoce** [comment]
Note that nerdctl build uses buildkit under the hood, thus uses buildkit strategy for dns (same as docker). AFAIK, it takes the host DNS and is able to resolve my company's private dns.
