### ISSUE TITLE
Respect containerd default runtime?

### ISSUE THREAD

**Issue by Rapiz1** [containerd/nerdctl#277]
I've set kata as the default runtime on my machine, by modifying `/etc/containerd/config.toml`. [Here is an configuration example](https://github.com/Rapiz1/kata-containers/blob/patch-1/docs/install/container-manager/containerd/containerd-install.md)
`ctr` respect that and a container without further specification run under kata.
However, `nerdctl` seems to still use `runc`.

**Comment by AkihiroSuda** [comment]
Nerdctl does not use CRI, so CRI config is discarded.
