### ISSUE TITLE
Does `nerdctl restart` have unstable issues

### ISSUE THREAD

**Issue by shilaidun** [containerd/nerdctl#2793]
### Description

After my machine unexpectedly restarted, the containers were all in a `Created` status, and containerd reported an error log: "no running task found: task 6ad08d6d5f8907df1fd555cc", after that `nerdctl restart 6ad08d6d5f89` it shows 
`FATA[0000] 1 errors:
no running task found: task 6ad08d6d5f8907df1fd555cc7ebd015291f1964e4c8b493fecd0fab9aa3d9541 not found: not found`,
but when I continue to `nerdctl start 6ad08d6d5f89`, it works, and then the container becomes in an `Up` status

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

`nerdctl restart` can work

### What version of nerdctl are you using?

1.7.2

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment]
@fahedouch @shilaidun shall we close this?

**Comment by apostasie** [comment]
@AkihiroSuda should this be closed?
