### ISSUE TITLE
Support `--abort-on-container-exit` for nerdctl compose up.

### ISSUE THREAD

**Issue by austinvazquez** [containerd/nerdctl#2795]
### What is the problem you're trying to solve

I have a use case which uses `docker compose up --abort-on-container-exit` to stop all containers if any container was stopped.

### Describe the solution you'd like

I'd like to have `nerdctl compose up` support `--abort-on-container-exit` flag.

### Additional context

Use case is https://github.com/runfinch/finch/issues/572

**Comment by alegrey91** [comment]
@austinvazquez if you agree I'd like to take care of this issue

**Comment by alegrey91** [comment]
It was a pleasure @austinvazquez.
Hope this new flag could be helpful for your needs!
