### ISSUE TITLE
Support `--compress` on build command.

### ISSUE THREAD

**Issue by austinvazquez** [containerd/nerdctl#2801]
### What is the problem you're trying to solve

I have a use case which uses `docker build --compress` to compress the build context using gzip.

### Describe the solution you'd like

I'd like to have `nerdctl build` support `--compress` flag.

### Additional context

Use case is https://github.com/runfinch/finch/issues/571

**Comment by yankay** [comment]
HI @austinvazquez 

The `nerdctl` uses `--local=context=<BuildContext>` in buildkit to build image.
But the buildkit has no args of compress context.

The compression of build context is useful to build remotely.
I need clarification on how to complete the feature and whether the feature is reasonable.

**Comment by austinvazquez** [comment]
Hi @yankay apologies missed the notification on this. After further research, per [comment](https://github.com/docker/compose/issues/7439#issuecomment-863005798) it sounds like `--compress` option was available on compose v1 only as it predated buildkit which uses compressed streams by design.

So makes sense to close this as not required. I can push my use case to update the workflow to not use this flag as it is no longer needed on modern container stacks. Thanks for taking a look!
