### ISSUE TITLE
Socks5 proxy support ?

### ISSUE THREAD

**Issue by yipengh** [containerd/nerdctl#282]
Hi there, is there a way to pull images through a socks5 proxy ? Something like what i could do with git: `git config --local http.proxy socks5://127.0.0.1:1080` ?

I've tried to set env for containerd service (with daemon-reload and restart) but no luck:
```
[Service]
ExecStartPre=/sbin/modprobe overlay
ExecStart=/usr/local/bin/containerd
Environment="HTTP_PROXY=socks5://127.0.0.1:1080"
```

Thank you in advance.

**Comment by AkihiroSuda** [comment]
I haven't tried proxy, but proxy env would need to be set for `nerdctl`, not for `containerd`, as pull operations happens on the client side.

**Comment by yipengh** [comment]
> I haven't tried proxy, but proxy env would need to be set for `nerdctl`, not for `containerd`, as pull operations happens on the client side.

Thanks, it make sense.

I've set env vars on client side and yes it works perfectly.

Thank you.

**Comment by jjahg520** [comment]
hello, i want use proxy for  nerdctl , can you tell me  how  do you set   env vars on client side ?
