### ISSUE TITLE
Support multiple build contexts

### ISSUE THREAD

**Issue by mharwani** [containerd/nerdctl#2835]
### What is the problem you're trying to solve

Docker build supports multiple contexts with `--build-context` flag to build complex projects. This allows you to build a Dockerfile using multiple local directories. https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/

Similar issue in Finch: https://github.com/runfinch/finch/issues/821

### Describe the solution you'd like

Add a `--build-context` flag to `nerdctl build` command.

**Comment by jmpargana** [comment]
Hey! I'm looking forward to start contributing to `containerd` projects. Could I get started with this one? (I'm already investigating the changes needed in the code base)

**Comment by austinvazquez** [comment]
@mharwani, can this issue be closed with the implementation that was added in #2835?
