### ISSUE TITLE
container not listening on defined port

### ISSUE THREAD

**Issue by andreassteiner97** [containerd/nerdctl#285]
**nerdctl version:** 

![image](https://user-images.githubusercontent.com/59861665/124903377-3171a100-dfe4-11eb-94b2-d5786fab024b.png)

**running containers:** 

![image](https://user-images.githubusercontent.com/59861665/124903444-43ebda80-dfe4-11eb-9128-0124d4fd9549.png)

**nerctl inspect SRV-LZ-MAPCACHE:**

![image](https://user-images.githubusercontent.com/59861665/124903552-5c5bf500-dfe4-11eb-96a7-7990644f5e18.png)

**nerdctl network ls**

![image](https://user-images.githubusercontent.com/59861665/124903719-87dedf80-dfe4-11eb-973a-8f516fe45a2f.png)

**netstat -pltn**

![image](https://user-images.githubusercontent.com/59861665/124903664-772e6980-dfe4-11eb-93e6-6a41ca8ba0c8.png)

as you can see the container does not listen on the defined port 8686

**Comment by AkihiroSuda** [comment]
- Please make sure CNI portmap plugin is installed
- Disabling firewalld may work
- Rootless mode may work, too

**Comment by andreassteiner97** [comment]
I installed: 

- nerdctl-full-0.10.0-linux-amd64.tar so "Full (nerdctl-full-0.10.0-linux-amd64.tar.gz): Includes dependencies such as containerd, runc, and CNI"
- firewalld is disabled: 
![image](https://user-images.githubusercontent.com/59861665/124911776-7221e800-dfed-11eb-8657-6cad1d905234.png)
- have to do it with user root or sudo..

**Comment by AkihiroSuda** [comment]
It seems that port numbers do not appear in `netstat -pltn`.

Does `sudo nerdctl run -d --name nginx -p 8080:80 nginx:alpine && curl http://localhost:8080`  work?
If it works, the issue is probably on the containerized app, not on nerdctl.

**Comment by andreassteiner97** [comment]
I reinstalled the whole nerdctl package under /usr/bin and not under /usr/local/bin - now I can run nerdctl with sudo ... - now it works.
