### ISSUE TITLE
`nerdctl build -n k8s.io` might not be working

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#2867]
- https://github.com/containerd/nerdctl/discussions/2859

Looks like `nerdctl build -n k8s.io` might not be working, but I didn't confirm yet

**Comment by coderbirju** [comment]
Seems like this issue is already [fixed](https://github.com/containerd/nerdctl/discussions/2859#discussioncomment-8847728)? Maybe we can close this issue.
