### ISSUE TITLE
How to offer a limited authority for non-root clients to manage the container created by a root user.

### ISSUE THREAD

**Issue by zibinpan** [containerd/nerdctl#2919]
### What is the problem you're trying to solve

How to offer a limited authority for non-root client to manage the container created by root user.

Specifically, as a root user, I want other user to view the containers I created, making them able to run code like `nerdctl container ls` and `nerdctl inspect` to prove that my container is authentic. 

Besides, I don't want them to be able to remove my container. 

Moreover, other users should be able to enter the container I created in non-root mode.

### Describe the solution you'd like

I want to share my container with others, but limit their authority.

**Comment by fahedouch** [comment]
> I want to share my container with others, but limit their authority.

we don't provide this kind of authorization layer in nerdctl, I think you need an interface in front of nerdctl  ( based authorization cli ) that point to nerdctl and enforce this kind of authorization

BTW, if you want to provide full root privileges for non-root user you can `SETUID` to execute the nerdctl as owner (root)

**Comment by zibinpan** [comment]
> > I want to share my container with others, but limit their authority.
> 
> we don't provide this kind of authorization layer in nerdctl, I think you need an interface in front of nerdctl ( based authorization cli ) that point to nerdctl and enforce this kind of authorization
> 
> BTW, if you want to provide full root privileges for non-root user you can `SETUID` to execute the nerdctl as owner (root)

That's great! Thank you so much.
