### ISSUE TITLE
nerdctl container inspect can't show Mounts of container which is created by CRI or ctr

### ISSUE THREAD

**Issue by zjumoon01** [containerd/nerdctl#2934]
### What is the problem you're trying to solve

Containers are created by CRI or ctr with bind mounts.
`nerdctl inspect <container>` shows Mounts  is null.

> #nerdctl inspect 0298a4 | grep Mounts
        "Mounts": null,
0298a4  is container ID which is created by CRI

However, `nerdctl inspect --mode native 0298a4` can show bind mounts which are actually in container OCI spec.

https://github.com/containerd/nerdctl/blob/main/pkg/inspecttypes/dockercompat/dockercompat.go#L251
It only shows mounts from label `nerdctl/mounts` .
In other words, `nerdctl inspect` only shows mounts of containers which are created by itself.

### Describe the solution you'd like

I'm not sure the result is by design or we can do some improvements.

My proposal:
1. inspect with dockercompat mode support showing container mounts both from CRI/ctr and nerdctl.
2. "nerdctl/mounts" in label has higher priority.
3. Only mounts in "bind" type from native are converted.  Native container shows all types of mounts, such as tmpfs, proc, sysfs.
4. ResolvConfPath and HostnamePath have the same issue, that should be also taken into consideration

**Comment by AkihiroSuda** [comment]
> My proposal:

SGTM
