### ISSUE TITLE
[Windows] fatal "no match for platform in manifest: not found"

### ISSUE THREAD

**Issue by gsevla** [containerd/nerdctl#2938]
### Description

I have just installed containerd and nerdctl on windows so I'll run postgres to test but give the error:
`time="2024-04-14T18:43:11-03:00" level=fatal msg="no match for platform in manifest: not found"`

### Steps to reproduce the issue

1. Installed containerd by following https://github.com/containerd/containerd/blob/main/docs/getting-started.md#installing-containerd-on-windows
2. Downloaded nerdctl.exe and put it side by side with containerd.exe
3. Tried to run nerdctl run --name postgres -e POSTGRES_PASSWORD=password -d postgres

### Describe the results you received and expected

I expected to start a postgres container running.

### What version of nerdctl are you using?

```
time="2024-04-14T18:54:02-03:00" level=warning msg="unable to determine buildctl version: exec: \"buildctl\": executable file not found in %PATH%"
time="2024-04-14T18:54:03-03:00" level=warning msg="unable to determine runc version: exec: \"runc\": executable file not found in %PATH%"
Client:
 Version:       v1.7.5
 OS/Arch:       windows/amd64
 Git commit:    cffed372371dcbea3dc9a646ce5a913fc1c09513
 buildctl:
  Version:

Server:
 containerd:
  Version:      v1.7.15
  GitCommit:    926c9586fe4a6236699318391cd44976a98e31f1
 runc:
  Version:
```

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

```
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.7.15
 Storage Driver: windows
 Logging Driver: json-file
 Cgroup Driver:
 Cgroup Version:
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: windows-lcow windows
 Security Options:
 Kernel Version:
 Operating System:
 OSType: windows
 Architecture:
 CPUs: 0
 Total Memory: 0B
 Name: gsevla-desktop
 ID: fa165362-8730-4069-a513-139689eca54e```

**Comment by AkihiroSuda** [comment]
`postgres` on Docker Hub does not seem to have Windows version, so this behavior is expected.
https://hub.docker.com/_/postgres


If you are trying to run Linux containers, you have to run containerd and nerdctl on WSL2
