### ISSUE TITLE
ubuntu24 unavailable (`fork/exec /proc/self/exe: operation not permitted`)

### ISSUE THREAD

**Issue by 6643** [containerd/nerdctl#3063]
### Description

[INFO] Checking RootlessKit functionality
[rootlesskit:parent] error: failed to start the child: fork/exec /proc/self/exe: operation not permitted
[ERROR] RootlessKit failed, see the error messages and https://rootlesscontaine.rs/getting-started/common/ .

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

nerdctl
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): stat /run/user/1000/containerd-rootless: no such file or directory

### What version of nerdctl are you using?

ubuntu24

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by AkihiroSuda** [comment]
What's your RootlessKit version?

**Comment by AkihiroSuda** [comment]
Please try this
```bash
cat <<EOT | sudo tee "/etc/apparmor.d/usr.local.bin.rootlesskit"
abi <abi/4.0>,
include <tunables/global>

/usr/local/bin/rootlesskit flags=(unconfined) {
  userns,

  # Site-specific additions and overrides. See local/README for details.
  include if exists <local/usr.local.bin.rootlesskit>
}
EOT
sudo systemctl restart apparmor.service
```

**Comment by AkihiroSuda** [comment]
This is now documented in https://rootlesscontaine.rs/getting-started/common/apparmor/

**Comment by 6643** [comment]
@AkihiroSuda 

thank you
