### ISSUE TITLE
Review the status of the current maintainers

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#3066]
See: https://github.com/containerd/project/blob/main/GOVERNANCE.md#handling-inactive-maintainers

@containerd/nerdctl-maintainers : If you are willing to stay as a maintainer (https://github.com/containerd/nerdctl/blob/main/MAINTAINERS), please ack in this issue. 🙏 

Committers:
- [x] @ktock 
- [x] @fahedouch 
- [x] @Zheaoli
- @junnplus : Leaving #3112

Reviewers:
- [x] @jsturtevant 
- @yuchanns : Leaving #3067
- [x] @manugupt1 
- [x] @djdongjin  : Promoted to Committer #3065
- [x] @yankay : Promoted to Committer #3064

**Comment by yankay** [comment]
support

**Comment by fahedouch** [comment]
Yes 🙏

**Comment by yuchanns** [comment]
I'm leaving.

I'd like to contribute more in my free time in the future when possible.
Given my recent concentration, I may still be inactive for a while.

Starting my open-source journey from nerdctl is a huge honor. Our community has been instrumental in mentoring me and it's truly invaluable to me. Thank you!

**Comment by AkihiroSuda** [comment]
> I'm leaving.
> 
> I'd like to contribute more in my free time in the future when possible. Given my recent concentration, I may still be inactive for a while.
> 
> Starting my open-source journey from nerdctl is a huge honor. Our community has been instrumental in mentoring me and it's truly invaluable to me. Thank you!

@yuchanns Thank you for you all contributions so far, and we hope that you eventually come back again! 🙇‍♂️ 
- #3067

**Comment by djdongjin** [comment]
Yes 🙏

**Comment by jsturtevant** [comment]
I haven't been super active except when related to Windows. I am fine either way and happy to continue to contribute reviews for on things related to Windows whether formally or informally.   Thank you for the support you've given!

**Comment by manugupt1** [comment]
I would like to try until the year to get contributions in, until then I would like to be present.

**Comment by AkihiroSuda** [comment]
Ping @junnplus 🙂

**Comment by junnplus** [comment]
Sorry for the late response. I'm leaving and will no longer be a maintainer.
It has been a pleasure contributing to this project and it has helped me grow. I wish the team all the best moving forward.

**Comment by AkihiroSuda** [comment]
@junnplus 
Thank you for you all contributions so far, and we hope that you eventually come back again! 🙇‍♂️

- #3112
