### ISSUE TITLE
`networks` do not appear to support --namespace

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3095]
### Description

@AkihiroSuda is there a reason we do not support namespaces for networks?
Or is this just TBD?

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by AkihiroSuda** [comment]
This is because CNI has no concept of namespaces

**Comment by apostasie** [comment]
Fixed by #3096
