### ISSUE TITLE
Expired PGP key

### ISSUE THREAD

**Issue by rohankrishnadev** [containerd/nerdctl#3148]
### Description

The PGP key used to sign the archive has expired. 

### Steps to reproduce the issue

1. wget https://github.com/containerd/nerdctl/releases/download/v1.7.6/SHA256SUMS.asc
2. wget https://github.com/containerd/nerdctl/releases/download/v1.7.6/SHA256SUMS
3. wget https://github.com/containerd/nerdctl/releases/download/v1.7.6/nerdctl-full-1.7.6-linux-amd64.tar.gz
4. gpg2 -v --verify SHA256SUMS.asc SHA256SUMS
5. gpg2 --recv-keys --verbose C020EA876CE4E06C7AB95AEF49524C6F9F638F1A

I get:
`gpg: Note: signature key 49524C6F9F638F1A expired Thu Jul 27 16:10:23 2023 AEST`

Running `gpg2 --verify SHA256SUMS.asc SHA256SUMS` returns the following:
```
gpg: Signature made Tue Apr 30 16:39:27 2024 AEST
gpg:                using RSA key C020EA876CE4E06C7AB95AEF49524C6F9F638F1A
gpg: Good signature from "Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>" [expired]
gpg:                 aka "Akihiro Suda <suda.kyoto@gmail.com>" [expired]
gpg: Note: This key has expired!
Primary key fingerprint: C020 EA87 6CE4 E06C 7AB9  5AEF 4952 4C6F 9F63 8F1A
```

### Describe the results you received and expected

PGP key needs to be updated

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

Not applicable

**Comment by AkihiroSuda** [comment]
Works for me 🤔 
```console
$ gpg -v --verify SHA256SUMS.asc SHA256SUMS
gpg: enabled compatibility flags:
gpg: Signature made 火  4/30 15:39:27 2024 JST
gpg:                using RSA key C020EA876CE4E06C7AB95AEF49524C6F9F638F1A
gpg: using pgp trust model
gpg: Good signature from "Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>" [ultimate]
gpg:                 aka "Akihiro Suda <suda.kyoto@gmail.com>" [ultimate]
gpg: binary signature, digest algorithm SHA256, key algorithm rsa3072
```

**Comment by AkihiroSuda** [comment]
Refreshed the key on  https://keys.openpgp.org:443
