### ISSUE TITLE
Windows system information missing in "nerdctl info"

### ISSUE THREAD

**Issue by TinaMor** [containerd/nerdctl#3160]
### Description

`nerdctl info` missing some information on Windows OS. The methods for this are currently not implemented

See [infoutil_windows.go#L29-L36C2](https://github.com/containerd/nerdctl/blob/c57ac3c10dbb54ff0cab89192f807e5308578b21/pkg/infoutil/infoutil_windows.go#L29-L36C2)

### Steps to reproduce the issue

On a WIndows environment, run `nerdctl info`.

### Describe the results you received and expected

Actual Results:

![image](https://github.com/containerd/nerdctl/assets/20437227/7dcb611e-bfcd-4ca8-9691-d016364ae93e)

### What version of nerdctl are you using?

nerdctl version: v1.7.17

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment]
@TinaMor out of curiosity, can you do a `docker info` and copy the output here?
Thanks!

**Comment by TinaMor** [comment]
![image](https://github.com/containerd/nerdctl/assets/20437227/13a2aa68-3164-46e2-90a1-4174f0215c58)
