### ISSUE TITLE
Add CI Test for arm64

### ISSUE THREAD

**Issue by yankay** [containerd/nerdctl#3171]
### What is the problem you're trying to solve

The nerdctl support arm64 but lacks the ci test.

supports

### Describe the solution you'd like

Fix the Fail tests OR skip it.

- FAIL: TestRunWithFluentdLogDriver (5.34s)
- FAIL: TestRunWithFluentdLogDriverWithLogOpt (3.76s)
- FAIL: TestMultiPlatformRun (0.90s)
- FAIL: TestMultiPlatformBuildPush (4.10s)
- FAIL: TestMultiPlatformBuildPushNoRun (1.89s)
- FAIL: TestMultiPlatformPullPushAllPlatforms (2.76s)
- FAIL: TestMultiPlatformComposeUpBuild (6.08s)
- FAIL: TestRunWithSystemdTrueEnabled (0.52s)

Support arm64 arch with CI. And Fix the issues:

And then add the arm64 CI.
https://github.com/containerd/nerdctl/pull/3045

### Additional context

[7_ARM64.txt](https://github.com/user-attachments/files/16092914/7_ARM64.txt)

**Comment by apostasie** [comment]
#3045 got merged.
We should close this.

**Comment by apostasie** [comment]
@AkihiroSuda can you close?

**Comment by AkihiroSuda** [comment]
Sure, thanks
