### ISSUE TITLE
info command prints format value when passed other than json

### ISSUE THREAD

**Issue by narharim** [containerd/nerdctl#3195]
### Description

```
$ nerdctl info -f json
{"ID":"a3051cb1-cb0b-4f55-b678-3cfd38e08183","Driver":"overlayfs","Plugins":{"Log":["fluentd","journald","json-file","syslog"],"Storage":["native","overlayfs"]},"MemoryLimit":true,"SwapLimit":true,"CpuCfsPeriod":false,"CpuCfsQuota":false,"CPUShares":false,"CPUSet":false,"PidsLimit":true,.......
```

```
$ nerdctl info -f myname
myname
```

### Steps to reproduce the issue

1. nerdctl info -f myname

### Describe the results you received and expected

Received
myname

expected:
invalid format: %s. Only 'json' is supported

### What version of nerdctl are you using?

v2.0.0-rc.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by xyz-li** [comment]
I don't think this is a bug. Cause the format string is parsed as Go template by nerdctl. 
This flag works the same with docker.
```
  -f, --format string   Format the output using the given Go template, e.g, '{{json .}}'
```

**Comment by AkihiroSuda** [comment]
Let me close this, as this behavior is expected
