### ISSUE TITLE
Incorporate buildctl

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3196]
### What is the problem you're trying to solve

Currently we are shelling out to a buildctl binary, which among other issues puts an additional dependency on the host.

### Describe the solution you'd like

Suggestion is to instead incorporate buildctl client library inside nerdctl, and get rid of the extra shell out / binary requirement

This is going to be quite a bit of work, so, before doing that, I would like to know if this is welcome.

@AkihiroSuda thoughts?

**Comment by AkihiroSuda** [comment]
Sorry, buildctl is shelled out on purpose to avoid the Go mod hell

Thanks anyway for the suggestion

**Comment by apostasie** [comment]
Thanks for the fast answer @AkihiroSuda !

What is the go mod hell in that case?
Too many dependencies? or different dependencies version? Something else?

**Comment by AkihiroSuda** [comment]
> Too many dependencies? or different dependencies version? 

Both

**Comment by AkihiroSuda** [comment]
We should also make some effort to reduce Go dependencies to get nerdctl accepted in apt-get
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030928

> And I know nerdctl continues exploding its build dependencies.
> 
> This is yet another giant monster software.

**Comment by apostasie** [comment]
Yeah, I have read that ticket.

I do not think their assessment is fair, but nevertheless, yeah, we can focus on reducing deps, that is a good goal.
We might also want to reduce the amount of stuff we need for testing on the "host" (for example: I do not see the point in running ipfs through systemd at the same level as nerdctl - while we are ALSO testing it inside a container)

**Comment by apostasie** [comment]
Honestly, we might want to ask this Debian person to clarify what exactly they mean.
nerdctl has about the same number of direct go mod dependencies as containerd, so, they must be talking about something else. Maybe their concerns is about cni-plugins + rootlesskit + ... ?

Without knowing what is their problem, it is going to be hard to make them happy.
