### ISSUE TITLE
why is not OCI type images tar package? when run nerdctl save -o <FILE_NAME> <IMAGE_NAME> 

### ISSUE THREAD

**Issue by sober-wang** [containerd/nerdctl#3202]
### What is the problem you're trying to solve

why is not OCI type images tar package? when run nerdctl save -o <FILE_NAME> <IMAGE_NAME> 

sometime I should used skopeo sync some images to other image registries. the skopeo show error message: 
`FATA[0000] initializing image from source dir:/mnt/d/tmp/sober_fc-check/: json: cannot unmarshal array into Go value of type manifest.Schema1`

I review untar docker save image file and nerdctl save image file, They are not the same.

### Describe the solution you'd like

why is not OCI type images tar package? when run nerdctl save -o <FILE_NAME> <IMAGE_NAME>

**Comment by apostasie** [comment]
Isnt' schema 1  fully deprecated now?

`nerdctl save` will export a proper OCI schema 2 index.

Comparing docker and nerdctl export they are basically doing the same thing:

```
< {"schemaVersion":2,"mediaType":"application/vnd.oci.image.index.v1+json","manifests":[{"mediaType":"application/vnd.oci.image.manifest.v1+json","digest":"sha256:180ef65ccd6d6673c985c149f481e4ae7fe978ec9d164219facbae56bbf9f884","size":1007,"annotations":{"io.containerd.image.name":"docker.io/library/registry:2.7","org.opencontainers.image.ref.name":"2.7"}}]}
\ No newline at end of file
---
> {"schemaVersion":2,"mediaType":"application/vnd.oci.image.index.v1+json","manifests":[{"mediaType":"application/vnd.docker.distribution.manifest.list.v2+json","digest":"sha256:169211e20e2f2d5d115674681eb79d21a217b296b43374b8e39f97fcf866b375","size":776,"annotations":{"containerd.io/distribution.source.docker.io":"library/registry","io.containerd.image.name":"docker.io/library/registry:2.7","org.opencontainers.image.ref.name":"2.7"}}]}

```

Your error message suggests that the tool you are using (skopeo?) fails by trying to read this as a schema 1 image and does not recover from that.

It feels to me like a bug in Skopeo.
