### ISSUE TITLE
Distribution v3 is coming

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3208]
### What is the problem you're trying to solve

With distribution v3 coming (beta 1 just dropped), we should start testing against it to let them know what issues we are facing and to get ready ahead of their releases.

It might also be a good time to split out integration testing into groups so that we get more modular on what we test while avoiding growing the test matrix for the entire suite.

Example: we could have a distribution-latest target that would run *only* login / push / pull tests against distribution master (or latest alpha/beta/RC).

### Describe the solution you'd like

na

### Additional context

na

**Comment by apostasie** [comment]
@AkihiroSuda I can take this - if you want to assign the ticket to me, that is fine.

**Comment by fahedouch** [comment]
looking at the time they took between alpha and beta I don't think beta is close
