### ISSUE TITLE
containerd/accelerated-container-image go.sum hash mismatch

### ISSUE THREAD

**Issue by darktohka** [containerd/nerdctl#3235]
### Description

Attempting to build the main branch results in this error:

verifying github.com/containerd/accelerated-container-image@v1.1.4: checksum mismatch
        downloaded: h1:n5HLcrta/MqsaqRaMigFqog+Y8Xrd3MtFrD37koqbv4=
        go.sum:     h1:9iFHrNRSFnta1A4z6HP1MVD7vH3hEd7jvJv9wnHHJHc=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

### Steps to reproduce the issue

1. Download main branch
2. Build

### Describe the results you received and expected

nerdctl builds successfully.

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by AkihiroSuda** [comment]
Can't repro the issue

```console
$ git rev-parse HEAD
245fcd2f195a0a97b1fec67a93e7ef1c854fb4da

$ go mod verify
all modules verified
```

**Comment by apostasie** [comment]
Can't repro either on a clean module:
```
$ go mod init example.com
$ go get github.com/containerd/accelerated-container-image
$ cat go.sum

github.com/containerd/accelerated-container-image v1.1.4 h1:9iFHrNRSFnta1A4z6HP1MVD7vH3hEd7jvJv9wnHHJHc=
github.com/containerd/accelerated-container-image v1.1.4/go.mod h1:9mpTpL4W4yAsq2giHgo4B7wTFJgE59qCPh7dZTSpGCA=
```

@darktohka

- what version of golang are using?
- are you behind a proxy (go mod proxy like Athens, or otherwise plain http proxy)?

**Comment by apostasie** [comment]
Suggesting we close this.
@darktohka feel free to comment here if this is still an issue - providing the requested details above ^
Thanks!
