### ISSUE TITLE
Support for running containers in any existing network namespace

### ISSUE THREAD

**Issue by dancavallaro** [containerd/nerdctl#3246]
### What is the problem you're trying to solve

I have a software-defined networking use case that involves creating and using Linux network namespaces outside of any container-driven lifecycle, but I would like to run services in containers with access to these namespaces. 

In some cases I might be able to use bridge networking, with a customization to the CNI bridge plugin that lets me override the bridge namespace. But in other cases what I really need is host networking, with the ability to override the netns that the container runs in. 

### Describe the solution you'd like

Ideally I'd like to continue using `nerdctl` for its higher-level orchestration features, but I don't see a way of getting what I want here without a change to nerdctl (i.e., as far as I can tell it's not possible to override the container netns solely via a CNI plugin). 

Would you be open to considering a PR for this feature? Here's a drafty first crack at this in my fork: https://github.com/dancavallaro/nerdctl/commit/102c2d39c221f1d4c118881918719b4e52b853ac. It works in my testing so far, but I'd be more than happy for feedback on anything I might've missed here, or possible alternative approaches.

**Comment by AkihiroSuda** [comment]
> Would you be open to considering a PR for this feature?

Yes, please.
This should be also documented in https://github.com/containerd/nerdctl/blob/main/docs/command-reference.md

**Comment by dancavallaro** [comment]
> > Would you be open to considering a PR for this feature?
> 
> Yes, please. This should be also documented in https://github.com/containerd/nerdctl/blob/main/docs/command-reference.md

Sorry for the delay -- thanks for the response and suggestion. I'll add documentation for the feature and submit a formal PR.

**Comment by dancavallaro** [comment]
Just submitted https://github.com/containerd/nerdctl/pull/3538.
