### ISSUE TITLE
nerdctl pull failed (`unexpected media type text/html`)

### ISSUE THREAD

**Issue by xjdtd** [containerd/nerdctl#3264]
### Description

[root@master01 k8s-jenkins-containerd-nerdctl]# nerdctl login 
WARNING: Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
[root@master01 k8s-jenkins-containerd-nerdctl]# nerdctl -n k8s.io pull jenkins/inbound-agent:latest-jdk17
docker.io/jenkins/inbound-agent:latest-jdk17: resolving      |--------------------------------------| 
elapsed: 3.7 s                                total:   0.0 B (0.0 B/s)                                         
WARN[0003] reference for unknown type: text/html         digest="sha256:ce8679fa7302e60b7ea6d02993d35440588ee0076bdaff1357b938c937abb3d0" mediatype=text/html size=276162
FATA[0003] failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:ce8679fa7302e60b7ea6d02993d35440588ee0076bdaff1357b938c937abb3d0: not found 
[root@master01 k8s-jenkins-containerd-nerdctl]#

[root@master01 k8s-jenkins-containerd-nerdctl]# nerdctl version
Client:
 Version:       v1.7.6
 OS/Arch:       linux/amd64
 Git commit:    845e989f69d25b420ae325fedc8e70186243fd93
 buildctl:
  Version:      v0.13.2
  GitCommit:    2e18d709fefdcc2db20853ee241c75b058189d39

Server:
 containerd:
  Version:      v1.7.16
  GitCommit:    83031836b2cf55637d7abf847b17134c51b38e53
 runc:
  Version:      1.1.12
  GitCommit:    v1.1.12-0-g51d5e946
[root@master01 k8s-jenkins-containerd-nerdctl]# 

but docker pull OK

[root@harbor jenkins]# docker pull jenkins/inbound-agent:latest-jdk17
latest-jdk17: Pulling from jenkins/inbound-agent
f11c1adaa26e: Pull complete 
d3915ffa03dd: Pull complete 
142683d3f557: Pull complete 
a445b84e6446: Pull complete 
55867a3b2a3b: Pull complete 
c10e49e2ae75: Pull complete 
ab94afba5451: Pull complete 
4f4fb700ef54: Pull complete 
7af6470caf99: Pull complete 
2828fce91c7c: Pull complete 
Digest: sha256:be0190aaa9141d1af2d37035ebcd5a98122f661b13f26cd59517f9082e848b0e
Status: Downloaded newer image for jenkins/inbound-agent:latest-jdk17
docker.io/jenkins/inbound-agent:latest-jdk17
[root@harbor jenkins]# 

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

nerdctl pull failed

### What version of nerdctl are you using?

[root@master01 k8s-jenkins-containerd-nerdctl]# nerdctl version
Client:
 Version:       v1.7.6
 OS/Arch:       linux/amd64
 Git commit:    845e989f69d25b420ae325fedc8e70186243fd93
 buildctl:
  Version:      v0.13.2
  GitCommit:    2e18d709fefdcc2db20853ee241c75b058189d39

Server:
 containerd:
  Version:      v1.7.16
  GitCommit:    83031836b2cf55637d7abf847b17134c51b38e53
 runc:
  Version:      1.1.12
  GitCommit:    v1.1.12-0-g51d5e946
[root@master01 k8s-jenkins-containerd-nerdctl]# 

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment]
@xjdtd

1. this is going to be very hard to diagnose without being able to access your registry
2. your `docker pull` command and `nerdctl pull` do not seem to be ran from the same server (root@harbor vs. root@master01) - can you confirm that you get the same result while running `docker pull` on the same server as nerdctl so that we can rule out networking issues on your side?
3. can you try running your nerdctl commands again while using the extra argument `--debug-full`

Thanks

**Comment by apostasie** [comment]
@xjdtd any update on the above? ^

**Comment by apostasie** [comment]
@AkihiroSuda I do not see the point of keeping this open.

O.P. has been unresponsive almost immediately.
There is clearly network fuckery afoot, but I doubt it is a nerdctl issue.
