### ISSUE TITLE
why create the concepts: k8s.io containerd namespace

### ISSUE THREAD

**Issue by xiaods** [containerd/nerdctl#329]
k8s.io containerd namespace is very confuse for me. it's not like kubernetes namespace. why add this feature to nerdctl.

**Comment by fahedouch** [comment]
hello @xiaods,

indeed, it is a k8s namespace, `nerdctl` let you create a kubernetes containers 


```
Namespacing: nerdctl --namespace=<NS> ps . (NOTE: All Kubernetes containers are in the k8s.io containerd namespace regardless to Kubernetes namespaces)
```

**Comment by AkihiroSuda** [comment]
Nerdctl didn't create this concept.

It has been there in containerd itself.
