### ISSUE TITLE
`Validate` identifiers should avoid reserved names on windows 

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3312]
### What is the problem you're trying to solve

https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

"
CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, COM¹, COM², COM³, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9, LPT¹, LPT², and LPT³. Also avoid these names followed immediately by an extension; for example, NUL.txt and NUL.tar.gz are both equivalent to NUL. For more information, see [Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces).
"

### Describe the solution you'd like

Identifiers that are being used on the filesystem should forbid these.
That should be put in a windows version of `Validate` (being reworked in #3279).

Something in the line of:
`^(con|prn|nul|aux|com[1-9]|lpt[1-9])([.].*)?`

### Additional context

Docker seem to enforce these.

**Comment by Shubhranshu153** [comment]
probably we want to add this also to validate function?
i am wondering there might be others regexp in docker too. Can document all the regexp and do a pr.
This week is bit constraint for me but can pick up next week.

**Comment by apostasie** [comment]
Yeah, should definitely go in `validate_windows.go` or something in the line.
A quick recon in Moby may show some more.

**Comment by Shubhranshu153** [comment]
do we want in the same pr or a different pr? would prefer a different pr in the sense adding restrictions to a validation function would mean we need to think about backward compatibility and how to handle that, relaxing on the other hand is simpler in that regard.

**Comment by apostasie** [comment]
> do we want in the same pr or a different pr? would prefer a different pr in the sense adding restrictions to a validation function would mean we need to think about backward compatibility and how to handle that, relaxing on the other hand is simpler in that regard.

Yeah, it is fine in a follow-up PR.

About backward compatibility, I don't think we need to think about it here.
These identifiers would fail on windows regardless (with some cryptic message).
Adding the extra validation (like Moby does) will just safeguard it and provide some reasonable output to the user.
