### ISSUE TITLE
macos installation

### ISSUE THREAD

**Issue by ksaur** [containerd/nerdctl#332]
Hello, I'm trying to install on macos (Intel chip).  From the README, I successfully do:

```
$ brew install lima
$ limactl start
```

But when I try to do `lima nerdctl run -d -p 8080:80 --name nginx:alpine`, I get 
```bash
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
exit status 1
```

I then tried `$ lima ./containerd-rootless-setuptool.sh install`
which of course gives:
```bash
[ERROR] Needs systemd (systemctl --user)
exit status 1
```

I also tried with `sudo`:
```bash
$ sudo lima nerdctl run -d -p 8080:80 --name nginx:alpine
Password:
FATA[0000] must not run as the root
```

Is there a work-around for the above error?  Or some other documentation you can point me to? Thanks!

**Comment by AkihiroSuda** [comment]
Can’t reproduce the error. Did you use non-default template such as Alpine?
What does `lima cat /etc/os-release` show?

**Comment by sah2ed** [comment]
@ksaur 

Please try without sudo.
Oh, and the command you ran has a typo so please run: `lima nerdctl run -d --name nginx -p 127.0.0.1:8080:80 nginx:alpine` and see if it works successfully.

**Comment by ksaur** [comment]
Thanks so much! This (`lima nerdctl run -d --name nginx -p 127.0.0.1:8080:80 nginx:alpine`) worked. 

I think maybe there is a bug in the README?  When I try again with verbatim from the readme (`lima nerdctl run -d -p 8080:80 --name nginx:alpine`), I get a different error than before:  `FATA[0000] image name needs to be specified`.   (I'm not sure what exactly happened before; but I closed my shell and reopened it, so maybe that helped.)

So maybe all this needs is a README update since the name is missing there?  I can submit it as a PR if you'd like?

BTW, since you asked:
```bash
$ lima cat /etc/os-release
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
```
