### ISSUE TITLE
` name "foo" is already used by ID ""`

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#3351]
Looks like the name store may accidentally get stuck in an improper state
```console
$ sudo nerdctl run -it --rm --name=foo alpine
FATA[0000] name "foo" is already used by ID ""

$ sudo nerdctl rm -f foo
ERRO[0000] 1 errors:
no such container: foo

$ sudo nerdctl run -it --rm --name=foo alpine 
FATA[0000] name "foo" is already used by ID ""
```

Probably a recent regression in the main branch.

Workaround: `sudo rm /var/lib/nerdctl/1935db59/names/default/foo`

**Comment by apostasie** [comment]
Likely #2992

This is definitely (still) happening when restarting containers is involved.
It might be time to consider pulling the plug on the namestore...

**Comment by apostasie** [comment]
I have #3357 for a specific case of this - just not sure this is the same.

lmk if you have a repro for yours here.
