### ISSUE TITLE
Possible refactoring: cmd/nerdctl is very crowded?

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3375]
### What is the problem you're trying to solve

The `cmd/nerdctl` folder is very crowded.

I find it hard to reason about, or figure out what depends on what.

This is not a *huge* problem - this falls more into the "developer quality of life" category.

Would we be open to putting that stuff under sub-folders, by category? (container, image, network, volume, system, etc)

### Describe the solution you'd like

na

**Comment by AkihiroSuda** [comment]
> Would we be open to putting that stuff under sub-folders, by category? (container, image, network, volume, system, etc)


IIRC we have tried this before and faced an issue about splitting `*_test.go`

**Comment by AkihiroSuda** [comment]
We can continue the discussion in:
- https://github.com/containerd/nerdctl/issues/1680
