### ISSUE TITLE
`nerdctl build --output "type=oci,dest=-" . > output.tar` does not output to stdout

### ISSUE THREAD

**Issue by MayCXC** [containerd/nerdctl#3386]
### Description

`nerdctl build --output "type=tar,dest=-" . > output.tar` works as expected, the root of the image outputs to stdout, and is then redirected to `output.tar`. This is also the expected behavior of `type=oci`, but this is the actual behavior:

```
$ nerdctl build --output "type=oci,dest=-" . > output.tar
$ cat output.tar
unpacking overlayfs@sha256:3f163869fade0eb290d0a847f8c5fb32b75009d862c59558deb3b21472b8c732 (sha256:3f163869fade0eb290d0a847f8c5fb32b75009d862c59558deb3b21472b8c732)...
Loaded image: overlayfs@sha256:3f163869fade0eb290d0a847f8c5fb32b75009d862c59558deb3b21472b8c732
```

### Steps to reproduce the issue

1. `mkdir output && nerdctl build --output "type=oci,dest=-" . | tar -C output -xvf - && ls output`

### Describe the results you received and expected

```
oci-layout
index.json
...
```

### What version of nerdctl are you using?

1.7.6

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Lima

### Host information

`Linux lima-default 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC aarch64 aarch64 aarch64 GNU/Linux`

**Comment by MayCXC** [comment]
(this is most likely a bug in buildkit)

**Comment by MayCXC** [comment]
in my case, `nerdctl build --output "type=oci,tar=false,dest=./dir` is a workaround because I do not actually need the tar archive. but the behavior of the oci exporter is definitely incorrect.

**Comment by apostasie** [comment]
Pretty sure we are outputting unrelated messages on stdout, so, definitely some bug on our side.

Will look into this a bit later.

Thanks @MayCXC

**Comment by apostasie** [comment]
Looks like in https://github.com/containerd/nerdctl/blob/main/pkg/cmd/builder/build.go#L230 we force loading of the image, regardless of the value of dest.

I am honestly unsure why we would enforce loading on `oci` images indiscriminately.
Even if that is the desirable behavior, we should at least mimick docker behavior and inspect `dest` before making a decision to load: 
```
dest - destination path where tarball will be written. If not specified, the tar will be loaded automatically to the local image store.
```

Does not feel like a buildkit bug to me - but more a nerdctl one.

**Comment by apostasie** [comment]
Note that `nerdctl build --output "type=oci,tar=false,dest=./dir" .; echo $?` actually "fails".
