### ISSUE TITLE
The `nerdctl pull ` will output logs through  the standard error stream.

### ISSUE THREAD

**Issue by cyxinda** [containerd/nerdctl#3395]
### Description

Even when no error occurs, the `nerdctl pull someImage` command will output the result logs through the standard error stream instead of the standard output stream . This can cause confusion.
If I call local nerdctl command by my golang code,I have to get logs through StderrPipe .

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

I hope that if no error occurs, the nerdctl pull command can output logs through the standard output stream

### What version of nerdctl are you using?

cyxinda@oldsix [~] ➜  nerdctl --version                                                                                                                                                           [16:29:56]
nerdctl version 2.0.0-rc.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

cyxinda@oldsix [~] ➜  nerdctl info                                                                                                                                                                [17:03:53]
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v2.0.0-rc.3
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
  rootless
 Kernel Version: 6.8.0-41-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 46.96GiB
 Name: oldsix
 ID: ca3e7d2c-4de1-4e7f-8f44-791f0d59cd75

WARNING: AppArmor profile "nerdctl-default" is not loaded.
         Use 'sudo nerdctl apparmor load' if you prefer to use AppArmor with rootless mode.
         This warning is negligible if you do not intend to use AppArmor.
WARNING: No cpuset support
cyxinda@oldsix [~] ➜

**Comment by apostasie** [comment]
Confirming that docker behavior is different.

```
docker rmi debian; docker pull debian >/dev/nul
nerdctl rmi debian; nerdctl pull debian >/dev/nul
```
