### ISSUE TITLE
[question] run nerdctl as root but without sudo

### ISSUE THREAD

**Issue by shyim** [containerd/nerdctl#341]
Hey,

is it possible to use nerdctl on normal account but with root mode? Like in docker adding the current user to the docker group 🤔

**Comment by tigerinus** [comment]
same question here - any anwser yet?

**Comment by AkihiroSuda** [comment]
> is it possible to use nerdctl on normal account but with root mode? Like in docker adding the current user to the docker group 

No, due to https://github.com/containerd/nerdctl/issues/473#issuecomment-953548961 .

Workaround is `alias nerdctl=sudo nerdctl`, or set SETUID on `nerdctl` binary.
(In the latter case, the nerdctl binary should be placed in `~/bin`, and chmod 700 `~/bin`)

**Comment by AkihiroSuda** [comment]
Added a documentation about this in https://github.com/containerd/nerdctl/blob/master/docs/faq.md#does-nerdctl-have-an-equivalent-of-sudo-usermod--ag-docker-user-

```
mkdir -p $HOME/bin
chmod 700 $HOME/bin
cp /usr/local/bin/nerdctl $HOME/bin
sudo chown root $HOME/bin/nerdctl
sudo chmod +s $HOME/bin/nerdctl
export PATH=$HOME/bin:$PATH
```
