### ISSUE TITLE
Issues related to missing layer (likely caused by https://github.com/containerd/containerd/issues/8973 )

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3425]
### Description

This here is to collect issues that _may_ be caused by https://github.com/containerd/containerd/issues/8973

* #3420
* #827 
* #2588
* #3415
* #2506
* #2327
* #2357

How to solve it is unclear at this point.

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by apostasie** [comment]
Tagging @lingdie who likely has a good understanding of whats going on.

**Comment by apostasie** [comment]
@AkihiroSuda while this is still murky, I feel this is bad enough given the number of issues.
Do you think this could be added to the v2 milestone?

**Comment by apostasie** [comment]
@AkihiroSuda https://github.com/containerd/containerd/issues/8973 is stale, despite pings.

What is your opinion?

- do you think this should be a blocker for containerd v2 release? Or otherwise any chance to get eyeballs on it?
- or should we try harder to work around it here (not sure this is even feasible honestly)?

The suggestion over there ("Changing the default pull behavior should be up to the client") is a bit asinine TBH, as it would have wide ranging impact on performance...

**Comment by apostasie** [comment]
@lingdie your patch was definitely going in the right direction, but I guess if the layers are missing, it will not be enough?

What if we check if there are missing layers, then force a fetch?

Something in the line of:
```
_, _, _, missing, err := images.Check(ctx, client.ContentStore(), im.Target, platform)
if len(missing) > 0 {
    img, err = client.Fetch(ctx, ref, opts...)
}

// unpack the image to snapshotter
cimg := containerd.NewImage(client, img)
if err := cimg.Unpack(ctx, snName); err != nil {
    return emptyDigest, err
}
```

**Comment by apostasie** [comment]
Here is a repro involving tagging:

```
nerdctl rm -f $(nerdctl ps -aq) 2>&1 >/dev/null
nerdctl rmi -f $(nerdctl images -q) 2>&1 >/dev/null
nerdctl image pull busybox 2>&1 >/dev/null
nerdctl run -d busybox 2>&1 >/dev/null
nerdctl image rm -f busybox 2>&1 >/dev/null
nerdctl pull busybox
nerdctl tag busybox myregistry:5000/test
nerdctl push myregistry:5000/test
```

This will fail when we try to convert to a temp single platform image (because we tagged an image with missing layers).

**Comment by AkihiroSuda** [comment]
> a blocker for containerd v2 release

I'd prefer to limit the blockers to:
- regressions in v2
- new features in v2, merged with a wrong design

**Comment by apostasie** [comment]
> > a blocker for containerd v2 release
> 
> I'd prefer to limit the blockers to:
> 
> * regressions in v2
> * new features in v2, merged with a wrong design

Fair enough.

I _might_ have a workable fix in the linked PR.

**Comment by ningmingxiao** [comment]
I find a reason sometimes containerd will skip to save some blobs. @AkihiroSuda  @apostasie 
ref : https://github.com/containerd/containerd/pull/11996
