### ISSUE TITLE
Panic: `not a console`, follow-up to #3297

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3433]
### Description

As outlined in #3297, there are more places that are likely to panic when we do not have a tty.

While the patch in #3300 fixed it for `exec` for a specific use case, clearly `run` can crash in the same circumstances.

Suggestion is to wrap the third party term console library so that it returns an error we can check instead of crashing.

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by alitvak69** [comment]
Do you have any examples of how you wrap?

**Comment by apostasie** [comment]
> Do you have any examples of how you wrap?

Sorry, there is no workaround that I know of.
Suggestion to wrap refers to how to fix the code: you need to search all the calls to `console.Current` and replace them by a call to a new function that will test for said condition.

**Comment by alitvak69** [comment]
Can I provide some additional information to help you fix the issue?   Even if it is impossible to run top inside of the container, at least it shouldn't crash.

**Comment by apostasie** [comment]
> Can I provide some additional information to help you fix the issue? Even if it is impossible to run top inside of the container, at least it shouldn't crash.

Of course.
Thanks!

**Comment by alitvak69** [comment]
What do you want me to do.  Let me know if you want me to run debugging of some sort or test with some different version of nerdctl

**Comment by apostasie** [comment]
> What do you want me to do. Let me know if you want me to run debugging of some sort or test with some different version of nerdctl

Ideally:
- use the latest nerdctl release candidate: https://github.com/containerd/nerdctl/releases/tag/v2.0.0-rc.2
- confirm that the problem still exist with your scenario
- come-up with a as-simple as-possible reproducer - eg: a short shell script that I can run and that shows the issue

Thanks.

**Comment by alitvak69** [comment]
Thank you for your work.  I built and tested new code.  It allows a container to continue.  This said are there any plans to make nerdctl started container from systemd more pseudo-terminal friendly?

**Comment by apostasie** [comment]
@alitvak69 you are welcome!

Roadmap questions should go to @AkihiroSuda or other maintainers.
Then again, there is nothing wrong with just going ahead: open issues / feature requests for what you need and let see what we can do.

Cheers.
