### ISSUE TITLE
Support to ps into nerdctl compose

### ISSUE THREAD

**Issue by joubertredrat** [containerd/nerdctl#347]
Today we have ps option to list containers running about compose into `docker-compose ps` and `docker compose ps` options.

I think is good idea to support this into nerdctl compose too, what you think?

**Comment by joubertredrat** [comment]
Hi guys, a little question. Is possible to develop to this project only in linux? I tested to build here in darwin intel/m1 and in both failed, like example below:

```bash
dev@Devs-MacBook-Pro ~/source/opensource/joubertredrat/nerdctl (feature/compose-ps)> make binaries
GO111MODULE=on CGO_ENABLED=0 GOOS=darwin go build -ldflags "-s -w -X github.com/containerd/nerdctl/pkg/version.Version=v0.11.1-21-gd765477 -X github.com/containerd/nerdctl/pkg/version.Revision=d76547747dcab02f2e3ec91e7ff3a25063092099" -o /Users/dev/source/opensource/joubertredrat/nerdctl/_output/nerdctl github.com/containerd/nerdctl/cmd/nerdctl
package github.com/containerd/nerdctl/cmd/nerdctl
	imports github.com/containerd/nerdctl/pkg/defaults: build constraints exclude all Go files in /Users/dev/source/opensource/joubertredrat/nerdctl/pkg/defaults
package github.com/containerd/nerdctl/cmd/nerdctl
	imports github.com/containerd/nerdctl/pkg/lockutil: build constraints exclude all Go files in /Users/dev/source/opensource/joubertredrat/nerdctl/pkg/lockutil
make: *** [nerdctl] Error 1
```

I'm interested to develop this issue but I have only darwin and wsl2 environments to develop.

**Comment by fahedouch** [comment]
@joubertredrat 
dawrin os is not yet supported

**Comment by joubertredrat** [comment]
Thanks @fahedouch, Im going to do this then

**Comment by abiosoft** [comment]
> @joubertredrat cross-compiling for dawrin os is not yet supported. You should compile the code inside Linux container for the moment to start working on this issue :)

You can actually cross-compile and it works fine.
```sh
GOOS=linux make
# simply copy the binary from `_output/nerdctl` to linux vm/container afterwards
```

**Comment by joubertredrat** [comment]
> You can actually cross-compile and it works fine.

Hi @abiosoft, I tried here, but still not working here, as you can see below

```bash
dev@Devs-MacBook-Pro ~/source/opensource/other/nerdctl (master)> make binaries
GO111MODULE=on CGO_ENABLED=0 GOOS=darwin go build -ldflags "-s -w -X github.com/containerd/nerdctl/pkg/version.Version=v0.12.0 -X github.com/containerd/nerdctl/pkg/version.Revision=aab5de3ae24e7203307cbb030b1114d652f0be01" -o /Users/dev/source/opensource/other/nerdctl/_output/nerdctl github.com/containerd/nerdctl/cmd/nerdctl
package github.com/containerd/nerdctl/cmd/nerdctl
	imports github.com/containerd/nerdctl/pkg/defaults: build constraints exclude all Go files in /Users/dev/source/opensource/other/nerdctl/pkg/defaults
package github.com/containerd/nerdctl/cmd/nerdctl
	imports github.com/containerd/nerdctl/pkg/lockutil: build constraints exclude all Go files in /Users/dev/source/opensource/other/nerdctl/pkg/lockutil
make: *** [nerdctl] Error 1
```

**Comment by abiosoft** [comment]
> ```shell
> dev@Devs-MacBook-Pro ~/source/opensource/other/nerdctl (master)> make binaries
> GO111MODULE=on CGO_ENABLED=0 GOOS=darwin go build -ldflags "-s -w -X github.com/containerd/nerdctl/pkg/version.Version=v0.12.0 -X github.com/containerd/nerdctl/pkg/version.Revision=aab5de3ae24e7203307cbb030b1114d652f0be01" -o /Users/dev/source/opensource/other/nerdctl/_output/nerdctl github.com/containerd/nerdctl/cmd/nerdctl
> package github.com/containerd/nerdctl/cmd/nerdctl
> 	imports github.com/containerd/nerdctl/pkg/defaults: build constraints exclude all Go files in /Users/dev/source/opensource/other/nerdctl/pkg/defaults
> package github.com/containerd/nerdctl/cmd/nerdctl
> 	imports github.com/containerd/nerdctl/pkg/lockutil: build constraints exclude all Go files in /Users/dev/source/opensource/other/nerdctl/pkg/lockutil
> make: *** [nerdctl] Error 1
> ```

@joubertredrat you need to override `GOOS` by specifying it. 
```
GOOS=linux make binaries
```

**Comment by fahedouch** [comment]
@joubertredrat you can use https://github.com/lima-vm/lima too.

**Comment by AkihiroSuda** [comment]
Implemented in https://github.com/containerd/nerdctl/pull/425 , thanks @joubertredrat
