### ISSUE TITLE
`images --filter=non-existent` inconsistent (docker vs. nerdctl)

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3511]
### Description

```
docker images --filter since=non-exists-image; echo $?
Error response from daemon: No such image: non-exists-image:latest
1
```

```
nerdctl images --filter since=non; echo $?
REPOSITORY    TAG    IMAGE ID    CREATED    PLATFORM    SIZE    BLOB SIZE
0
```

This recently got fixed because of a panic - in #3469 - though the tests being currently disabled for Docker made this go under the radar.

Tagging @xyz-li in case you are interested in revisiting. 

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by xyz-li** [comment]
`docker images --filter since=IMAGE_ID` does not consistent with docker too.
