### ISSUE TITLE
Consider removing `ipfs` binary from `nerdctl-full`

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#3527]
Enterprise companies often (blindly) ban installing any software that relates to "P2P".

Removing `ipfs` binary from `nerdctl-full` may help installing nerdctl on those environments.

Users can still opt-in to install `ipfs` from https://github.com/ipfs/kubo .

**Comment by AkihiroSuda** [comment]
cc @ktock

**Comment by ktock** [comment]
SGTM
