### ISSUE TITLE
container version 1.5.7 and  nofile settings is LimitNOFILE=infinity

### ISSUE THREAD

**Issue by sun-11y** [containerd/nerdctl#3582]
container version 1.5.7 and  nofile settings is LimitNOFILE=infinity

when i use nerdctl 1.4.0 exec command like this  nerdctl compose -f ./docker-compose.yml up  --debug-full
and when i run exec -it xxx --ulimit -Hn return 1024

when i use nerdctl 1.7.7 exec command like this  nerdctl compose -f ./docker-compose.yml up  --debug-full  no error and when i run exec -it xxx --ulimit -Hn return 1073741816

Why does this happen? Is the version incompatible？Please help answer

**Comment by apostasie** [comment]
containerd 1.5 has been end-of-life since February 2023.
Also, it is unlikely we would fix anything in nerdctl 1.4...

Is your problem affecting the last version? It is hard to tell. If yes, can you provide an actual example that we can run to reproduce your issue?

**Comment by apostasie** [comment]
@sun-11y where you able to test a supported version?

**Comment by apostasie** [comment]
@AkihiroSuda suggesting we close. Issue is about a long gone version.
