### ISSUE TITLE
[CI BROKEN] [URGENT] Integration test broken for docker

### ISSUE THREAD

**Issue by apostasie** [containerd/nerdctl#3652]
### Description

test-integration-docker-compatibility started failing on master with seemingly no related change around the time of:
https://github.com/containerd/nerdctl/commit/af229a67313733a88cc623e0bc05bda34ec568a3

Failing test is TestBuilder/Debug (`docker builder debug` not recognized as a command).

It seems the trigger for this comes from the updated github action runner base image.

From:
https://github.com/actions/runner-images/blob/ubuntu24/20241016.1/images/ubuntu/Ubuntu2404-Readme.md
to
https://github.com/actions/runner-images/blob/ubuntu24/20241103.1/images/ubuntu/Ubuntu2404-Readme.md

which happened around 11/03 - timeline is consistent.

Specifically in the changelog, Docker-Buildx has been updated from 0.17.1 to 0.18.0, which I _guess_ is the culprit.

@AkihiroSuda I am flying and will be unable to send PRs for a few days.
Could you carry this?

I am not completely sure why or what is going on here, but maybe just
```
index 9cb34d5e..033f70e3 100644
--- a/cmd/nerdctl/builder/builder_builder_test.go
+++ b/cmd/nerdctl/builder/builder_builder_test.go
@@ -71,6 +71,7 @@ CMD ["echo", "nerdctl-test-builder-prune"]`, testutil.CommonImage)
                        },
                        {
                                Description: "Debug",
+                               Env:         map[string]string{"BUILDX_EXPERIMENTAL": "1"},
                                NoParallel:  true,
                                Command: func(data test.Data, helpers test.Helpers) test.TestableCommand {
                                        dockerfile := fmt.Sprintf(`FROM %s
```

might fix it.

### Steps to reproduce the issue

na

### Describe the results you received and expected

na

### What version of nerdctl are you using?

main

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by AkihiroSuda** [comment]
The test was completely broken, even in  buildx v0.17.1.
The error was ignored because the command exited with status 0.

```
$ buildx debug .
Extended build capabilities with BuildKit

Usage:
  ./bin/build/buildx [command]

Available Commands:
  bake        Build from a file
  build       Start a build
  create      Create a new builder instance
  dial-stdio  Proxy current stdio streams to builder instance
  du          Disk usage
  help        Help about any command
  imagetools  Commands to work on images in registry
  inspect     Inspect current builder instance
  ls          List builder instances
  prune       Remove build cache
  rm          Remove one or more builder instances
  stop        Stop builder instance
  use         Set the current builder instance
  version     Show buildx version information

Flags:
      --builder string   Override the configured builder instance
  -D, --debug            Enable debug logging
  -h, --help             help for ./bin/build/buildx

Use "./bin/build/buildx [command] --help" for more information about a command.

Experimental commands and flags are hidden. Set BUILDX_EXPERIMENTAL=1 to show them.

$ echo $?
0

$ BUILDX_EXPERIMENTAL=1 ./bin/build/buildx debug .
ERROR: unknown command "." for "./bin/build/buildx debug"
```
