### ISSUE TITLE
Support user prompt for nerdctl login registry --> like docker does

### ISSUE THREAD

**Issue by tantweiler** [containerd/nerdctl#368]
Hello everyone!

nerdctl requires the --username option to do a login into a registry. Otherwise the following error message pops up:

```
FATA[0000] error: Username is Required
exit status 1
```

 With docker a prompt pops up when the option is not given. Could you implement that in nerdctl as well to make nerdctl more compatible with docker? Otherwise many docker scripts may fail and have to be rewritten.

**Comment by AkihiroSuda** [comment]
@HassanAlsamahi 
Yes, thanks

**Comment by simorgh1** [comment]
Is in progress in [pr 641](https://github.com/containerd/nerdctl/pull/641)

**Comment by AkihiroSuda** [comment]
Fixed in a recent release
