### ISSUE TITLE
nerdctl compose does not pick default compose file

### ISSUE THREAD

**Issue by jandubois** [containerd/nerdctl#3694]
The [docker compose](https://docs.docker.com/compose/intro/compose-application-model/#the-compose-file) documentation says:

> The default path for a Compose file is `compose.yaml` (preferred) or `compose.yml` that is placed in the working directory. Compose also supports `docker-compose.yaml` and `docker-compose.yml` for backwards compatibility of earlier versions. If both files exist, Compose prefers the canonical `compose.yaml`.

This was implemented as part of #305 (although the names were in the wrong order, I think).

But #802 seems to have removed that code again, probably by accident.

```console
$ nerdctl compose up -d
FATA[0000] no configuration file provided: not found
```

cc: @nino-K

**Comment by Nino-K** [comment]
Just a quick update, I’m running this (on Rancher Desktop 1.16 and windows 10) and trying the following:
```
nerdctl compose up -d
```
While it is mentioned [here](https://github.com/containerd/nerdctl/blob/main/docs/compose.md#usage) that there should be compatibility with docker-compose (and the above command works fine with docker), however, it fails with the following error:
```
FATA[0000] no configuration file provided: not found
```
Modifying the command to specify the file, however:
```
nerdctl compose -f .\docker-compose.yaml up -d
```
It works with no problem.

**Comment by jandubois** [comment]
This may actually be an issue with Rancher Desktop on Windows; I've tried to repro the issue on macOS, and it seems to be working there:

```console
$ nerdctl compose up -d
WARN[0000] /Users/jan/tmp/composetest/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
…
```

**Comment by jandubois** [comment]
The code to specify default config files at https://github.com/containerd/nerdctl/blob/43b613322cfde3e5460a0738f055578ea1e41dcd/pkg/composer/composer.go#L83

This is likely an issue with the `nerdctl-stub` handler that converts Windows paths to Linux paths.
