### ISSUE TITLE
nerdctl 2.0.0 fails to use configuration acceleration

### ISSUE THREAD

**Issue by wzxmt** [containerd/nerdctl#3697]
### Description

containerd is using 2.0.0, nerdctl v2.0.0 configuration acceleration failed, but version v1.7.7 was able to accelerate successfully

### Steps to reproduce the issue

1.Use the same configuration
 cat /etc/containerd/certs.d/docker.io/hosts.toml
[host."https://tylhjsevjg.xx.x/"]
  capabilities = ["pull", "resolve", "push"]

2. nerdctl v1.7.7 can succeed
[root@m1 ~]# nerdctl -v
nerdctl version 1.7.7
[root@m1 ~]# nerdctl pull nginx:1.14.1
docker.io/library/nginx:1.14.1:                                                   resolved       |++++++++++++++++++++++++++++++++++++++|
index-sha256:32fdf92b4e986e109e4db0865758020cb0c3b70d6ba80d02fe87bad5cc3dc228:    done           |++++++++++++++++++++++++++++++++++++++|
manifest-sha256:dacd12f5855de663f1a87c9b62004241d389d6d02d7da1a136dfd71aaea8b3e1: done           |++++++++++++++++++++++++++++++++++++++|
config-sha256:5f2d4477b7ea238f6ffb483962f4d124876277879a8aa948ae554d4268a41b04:   done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:251439d5b33cacae1be27ed05f7390cc9cb9759e9c47cb51a6df18a069790ddf:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:a5a6f2f73cd8abbdc55d0df0d8834f7262713e87d6c8800ea3851f103025e0f0:    done           |++++++++++++++++++++++++++++++++++++++|
layer-sha256:2343eb083a4e37d0f6c210b7673bd2cede0f5e96b5fc740045b67f57a5ef28f4:    done           |++++++++++++++++++++++++++++++++++++++|
elapsed: 41.5s                                                                    total:  42.6 M (1.0 MiB/s)

3.nerdctl v2.0.0 can failed
[root@m1 ~]# nerdctl -v
nerdctl version 2.0.0
[root@m1 ~]# nerdctl pull nginx:1.14.2
docker.io/library/nginx:1.14.2: resolving      |--------------------------------------|
elapsed: 9.9 s                  total:   0.0 B (0.0 B/s)
INFO[0010] fetch failed                                  error="failed to do request: Head \"https://registry-1.docker.io/v2/library/nginx/manifests/1.14.2\": net/http: TLS handshake timeout" host=registry-1.docker.io
FATA[0010] failed to resolve reference "docker.io/library/nginx:1.14.2": failed to do request: Head "https://registry-1.docker.io/v2/library/nginx/manifests/1.14.2": net/http: TLS handshake timeout

### Describe the results you received and expected

nerdctl repair speedup

### What version of nerdctl are you using?

v2.0.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

[root@m1 ~]# nerdctl info
Client:
 Namespace:	k8s.io
 Debug Mode:	false

Server:
 Server Version: v2.0.0
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.14.0-427.13.1.el9_4.x86_64
 Operating System: Rocky Linux 9.4 (Blue Onyx)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.793GiB
 Name: m1
 ID: 58f2d555-cf38-4a2a-98bb-9813e727efe0

**Comment by apostasie** [comment]
Confirmed
@AkihiroSuda /assign + v2.0.2 tentatively.

@wzxmt you can temporarily workaround this by TEMPORARILY putting your configuration inside `index.docker.io` instead of `docker.io`:
`/etc/containerd/certs.d/index.docker.io/hosts.toml`

**Comment by wzxmt** [comment]
> 确认的 [@AkihiroSuda](https://github.com/AkihiroSuda)/assign + v2.0.2 暂定。
> 
> [@wzxmt](https://github.com/wzxmt)您可以暂时解决这个问题，方法是将您的配置暂时放在里面，`index.docker.io`而不是`docker.io`： `/etc/containerd/certs.d/index.docker.io/hosts.toml`

ok,thanks!  Change to index.docker.io to succeed。

**Comment by apostasie** [comment]
@wzxmt fix just got merged and will go with upcoming 2.0.2.
Remember to revert from `index.docker.io` to the normal and expected `docker.io` once you update.
