### ISSUE TITLE
mount a path as root / in dockerfile

### ISSUE THREAD

**Issue by finch71** [containerd/nerdctl#3707]
### What is the problem you're trying to solve

containerd does not allow mounting external path to / in dockerfile 

### Describe the solution you'd like

allow mount a path as root / and bypass all the content of image

**Comment by AkihiroSuda** [comment]
We already have `nerdctl run --rootfs DIR /bin/sh`

**Comment by AkihiroSuda** [comment]
> sorry, i know --rootfs but i wonder if this can be done in the dockerfile

This should be proposed to BuildKit:
- https://github.com/moby/buildkit/issues
