### ISSUE TITLE
v2.0.1 (or v2.1.0) planning

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#3709]
https://github.com/containerd/nerdctl/milestone/38?closed=1

The amount of the changes since v2.0.0 are relative small, so probably this can be v2.0.1 rather than v2.1.0.

cc @containerd/nerdctl-committers

**Comment by fahedouch** [comment]
Yes please go ahead @AkihiroSuda. When  do you plan to release ?

**Comment by AkihiroSuda** [comment]
> When do you plan to release ?

Can be today, after:
- s/2.1.0/2.0.1/ https://github.com/containerd/nerdctl/blob/3c41efe581fd7291b446709f11c7439594abf347/docs/config.md?plain=1#L48
- bumping up the deps

**Comment by apostasie** [comment]
@AkihiroSuda if possible, would like to have #3708 in. Addressing comments rn.

**Comment by apostasie** [comment]
Thanks @AkihiroSuda 
Appreciate the inclusion of #3708. This one gave me a serious migraine.

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/nerdctl/releases/tag/v2.0.1
