### ISSUE TITLE
nerdctl-managed containers lack `/etc/hostname`

### ISSUE THREAD

**Issue by TheDiveO** [containerd/nerdctl#376]
As of commit 2895d605d94334620e09fd7edad67711c75a5908 `nerdctl` doesn't seem to create any `/etc/hostname` file inside containers, but only sets the UTS "hostname". This can cause subtle issues with some applications that avoid the glibc hostname call and/or the underlying (sysname) syscall. These then assume that the hostname of the container is empty or undefined.

Test case:

```bash
sudo nerdctl run -it --name nohostname --rm busybox sh -c 'echo hostname: "$(cat /etc/hostname)"'
cat: can't open '/etc/hostname': No such file or directory
hostname:
```

Compare with:

```bash
docker run -it --name nohostname --rm busybox sh -c 'echo hostname: "$(cat /etc/hostname)"'
hostname: 78c26758077f
```

Please provide `/etc/hostname` for improved Docker compatibility.

**Comment by TheDiveO** [comment]
I dunno if this really is a "good first issue", but anyway: where should the code be added to? Would pkg/dnsutil/hostsstore a suitable place, as this is where etc/hosts already gets managed? Or would that be overkill, considering that etc/hostname is static, while etc/hosts is dynamic?

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/nerdctl/blob/d5c5491e35ee6225d5bb795d4db9863d2dfb1ec2/cmd/nerdctl/run.go#L484

We should just create a static `hostname` file in the `stateDir` here and bind-mount.

**Comment by AkihiroSuda** [comment]
PR: https://github.com/containerd/nerdctl/pull/400
