### ISSUE TITLE
MACVLAN support?

### ISSUE THREAD

**Issue by TheDiveO** [containerd/nerdctl#378]
Some of today's Docker scenarios require granting specific containers direct data-link layer ("MAC") access, as opposed to nat'ed IP access. Examples are not only (infamous?) license server containers, but also non-IP protocol-based applications, such as in some industrial environments. Docker comes with its CNM "macvlan" driver and the CNI "driver" base also supports MACVLAN.

At the moment (as of commit 2895d605d94334620e09fd7edad67711c75a5908) does not understand the `-d` option when creating a new network: for Docker, `-d` specifies the type of CNM driver to create a new network with. `nerdctl compose` also catches these case that try to specify a non-bridge network driver and blocks such projects from deployment. 

Please support MACVLAN networks next to bridge networks in nerdctl for improved Docker-compatibility.

**Comment by AkihiroSuda** [comment]
Implemented in https://github.com/containerd/nerdctl/pull/836

**Comment by TheDiveO** [comment]
Thank you very much! I'll see to put it through the paces of some unit tests on our side. Once again, thank you very much!
