### ISSUE TITLE
Why multple images have same iamge ID?

### ISSUE THREAD

**Issue by stricklandye** [containerd/nerdctl#3785]
### Description

Hi there. I am trying to write a program to remove some large images on a node. And I guess the following code should work:
```golang
func (c *Cleaner) RemoveImage(imageName, ns string) error {
	ctx := namespaces.WithNamespace(context.Background(), ns)
	delOpts := []images.DeleteOpt{images.SynchronousDelete()}
	return c.client.ImageService().Delete(ctx, imageName, delOpts...)
}
```
But I found that an image has multiple parts that has some image ID and the **above code only moves one part of it.**  Here is the image information I got by using `nerdctl images --namespace k8s.io`:
```
calico/cni     <none>      77e44a758688    21 hours ago      linux/amd64    221MB      99.81MB
<none>         <none>      77e44a758688    21 hours ago      linux/amd64    221MB      99.81MB
calico/cni     master      77e44a758688    21 hours ago      linux/amd64    221MB      99.81MB
```
It's a lilttle bit weird becuase I though Image ID should be unique to every image, **why multiple images have same Image ID?**  So I don't know why and **how can I  remove all these images (for example, images with ID `77e44a758688`) by using code shown above?** 

### Steps to reproduce the issue

1.
2.
3.

### Describe the results you received and expected

`RemoveImage("calico/cni:master ")` should remove all the images with ID `77e44a758688`

### What version of nerdctl are you using?

v2.0.2

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by AkihiroSuda** [comment]
They have the same ID because they are the same image. (i.g., they have the same OCI Index blob)

**Comment by stricklandye** [comment]
> They have the same ID because they are the same image. (i.g., they have the same OCI Index blob)

I see. Haha the truth is that all these images are identical but with different t tags . I copied some codes from nerdctl (remove dangling images)  and it works as I excepted. Thank you for replying :D
