### ISSUE TITLE
FreeBSD CI is flaky: mount_nullfs: ...: Resource deadlock avoided

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#379]
> CI seems flaky.
> 
> Can be fixed later, though
>
>
>> time="2021-09-21T14:19:05Z" level=fatal msg="failed to create shim: failed to mount rootfs component &{nullfs /var/lib/containerd/io.containerd.snapshotter.v1.native/snapshots/3 [rw]}: mount [[-o rw -t nullfs /var/lib/containerd/io.containerd.snapshotter.v1.native/snapshots/3 /run/containerd/io.containerd.runtime.v2.task/default/70886b2a11483b463360ab4f419294075698a64754c02bc1dda57fc642e60ba9/rootfs]] failed: \"mount_nullfs: /run/containerd/io.containerd.runtime.v2.task/default/70886b2a11483b463360ab4f419294075698a64754c02bc1dda57fc642e60ba9/rootfs: Resource deadlock avoided\\n\": exit status 1: unknown"

_Originally posted by @AkihiroSuda in https://github.com/containerd/nerdctl/issues/361#issuecomment-924040570_

**Comment by akhramov** [comment]
Tracking this issue in runj: https://github.com/samuelkarp/runj/issues/30

**Comment by samuelkarp** [comment]
Is this still an issue?

**Comment by AkihiroSuda** [comment]
Seems not
