### ISSUE TITLE
login succeeds but push doesn't progress

### ISSUE THREAD

**Issue by davidberglund** [containerd/nerdctl#386]
nerdctl in lima (ubuntu cloud image) on an Apple Silicon Mac on 11.6 (Big Sur). build, run and other commands seem to work.
Login as well ("Login Succeeded"). But `nerdctl push` hangs, counting in waiting for all layers while "elapsed" time continous indefinitely.
 
`nerdctl push gitlab.domain.com:5050/user123/app123:tag
INFO[0000] pushing as a single-platform image (application/vnd.docker.distribution.manifest.v2+json, sha256:cdb7445382913287d1e0034db9080e01e96aea3a3c1f109d2643148801e578a7) 
manifest-sha256:cdb7445382913287d1e0034db9080e01e96aea3a3c1f109d2643148801e578a7: waiting        |--------------------------------------| 
layer-sha256:e91064730500746be97b6f35ae9c33bf1d9b7b0b4e9fd5f766c84ff08d25502b:    waiting        |--------------------------------------| 
layer-sha256:9822acfe964a9371ddf4fe437c97db215e08b89a4bd4bf7db8c689f4ee8cf510:    waiting        |--------------------------------------| 
layer-sha256:e88c09aad7fe916f528741afa2a4072f4b8514725f54c9a9e3b0d8e38d7cf98d:    waiting        |--------------------------------------| 
layer-sha256:7c492206888c962a8cd02d08cdbdc962f2a10b7e2373d1aca6ac94a817ca309c:    waiting        |--------------------------------------| 
layer-sha256:32ebfb02ddcff9e4c8d2b993f909b47b7141ba9fb8aa2719d96e6279e865f713:    waiting        |--------------------------------------| 
layer-sha256:69e62efd707da56e76b22cba50b0997fca3805c7b2a2f0e70e0534b25bc4b003:    waiting        |--------------------------------------| 
layer-sha256:bbb36f655d20cbcffd62fe83cb26be4a1a3132dbc0efd2a35adce573455b3315:    waiting        |--------------------------------------| 
layer-sha256:796aacde044f63dff989d60988f9bed73d5de2b21f44da8002a563d882fa4e73:    waiting        |--------------------------------------| 
config-sha256:1320501e354fcc1a31af7d6a1bb374910696e8317f849c11dc89e2ae2cad8d46:   waiting        |--------------------------------------| 
layer-sha256:fb44d26a138a8d064a4ab8f9b472c64e7136c2482ec5af19bab8811b6d2c15b7:    waiting        |--------------------------------------| 
layer-sha256:195488cfc78f0e257698fa052494b5340338b5acfdec4df1b249942044222274:    waiting        |--------------------------------------| 
layer-sha256:c78c297fb0d010ee085f95ae439636ecb167b050c1acb4273bd576998cf94a83:    waiting        |--------------------------------------| 
layer-sha256:06af62193c25241eb123af8cf115c7a6298e834976fe148ac79ec11a7ca06ee5:    waiting        |--------------------------------------| 
layer-sha256:8b846e1b73901174c506ae5e6219ac2f356ef71eaa5896dfbc238dc67ca4bf73:    waiting        |--------------------------------------| 
elapsed: 16.5s                                                                    total:   0.0 B (0.0 B/s) ` 

Where can I start troubleshooting this, please? Thank you/David

**Comment by davidberglund** [comment]
Push started to work after an update. I'll close this.

**Comment by markgarrigan** [comment]
I have the same issue on version 0.12.1

**Comment by markgarrigan** [comment]
```
INFO[0000] pushing as a single-platform image (application/vnd.docker.distribution.manifest.v2+json, sha256:2b45370d34e0d0fd7ee670c7827460fde1e6ea6b22b6484ae30ff4ae28b7f911) 
manifest-sha256:2b45370d34e0d0fd7ee670c7827460fde1e6ea6b22b6484ae30ff4ae28b7f911: waiting        |--------------------------------------| 
layer-sha256:33f41887a57080e081ecb50510902fa86080baa37766a002d92658e6f2ab3ea8:    waiting        |--------------------------------------| 
config-sha256:b8c9614b9f6c0d87d734e100b849864a8c2c93f2ff709f02a4396c0077c341f0:   waiting        |--------------------------------------| 
layer-sha256:b887f37000be02b1fc30ae5e6242a21d0f50cf4add51055b0f73558de38824b1:    waiting        |--------------------------------------| 
layer-sha256:2557d77de56fe6b1335d3e2c89fc50f25963b6b0e0b5708a5357c8f8d2c3e8b8:    waiting        |--------------------------------------| 
layer-sha256:77cd4eacbe814fea30ed7e9bd30d84a72ab63c2f6c16b3efbdbb1a66c6c13e5d:    waiting        |--------------------------------------| 
layer-sha256:b192fb9b8fcd568e7de396212939da4342dfd27f3e38ef51d28f8f2c68a58b1a:    waiting        |--------------------------------------| 
layer-sha256:33db897323538f48b0d5f833404959602ded24e2c60221c2a65f7e6aaec25f4e:    waiting        |--------------------------------------| 
layer-sha256:e6563ca08b36bda9f251c571c79591b02a5981ddb305ebc040249100878cf0f8:    waiting        |--------------------------------------| 
layer-sha256:51de130d83f8c690d29a15064f98eab7db1810603d0288d3b813ec54a93c7416:    waiting        |--------------------------------------| 
layer-sha256:e2f7af5f0e1b7fe34105a79b9f9f1555af4d9b9ee6eb2debec0be51ec70e06cd:    waiting        |--------------------------------------| 
layer-sha256:afef5e87d3adbf775d4d44eadaba439adac6363a6a7ed50d18652ba63859a506:    waiting        |--------------------------------------| 
elapsed: 92.2s                                                                    total:   0.0 B (0.0 B/s) 
```

**Comment by tmehlinger** [comment]
I'm having this problem as well with nerdctl 0.13.0 with colima.

**Comment by kmhagan** [comment]
I am seeing this issue as well. The push worked for me but only the elapsed duration was updating on the screen, the rest of the text fields didn't progress which made it seem like it wasn't working. I am using `limactl v0.8.0` and `nerdctl v0.15.0`
