### ISSUE TITLE
Integration with VSCode

### ISSUE THREAD

**Issue by ksaur** [containerd/nerdctl#392]
Hello, I would like to try to use `nerdctl` with VSCode.  When VSCode starts, it checks for Docker with:

```
[342501 ms] Remote-Containers 0.194.3 in VS Code 1.60.2 (7f6ab5485bbc008386c4386d08766667e155244e).
[342501 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[342637 ms] 
[342638 ms] Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

My first thought was to point VSCode to point to `lima nerdctl` by using an environment variable to sub out `docker`.  But this command gives the error of:

```
$ lima nerdctl version --format {{.Server.APIVersion}}
FATA[0000] template: :1:9: executing "" at <.Server.APIVersion>: can't evaluate field APIVersion in type *dockercompat.ServerVersion
```

Is there a current way to make VSCode work with `nerdctl`? If not, what needs to be done?

**Comment by AkihiroSuda** [comment]
VS Code would need to be modified to support nerdctl

**Comment by vlushn** [comment]
VS Code link: https://github.com/microsoft/vscode-remote-release/issues/5538

**Comment by brad-jones** [comment]
FWIW I just gave nerdctl a go with devcontainers & ran into the same issue. Hacked up a super simple bash shim to give vscode the right value for `.Server.APIVersion` but then ran into another CLI incompatibly. Missing `--sig-proxy` flag for the `run` command. I gave up at that point.
