### ISSUE TITLE
No support for 'container create' command

### ISSUE THREAD

**Issue by tmbull** [containerd/nerdctl#393]
Docker CLI has a [container create](https://docs.docker.com/engine/reference/commandline/container_create/) command which will create a container without starting it. I have used this in the past to, for example, copy some files from the host into a docker volume:

`docker create --name temp -v api-config:/data busybox && docker cp ./api/config/. temp:/data && docker rm temp`

This can be accomplished in other ways. I just thought I would post this issue assuming that the goal of this project is feature parity with docker CLI.

**Comment by AkihiroSuda** [comment]
Implemented in https://github.com/containerd/nerdctl/pull/646 (v0.16.0)
