### ISSUE TITLE
quick question about the networking stack...

### ISSUE THREAD

**Issue by dreamcat4** [containerd/nerdctl#405]
Hello Akihiro,
and sorry to bother you here with my question. But well done for `nerdctl` and working on these OCI and containerd side of things. My question is something related to lower layers in the networking drivers. Which might already be the same and in common with docker. But I shall first explain:

In docker (last time I tried this). Was trying to create a VPN containers, including killswitch feature. However while it was possible to setup an openvpn connection inside a container. To make and export it´s own vpn network into other containers as a docker network. There was an issue:

The killswitch feature did not work during container restarts. The reason was due to the way docker would automatically setup networking default `route`s the routing table in a container on boot up. To configure the VPN, it then had to edit the default routing table, from within the container. Which can only happen after the container is started. And after docker had first setup the default routes before passing control over to the entrypoint / init porcess inside the container.

So due to those assumptions inside the networking driver (for bridge mode / macvlan was being tested in this case). Anyhow due to that sequence of preparation events. For inserting the `eth0` inside the container. Then this broke killswitch feature. And packets would leak during boot time. Before the container script had the opportunity to fix the network routing table using the `route` command. And the other key networking setup command was iptables, to then also assign forwarding rules to the vpn endpoint. Which would also occur during this startup process.

So my question is simple: can we get around this assumptions / issue using `containerd` and `nerdctl`? Is that networking stack different enough at lower levels to afford this extra control during the container networking initialization? Because then that would be worth trying again here with `nerdctl`instead of docker. Another reason for my question is also because as you explain: docker is much slower to lag behind getting new features. 

I am sorry if this is not the correct project where to be asking this. But the current modern network stack I am not anymore so familiar. But maybe you can still give a small insight, and to point me in the right direction. For where this `default route` initialization is now occuring in the OCI code. Many thanks

**Comment by AkihiroSuda** [comment]
nerdctl uses CNI, so if you build a CNI plugin that satisfies your requirement, it should work with nerdctl.

`sudo nerdctl run --network foo` uses the CNI config located at `/etc/cni/net.d/foo.conflist`.

How to build a CNI plugin for your requirement is out of my knowledge.
