### ISSUE TITLE
container run failure in kubernetes pod

### ISSUE THREAD

**Issue by ryanbrigden** [containerd/nerdctl#406]
Looking to run `nerdctl` in a kubernetes pod, specifically to run containers on the host. I've successfully been able to run all basic commands other than `container run`, which include

```
container exec
container ls
container rm
container stop
```

When I execute `container run` at any debug level I only see the following error:

```
FATA[0000] operation not permitted
```

I've mounted the following host paths to the pod
```
/run/containerd
/var/lib/containerd
/var/lib/nerdctl
/tmp
```

I've attached the `strace` of `container run` in the pod -- here is a snippet of it that I think may point to the issue:

```
rt_sigreturn({mask=[]})                 = 1
geteuid()                               = 0
geteuid()                               = 0
openat(AT_FDCWD, "/proc/self/uid_map", O_RDONLY|O_CLOEXEC) = 3
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=723666648, u64=140390319671000}}) = -1 EPERM (Operation not permitted)
read(3, "         0          0 4294967295"..., 4096) = 33
close(3)                                = 0
statfs("/sys/fs/cgroup", {f_type=TMPFS_MAGIC, f_bsize=4096, f_blocks=32640722, f_bfree=32640722, f_bavail=32640722, f_files=32640722, f_ffree=32640706, f_fsid={val=[0, 0]}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_NOSUID|ST_NODEV|ST_NOEXEC|ST_RELATIME}) = 0
```

[strace_container_run.log](https://github.com/containerd/nerdctl/files/7279810/tracing.log)

Appreciate any pointers for getting this to run successfully.

**Comment by AkihiroSuda** [comment]
You need securityContext.privileged

**Comment by ryanbrigden** [comment]
That did it  😃
