### ISSUE TITLE
Sharing network namespace

### ISSUE THREAD

**Issue by ryanbrigden** [containerd/nerdctl#421]
Is it possible to share the network namespace between two containers, just like when passing `--network=container:<container>` with `docker run`? I'm looking to share an interface / network namespace between two containers that are in a bridge network with other containers.

**Comment by ryanbrigden** [comment]
Anyone have an idea for a workaround for the moment? Would it be enough to create a named network namespace using `ip netns add` and then passing this path [in this OCI hook handler](https://github.com/containerd/nerdctl/blob/master/pkg/ocihook/ocihook.go#L236)? Appreciate the help and once I can get it working would like to contribute this as a feature to meet docker CLI parity.

**Comment by AkihiroSuda** [comment]
> Would it be enough to create a named network namespace using `ip netns add` and then passing this path at `/var/run/netns` [in this OCI hook handler](https://github.com/containerd/nerdctl/blob/master/pkg/ocihook/ocihook.go#L236)?

I don't think we need `ip netns add`. 

We can just use `/proc/${ANOTHER_CONTAINER_PID}/ns/net`.

Supporting `--restart` in conjunction with this might be complicated ,though.

**Comment by t1anz0ng** [comment]
@ryanbrigden this feature was implemented in https://github.com/containerd/nerdctl/releases/tag/v0.22.1
please use check it out on  https://github.com/containerd/nerdctl/releases/tag/v0.22.2 (v0.22.2 fixed a regression from [v0.22.1](https://github.com/containerd/nerdctl/releases/tag/v0.22.1)) 😄

**Comment by junnplus** [comment]
@t1anz0ng Thanks, and I close this.
