### ISSUE TITLE
embed signing container image logic into nerdctl by using cosign as a library

### ISSUE THREAD

**Issue by developer-guy** [containerd/nerdctl#423]
[cosign](https://github.com/sigstore/cosign) maintained by the awesome `sigstore` community is a new standard that allows the signature and verification of container images and OCI artifacts.

we (w/@Dentrax @erkanzileli) thought that we can add this support for signing images right after built them.

**Comment by AkihiroSuda** [comment]
SGTM, how will CLI look like?

**Comment by developer-guy** [comment]
> SGTM, how will CLI look like?

I thought we may accept --key option from the users while building container image, that's all, then we can pass this to cosign to sign container image right after we built it.

```shell
$ nerdctl build -t foo --key <private_key_path> /some-dockerfile-directory
```

**Comment by developer-guy** [comment]
let's make it happen with Keyless mode. 😍  Would you mind assigning it to me @AkihiroSuda 🙋🏻‍♂️

**Comment by AkihiroSuda** [comment]
Assigned @developer-guy 👍
