### ISSUE TITLE
Docker credential helpers not working

### ISSUE THREAD

**Issue by thecodeassassin** [containerd/nerdctl#429]
Hi all,

I am using credential helpers for accessing Google Cloud Container Registry repo's and it's not working for me:

elapsed: 0.7 s                            total:   0.0 B (0.0 B/s)
FATA[0000] failed to resolve reference "eu.gcr.io/xxx/xxx:197": pulling from host eu.gcr.io failed with status code [manifests 197]: 401 Unauthorized

It seems that my credential file is not parsed or loaded correctly. According to the docks the default of DOCKER_CONFIG should be $HOME/.docker. The file is there and everything works fine with Docker for Mac. But with nerdctl it doesn't work.

I am using OSX 10.15.7

Excerp of my ~/.docker/config
```
  "credsStore" : "osxkeychain",
  "experimental" : "disabled",
  "credHelpers" : {
    "marketplace.gcr.io" : "gcloud",
    "asia.gcr.io" : "gcloud",
    "us.gcr.io" : "gcloud",
    "eu.gcr.io" : "gcloud",
    "gcr.io" : "gcloud",
    "staging-k8s.gcr.io" : "gcloud"
  },
  "auths" : {
    "eu.gcr.io" : {

    },
  ```

**Comment by AkihiroSuda** [comment]
@knkarthik Please make sure you have `docker-credential-ecr-login`  binary inside the VM.

**Comment by knkarthik** [comment]
I've it installed in the VM with `sudo apt install amazon-ecr-credential-helper`  and my local `.aws/` mounted on `/home/USERNAME.linux/.aws`. `docker pull` from host works but not `nerdctl.lima`.

**Comment by jmbradshaw79** [comment]
Not sure if this is same issue with aws cred helper but I saw a similar issue with docker-credential-gcloud. Running `lima nerdctl --debug-full pull ...` I see `error getting credentials - err: exec: \"docker-credential-gcloud\": executable file not found in $PATH`....  
Seems running `lima nerdctl` does not use path updated in by `.bashrc` So after running `sudo ln -s $HOME/google-cloud-sdk/bin/docker-credential-gcloud /usr/bin/docker-credential-gcloud` to make the binary available in the default path solves the issue for me. So linking to a location in the default path or updating default path enables it to work without jumping in to VM and executing in shell that has processed .bashrc.

**Comment by nikonovak** [comment]
To add to what @jmbradshaw79 - I got it to work on my end with following:

Google Cloud SDK 365.0.1
Rancher Desktop Version: 0.6.1

My google-cloud-sdk resides in my home folder under ~/google-cloud-sdk

```
# export lima home
export LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima"

# install python3 (necessary for gcloud)
"/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0 \
sudo apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main python3

# create symlinks
"/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0 \
sudo ln -s $(echo "/Users/$(whoami)/.config") /root/.config

"/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0 \
sudo ln -s $(echo "/Users/$(whoami)/.docker") /root/.docker

"/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0 \
sudo ln -s $(echo "/Users/$(whoami)/google-cloud-sdk/bin/docker-credential-gcloud") /usr/bin/docker-credential-gcloud
```

**Comment by thecodeassassin** [comment]
> To add to what @jmbradshaw79 - I got it to work on my end with following:
> 
> Google Cloud SDK 365.0.1 Rancher Desktop Version: 0.6.1
> 
> My google-cloud-sdk resides in my home folder under ~/google-cloud-sdk
> 
> ```
> # export lima home
> export LIMA_HOME="$HOME/Library/Application Support/rancher-desktop/lima"
> 
> # install python3 (necessary for gcloud)
> "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0 \
> sudo apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/main python3
> 
> # create symlinks
> "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0 \
> sudo ln -s $(echo "/Users/$(whoami)/.config") /root/.config
> 
> "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0 \
> sudo ln -s $(echo "/Users/$(whoami)/.docker") /root/.docker
> 
> "/Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/lima/bin/limactl" shell 0 \
> sudo ln -s $(echo "/Users/$(whoami)/google-cloud-sdk/bin/docker-credential-gcloud") /usr/bin/docker-credential-gcloud
> ```

Thank you very much for this, works like a charm.

**Comment by AkihiroSuda** [comment]
Seems we can close this issue?

**Comment by Sebor** [comment]
> ```shell
> aws ecr get-login-password
> ```

Do you have AWS credentials inside lima?

**Comment by emmahsax** [comment]
Hah probably not. I didn't pass anything to lima, just have my `~/.aws/credentials` file set up.
