### ISSUE TITLE
build: unable to parse COPY --chown flag in Dockerfile

### ISSUE THREAD

**Issue by pfiaux** [containerd/nerdctl#433]
Nice project, loving the idea of a containerd based docker alternative. While trying it out I ran into some issues, one being some of the flags on `COPY` cause errors trying to build images:
```
  30 | >>> COPY --chown=
--------------------
error: failed to solve: dockerfile parse error on line 30: COPY requires at least two arguments, but only one was provided. Destination could not be determined.
```
I have a dockerfiles with 2 stage build, in images with only `--from=` it seems to work, but `--chown` and `--from` together don't (didn't try `--chown=` alone) but image builds fine with docker.

Dockerfile reference doc: https://docs.docker.com/engine/reference/builder/#copy

Version info:
```
nerdctl version
Client:
 Version:	v0.12.1
 Git commit:	6f0c8b7bc63270404c9f5810a899e6bae7546608
Server:
 containerd:
  Version:	v1.5.7
  GitCommit:	8686ededfc90076914c5238eb96c883ea093a8ba
```

**Comment by AkihiroSuda** [comment]
Please report to https://github.com/moby/buildkit/issues with the version info of buildkitd
