### ISSUE TITLE
nerdctl login needs Enter key pressed twice

### ISSUE THREAD

**Issue by artursouza** [containerd/nerdctl#462]
How to repro:

```txt
nerdctl login -u <your username>
```

Now, enter your password and hit enter. Nothing happens until you hit enter again.

Reproduced using MacOS BigSur Intel.
nerdctl version 0.12.1

**Comment by simorgh1** [comment]
Using [pr 641](https://github.com/containerd/nerdctl/pull/641), after running
```
nerdctl login -u <your username>
```
and adding password, login is executed.
used: 

- MacOS BigSure M1
- nerdctl version: 0.15.0

**Comment by AkihiroSuda** [comment]
This should have been fixed in a recent release
