### ISSUE TITLE
Docker-py compatible Python Bindings for nerdctl / containerd

### ISSUE THREAD

**Issue by mrueg** [containerd/nerdctl#48]
It would be interesting to create python bindings for nerdctl that are compatible with the docker-py implementation as well.
With this it might be possible to run docker-compose (or nerd-compose) via containerd.

**Comment by AkihiroSuda** [comment]
This one might be easy to port https://github.com/gabrieldemarmiesse/python-on-whales

**Comment by sckn** [comment]
Hi,
I have fork from original repository and changed to nerdctl. I didn't test yet.

https://github.com/sckn/python-on-nerdctl

I will test in at my free time.

**Comment by AkihiroSuda** [comment]
python-on-whales supports nerdctl now:
- https://github.com/gabrieldemarmiesse/python-on-whales/pull/329
