### ISSUE TITLE
Question: `docker compose pull` type functionality

### ISSUE THREAD

**Issue by dkowis** [containerd/nerdctl#480]
This is a fantastic project, and I love that it exists!

I'm used to being able to say `docker compose pull` to make sure all my containers are up to date, especially with tags like `latest`. How can I do the same thing with nerdctl? 

I already tried `nerdctl compose pull` and that wasn't in the list of supported commands. I also didn't find a command option that I could say "always pull" or something like that to ensure my images are up to date.

Thanks!

**Comment by fahedouch** [comment]
Hi @dkowis ,

I assume that `docker-compose pull` don't ensure up to date images.  This can be done with `docker-compose build --pull`.
`nerdctl compose pull` and `nerdct compose build --pull` are not yet implemented

**Comment by afbjorklund** [comment]
Added naive implementation in #546

**Comment by AkihiroSuda** [comment]
Thanks @afbjorklund
