### ISSUE TITLE
nerdctl0 not created after deleted

### ISSUE THREAD

**Issue by jongwu** [containerd/nerdctl#482]
when I first use nerdctl, the bridge "nerdctl0" is created. but after I delete that bridge using "ip link delete", the bridge never created again.
what should I do to resolve it?

**Comment by AkihiroSuda** [comment]
Does it work after rebooting?

**Comment by jongwu** [comment]
No, I tried but it does not work. I look into the code and can't find where the bridge is created. Can you show me where that bridge is created? thanks!

**Comment by AkihiroSuda** [comment]
The bridge is created by just running CNI bridge plugin

https://github.com/containerd/nerdctl/blob/46be3b7fd8d8921603d3844475abb784f06077e6/pkg/netutil/netutil_unix.go#L38-L56

https://github.com/containernetworking/plugins/tree/v1.0.1/plugins/main/bridge

**Comment by AkihiroSuda** [comment]
Do you see any error when you run `sudo nerdctl --debug-full run --rm  alpine ip a`?
Does `dmesg` show anything related?

**Comment by jongwu** [comment]
In my machine, start container using nerdctl will give a error: `FATA[0001] failed to create shim: OCI runtime create failed: container_linux.go:349: starting container process caused "error adding seccomp filter rule for syscall clone3: permission denied": unknown`

So I suppress the seccomp by using `--security-opt "seccomp=unconfined"` then I can start container without warning. it show:

DEBU[0000] detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf
DEBU[0000] final cOpts is [0x7704c0 0x7707e0 0x770850 0x770680 0x7703f0 0x770540 0x770540 0x770af0]
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever

**Comment by jongwu** [comment]
Also, there is nothing related in dmesg.

**Comment by jongwu** [comment]
> The bridge is created by just running CNI bridge plugin
> 
> https://github.com/containerd/nerdctl/blob/46be3b7fd8d8921603d3844475abb784f06077e6/pkg/netutil/netutil_unix.go#L38-L56
> 
> https://github.com/containernetworking/plugins/tree/v1.0.1/plugins/main/bridge

But where nerdctl call the lib of cni? I can't find the entry.

**Comment by AkihiroSuda** [comment]
> clone3

Please make sure to run nerdctl v0.11.2 or later. 
https://github.com/containerd/nerdctl/pull/360

> But where nerdctl call the lib of cni? I can't find the entry.

Here: https://github.com/containerd/nerdctl/blob/46be3b7fd8d8921603d3844475abb784f06077e6/pkg/ocihook/ocihook.go#L321

**Comment by jongwu** [comment]
Thanks @AkihiroSuda -, I reinstall runc and the issue is gone. Maybe the runtime is old and won't compatible with the oci-hooks offered by nerdctl. But I'm also confused with that runc is not used by containerd, so, why runc will affected the result.

**Comment by AkihiroSuda** [comment]
> runc is not used by containerd

used.

**Comment by jongwu** [comment]
> > runc is not used by containerd
> 
> used.

Yeah, containerd-shim-runc-v2 call runc. thanks!
