### ISSUE TITLE
Short arguments should not require a space before the parameter

### ISSUE THREAD

**Issue by friedrich** [containerd/nerdctl#490]
Many (most?) programs that accept short style command line arguments do not require a space before a parameter. nerdctl deviates from this tradition, which introduces an incompatibility with Docker.

This works:
`nerdctl run -p 8080:80 nginx:alpine`
This does not:
`nerdctl run -p8080:80 nginx:alpine`

Both work using Docker:
`docker run -p 8080:80 nginx:alpine`
`docker run -p8080:80 nginx:alpine`

**Comment by AkihiroSuda** [comment]
`nerdctl run -p8080:80 nginx:alpine` seems to work with the master branch.
Will be included in v0.13.

**Comment by AkihiroSuda** [comment]
v0.13 is now available https://github.com/containerd/nerdctl/releases/tag/v0.13.0

**Comment by friedrich** [comment]
Great! I just tried it and can confirm that it works now.
