### ISSUE TITLE
facing problem when I use nerdctl image encrypt

### ISSUE THREAD

**Issue by Ramkumar-Murugesan** [containerd/nerdctl#494]
Hi team,
I like the concept of combining containerd and docker into one package

 when I give 
"`sudo nerdctl image encrypt --recipient=jwe:mypubkey.pem --platform=linux/amd64,linux/arm64 angular-ex2 angular_example:encrypted` " cmd in terminal

it shows **"No help topic for 'encrypt'"** 

also can't able to see the **encrypt** command in `nerdctl image -help`

**![Screenshot_2021-11-03_04-43-11](https://user-images.githubusercontent.com/33427536/140030979-1dbc5d4c-90f9-4ffe-af41-34e3a8cc0fb7.png)**

**Comment by AkihiroSuda** [comment]
You need nerdctl v0.13 or later to use `nerdctl image encrypt`.
v0.13 will be probably released tomorrow.

Until that you can try the master branch.

**Comment by AkihiroSuda** [comment]
v0.13 is now available 
https://github.com/containerd/nerdctl/releases/tag/v0.13.0
