### ISSUE TITLE
Support for `nerdctl build --rm` flag

### ISSUE THREAD

**Issue by gakio12** [containerd/nerdctl#504]
There are some makefile systems that specify the `--rm` flag on a `build` command. Because there is no support for this in nerdctl, an `alias docker=nerdctl` won't work.

From the Docker documentation: 
> default: true
> Remove intermediate containers after a successful build

**Comment by gakio12** [comment]
It looks like buildkit doesn't actually use `--rm`, and the Docker CLI doesn't look to be using it anymore (https://github.com/moby/buildkit/issues/1470).

I can add it as a flag, then mark it as hidden, so it will still function. If someone does use it, should it print a warning such as `ignoring depricated flag: '--rm=false'`, or should it just be quiet about it?

**Comment by AkihiroSuda** [comment]
Maybe we should run `buildctl prune` when `--rm` is specified
