### ISSUE TITLE
`nerdctl run` argument parsing order potentially broken?

### ISSUE THREAD

**Issue by askreet** [containerd/nerdctl#510]
From `nerdctl run --help`:

```
Usage:
  nerdctl run IMAGE [COMMAND] [ARG...] [flags]
```

From `docker run --help`:

```
Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]
```

We are trying to run a container in a script with a complex set of options passed to the command but because of this ordering it's not clear that `nerdctl` can safely disambiguate between arguments it should process and arguments for the spawned container.

The docker equivalent command looks like this:

```
docker run --rm --mount type=bind,source=A_PATH,target=A_PATH --env PGHOST=host.lima.internal --env PGPORT=5432 --env PGUSER=postgres --env PGPASSWORD=password -it postgres:12.3 pg_dump --schema-only --no-privileges --no-owner --file A_FILE db_name
```

If I attempt to use the argument order in the help, it of course tries to pass `run` arguments like `--rm` and `--env` to the `pg_dump` binary in the container and fails. If someone can confirm this is unexpected, I may be able to take a look at resolving it.

**Comment by AkihiroSuda** [comment]
Just the --help text is broken.

The actual implementation is correct AFAIC, but let us know if something is actually broken.

**Comment by askreet** [comment]
@AkihiroSuda Ahh, I see. I think this actually stems from the fact that I am trying to use `--mount` which is (it seems) unsupported by `nerdctl` and thus it stops argument parsing and gives me this error:

```
FATA[0000] requires at least 1 arg(s), only received 0
```

**Comment by AkihiroSuda** [comment]
> FATA[0000] requires at least 1 arg(s), only received 0

cc @robberphex 
Can we improve this error message?

**Comment by robberphex** [comment]
ok, I will fix this later.
