### ISSUE TITLE
M1 native full build release

### ISSUE THREAD

**Issue by Syntax3rror404** [containerd/nerdctl#514]
Hi i see that for linux amd 64 exist a full package with containerd and a sh script and the nerdctl bin. Can you build a package for M1 mac?

**Comment by AkihiroSuda** [comment]
> Can you build a package for M1 mac?

Yes, this is called Lima (https://github.com/lima-vm/lima)

```console
$ brew install lima
$ limactl start
$ lima nerdctl run -d --name nginx -p 127.0.0.1:8080:80 nginx:alpine
```
