### ISSUE TITLE
Add Windows hostprocess support

### ISSUE THREAD

**Issue by jsturtevant** [containerd/nerdctl#518]
Add the correct specs fields to https://github.com/containerd/nerdctl/blob/f316402913c4239a2388b7467bcffc9735dd8327/cmd/nerdctl/run_windows.go#L42

Something like:

```
hpc, err := cmd.Flags().GetBool("host-process")
if err != nil {
  return nil, err
}
if hpc {
  //TODO append the right hpc opts
}
```

See https://github.com/containerd/containerd/pull/5131 for details on how to set the right spec fields.

**Comment by dcantah** [comment]
Planning to look at this next week

**Comment by dcantah** [comment]
@AkihiroSuda What's the story for how certain things should be handled if they require a specific Containerd version? hostprocess (Windows' version of a privileged container) will be a feature for Containerd 1.6 and currently only works in the beta releases until a full release.

**Comment by AkihiroSuda** [comment]
> What's the story for how certain things should be handled if they require a specific Containerd version?

Just mentioning that in `docs/windows.md` would be fine

**Comment by dcantah** [comment]
Ok awesome, thanks!
