### ISSUE TITLE
[nerdctl.exe of Rancher Desktop] Support cygwin under windows

### ISSUE THREAD

**Issue by alfclement** [containerd/nerdctl#540]
I have my code under a mapped directory "Z" (subst z: c:\cygwin64\home\aclement\WORK) under Windows 10 using cygwin to compile and build on command line. Somehow nerdctl does not yet can deal with this situation:

aclement@DESKTOP-L161MC2 /cygdrive/z/code/docker/c1
$ ls -l docker-compose.yaml
-rw-r--r-- 1 aclement None 81 Jul  7 10:42 docker-compose.yaml

aclement@DESKTOP-L161MC2 /cygdrive/z/code/docker/c1
$ nerdctl compose up -d
FATA[0000] cannot find a compose YAML, supported file names: [docker-compose.yml
 docker-compose.yaml compose.yml compose.yaml] in this directory or any parent

aclement@DESKTOP-L161MC2 /cygdrive/z/code/docker/c1
$ nerdctl version
Client:
 Version:       v0.11.1
 Git commit:    95071bf1c5ec9c844931bcedeff049d0ce6f3584

Server:
 containerd:
  Version:      v1.4.11-k3s1
  GitCommit:

$ type nerdctl
nerdctl is hashed (/cygdrive/c/Users/aclement/AppData/Local/Programs/Rancher Desktop/resources/resources/win32/bin/nerdctl)

Would be nice if this works. Docker desktop worked fine.

**Comment by AkihiroSuda** [comment]
This seems an issue of `nerdctl-stub` of Rancher Desktop 
https://github.com/rancher-sandbox/rancher-desktop/tree/v0.6.1/src/go/nerdctl-stub

Could you open an issue in Rancher Desktop repo: https://github.com/rancher-sandbox/rancher-desktop/issues
