### ISSUE TITLE
Listen port not show with ss -tln or netstat -tln

### ISSUE THREAD

**Issue by fredericpougnault** [containerd/nerdctl#543]
I created a containerd with the following command :
- nerdctl create -d -p 8080:80 --name httpd docker.io/library/httpd:latest

The httpd server works well.
But when I tried to see if something is listening on port 8080 on the host I didn't show anything 

nerdctl ps
CONTAINER ID    IMAGE                             PLATFORM       COMMAND               CREATED           STATUS    PORTS                   NAMES
159aa295e385    docker.io/library/httpd:latest    linux/amd64    "httpd-foreground"    48 minutes ago    Up        0.0.0.0:8080->80/tcp    httpd

ss -tln
State                           Recv-Q                          Send-Q                                                     Local Address:Port                                                      Peer Address:Port                          Process
LISTEN                          0                               128                                                            127.0.0.1:44673                                                          0.0.0.0:*
LISTEN                          0                               128                                                              0.0.0.0:111                                                            0.0.0.0:*
LISTEN                          0                               128                                                              0.0.0.0:22                                                             0.0.0.0:*
LISTEN                          0                               128                                                                 [::]:111                                                               [::]:*
LISTEN                          0                               128                                                                 [::]:22                                                                [::]:*

With curl command : 
curl http://127.0.0.1:8080
<html><body><h1>It works!</h1></body></html>

**Comment by fahedouch** [comment]
Hi @fredericpougnault,

This may help you https://github.com/containerd/nerdctl/issues/285#issuecomment-876350835

**Comment by AkihiroSuda** [comment]
Expected behavior with rootful mode, as rootful mode uses CNI portmap for exposing ports.
https://www.cni.dev/plugins/current/meta/portmap/

Rootless mode can create `ss`-visible ports.

**Comment by Congee** [comment]
`ss` has to use (be used in) the isolated network namespace. Say if you have redis is started by nerdctl and want to see the default 6379 port, `sudo nsenter --net --target $(pidof redis-server) ss --listening --tcp --numeric` might help
