### ISSUE TITLE
How to delete these images?

### ISSUE THREAD

**Issue by offSwitch** [containerd/nerdctl#555]
![image](https://user-images.githubusercontent.com/11695496/142973249-09146bc6-1e63-4120-8847-ccc4aed3d06e.png)
![image](https://user-images.githubusercontent.com/11695496/142973313-d7173627-6d95-4f28-b1ea-b933c1be8f62.png)

**Comment by AkihiroSuda** [comment]
Please try `nerdctl -n k8s.io rim 00481181 cdbf75e1`

**Comment by offSwitch** [comment]
> nerdctl -n k8s.io rmi 00481181 cdbf75e1
![image](https://user-images.githubusercontent.com/11695496/142977396-ac768f7e-c1b0-467a-92c9-e4a199a1bdd0.png)

Doesn't look like what I was expecting
