### ISSUE TITLE
verifying the images by using cosign during the image pulling

### ISSUE THREAD

**Issue by Dentrax** [containerd/nerdctl#577]
Follow-up issue for #423

---

We can verify the images during the image pull since we will be able to signing it using keyless mode at PR #556. If it makes sense, we can (@developer-guy) implement this feature in the same branch!

**Comment by AkihiroSuda** [comment]
SGTM, left comments in https://github.com/containerd/nerdctl/pull/556#discussion_r758953499

**Comment by AkihiroSuda** [comment]
Could you propose this to BuildKit (https://github.com/moby/buildkit/issues) too, so that we can verify Dockerfile `FROM` images in `nerdctl build` and `nerdctl compose up --build`?

**Comment by AkihiroSuda** [comment]
Closing, as this is implemented in v0.15
https://github.com/containerd/nerdctl/blob/master/docs/cosign.md
