### ISSUE TITLE
/dev/shm support is broken (Was: `What options does the --tmpfs flag in the run statement allow`)

### ISSUE THREAD

**Issue by doberkofler** [containerd/nerdctl#594]
I'm trying to a run an Oracle  Database in a Docker image in a lima environment on macOS and get a lot of errors related to the shm volume.

```bash
lima nerdctl run --detach --name="oracledb" --network="oraclenet" --memory="4g" --publish="1521:1521" --volume="/dev/shm" --tmpfs="/dev/shm:rw,exec,size=1g" qualiant/database
```

As there is no specific documentation, I wanted to ask a few specific questions:

1) Does `nerdctl` all the options `--tmpfs="/dev/shm:rw,exec,size=1g"` in the `--tmpfs` flag ?
2) `nerdctl` support the `--memory` option but how does this relate to lima? Is it guaranteed that the container gets 4g when using the `--memory` flag independently from lima?

Thank you!

**Comment by doberkofler** [comment]
After some more testing , it seems as if at least the `exec` would option not be observed when using
`--tmpfs="/dev/shm:rw,exec,size=1g"`

**Comment by AkihiroSuda** [comment]
1. All the tmpfs options are supported, however, there seems to be a bug specific to `/dev/shm` path, as nerdctl mounts its own `/dev/shm` 
```
$ nerdctl run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts
shm /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=65536k,uid=1001,gid=1001,inode64 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,uid=1001,gid=1001,inode64 0 0

$ docker run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,inode64 0 0
```
(nerdctl v0.14.0)

2. Unrelated. Lima memory is an amount of QEMU memory (which looks like the physical memory to the Linux guest), and nerdctl memory is just cgroup memory limits.

**Comment by doberkofler** [comment]
@AkihiroSuda Thank you for your very helpful feedback. Do you expect this problem to be fixed in the near future?

**Comment by doberkofler** [comment]
@AkihiroSuda I would be most appreciated, if you could give some update on this bug.

**Comment by Junnplus** [comment]
@doberkofler I tried to fix this, but I don't have an oracle/database image to verify that works :(

**Comment by doberkofler** [comment]
> @doberkofler I tried to fix this, but I don't have an oracle/database image to verify that works :(

I can test it when a version becomes available.

**Comment by doberkofler** [comment]
@AkihiroSuda Will the fix in nerdctl be available in the next release of lima?

**Comment by AkihiroSuda** [comment]
Yes, in a few days, but upgrading Lima does not automatically upgrade nerdctl in existing Lima instances, so you will have to either recreate the Lima instance, or just overwrite `/usr/local/bin/nerdctl` in the existing instance with the newer version of `nerdctl` binary.

**Comment by Junnplus** [comment]
@doberkofler An easy way to help you build from source: 
```
make nerdctl && sudo make install
```

**Comment by doberkofler** [comment]
@Junnplus I've just downloaded the latest version of lima (0.8.2) and upgraded nerdctl (0.16.1) and run my tests again but unfortunately the Installation of natively compiled code in an Oracle Database still fails in a lima/nerdctl container.

I'm starting my Oracle container using:
```
lima nerdctl run --detach --name="oracledb" --memory="4g" --publish="31521:1521" --volume="/dev/shm" --tmpfs="/dev/shm:rw,exec,size=1g" oracle/database-prebuild:19.3.0-se2
```

and get an error:
```
ORA-00600: internal error code, arguments: [pesldl02_Make_Object: shm_open failed: errno 13 errmsg Permissio], [/PESLD_ORCLCDB_3_f0d63c6400000000], [], [], [], [], [], [], [], [], [], []
```

that according to the Oracle Tech Support is related to an error in `tmpfs` device, but when checking the new version independently from Oracle it seems as if the problem has been resolved:

```sh
/ $ lima nerdctl run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,uid=501,gid=1000,inode64 0 0
/ $ docker run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k 0 0
```

When running the exact same container on Docker everything works as expected.

Maybe there is some other problem. Any help would be greatly appreciated.

**Comment by fahedouch** [comment]
looks like it is related to lima;  lima add `uid=501,gid=1000` to the mount so you are not mouting `/dev/shm` as user `0` and you need be user `0 to open shm 

```
nerdctl run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k 0 0
``` 

```
lima nerdctl run --rm --tmpfs="/dev/shm:rw,exec,size=1g,uid=1,gid=1" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,uid=100000,gid=100000,inode64 0 0
````
I assume that lima using vm user to make this mount which is logic, but When I tried to force user 0 , it dosen't wort

```
lima nerdctl run --rm --tmpfs="/dev/shm:rw,exec,size=1g,uid=0,gid=0" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,uid=501,gid=1000,inode64 0 0
```
WDYT @AkihiroSuda  @Junnplus  ?

**Comment by doberkofler** [comment]
@AkihiroSuda @Junnplus Can this issue be reopened this problem or should I open a new one?

**Comment by Junnplus** [comment]
@doberkofler Your docker should be in rootful mode, correspondingly you should try the rootful mode of nerdctl.

```
$ sudo docker run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,inode64 0 0
$ docker run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,uid=501,gid=1000,inode64 0 0
$ sudo nerdctl run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,inode64 0 0
$ nerdctl run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts
tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,uid=501,gid=1000,inode64 0 0
```

Set `containerd.systemd` to true to enable rootful containerd.
https://github.com/lima-vm/lima/blob/v0.8.2/pkg/limayaml/default.yaml#L89

**Comment by doberkofler** [comment]
@Junnplus Thank you for he feedback, but I'm not sure I understand.

I have tried just changing the `containerd.system` option in the `default.yaml` file but it did not make a difference when trying to run the Oracle Database.

Could you elaborate on what the problem might be or what I'm doing wrong?

When trying to run `sudo lima nerdctl run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts` the error `FATA[0000] must not run as the root` is shown.

Running `lima nerdctl run --rm --tmpfs="/dev/shm:rw,exec,size=1g" alpine grep /dev/shm /proc/mounts` shows `tmpfs /dev/shm tmpfs rw,nosuid,nodev,relatime,size=1048576k,uid=501,gid=1000,inode64 0 0`.

**Comment by Junnplus** [comment]
@doberkofler Try the following steps:
1. Set `containerd.system` to true.
2. And restart lima instance: `limactl stop` && `limactl start`.
3. Using `lima sudo nerdctl run ...` to instead of `lima nerdctl run ...`.

**Comment by doberkofler** [comment]
@Junnplus Thank you for all your help and sorry for being of so little help!

1) I've changed `default.yaml` used limactl start and stop.

```yaml
containerd:
  # Enable system-wide (aka rootful)  containerd and its dependencies (BuildKit, Stargz Snapshotter)
  # Default: false
  system: true
  # Enable user-scoped (aka rootless) containerd and its dependencies
  # Default: true
  user: null
```

Is there way to check if the "rootful" mode is activated?
I actually also had to import the `oracle/database-prebuild:19.3.0-se2` image again after changing the setting. Is this normal? 

2) This is how I start the Oracle database in the container 
```
lima sudo nerdctl run --detach --name="oracledb" --memory="4g" --publish="31521:1521" --volume="/dev/shm" --tmpfs="/dev/shm:rw,exec,size=1g" oracle/database-prebuild:19.3.0-se2
```

3) Unfortunately I still get the same error message when trying to compile to native in the Oracle Database

```
* ORA-00600: internal error code, arguments: [pesldl02_Make_Object: shm_open failed: errno 13 errmsg Permissio], [/PESLD_ORCLCDB_3_6030696600000000], [], [], [], [], [], [], [], [], [], []
```

**Comment by Junnplus** [comment]
> Is there way to check if the "rootful" mode is activated?
Run `lima sudo nerdctl info` successfully.

> I actually also had to import the oracle/database-prebuild:19.3.0-se2 image again after changing the setting. Is this normal?
Yes.

I using [oracle docker image](https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/samples/prebuiltdb) and  tried to reproduce this error but it works.

**Comment by doberkofler** [comment]
@Junnplus The error only appears when Oracle uses the tmpfs device to (for example) [compile natively](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/FAQ.md#ora-00600-internal-error-code-arguments-pesldl03_mmap-errno-1-errmsg-operation-not-permitted-----------).
