### ISSUE TITLE
proposal: support namespace switch command

### ISSUE THREAD

**Issue by junnplus** [containerd/nerdctl#624]
Switching between multiple namespaces is cumbersome.
Support switching namespace commands to make it easier for users to use.
- `nerdctl namespace switch <ns>` switch to the specified namespace
- `nerdctl namespace switch -` switch to the previous context

**Comment by AkihiroSuda** [comment]
Perhaps `nerdctl namespace use`, or `nerdctl context use`, to mimic `docker context use`
https://docs.docker.com/engine/reference/commandline/context_use/

**Comment by Junnplus** [comment]
@AkihiroSuda `namespace use` is OK, `nerdctl context use` is best to be consistent with `docker context use`.

**Comment by Junnplus** [comment]
maybe need https://github.com/containerd/nerdctl/pull/470

**Comment by fahedouch** [comment]
`namespace` should be related to `context` , `nerdctl context use` makes more sense to switch namespace ; 

this can be sthg like this:
`nerdctl context create context1 --namespace=ns1`
and then to switch to `ns1` : 
`nerdctl context use context1`
