### ISSUE TITLE
Add Windows image build  

### ISSUE THREAD

**Issue by stowel** [containerd/nerdctl#627]
Because of announced changes of the [Windows Container Runtime](https://techcommunity.microsoft.com/t5/containers/updates-to-the-windows-container-runtime-support/ba-p/2788799) in September 2022, we are looking for a way to replace docker engine with containerd and nertdctl on Windows. Our solutions are based on windows images, therefor we need a possibility to build Windows Images. 

If there is already an ongoing dicussion on this topic or a technical hint why this is not possible, I was unfortunately unable to find any information on this. 

![image](https://user-images.githubusercontent.com/3041802/146243047-c0f3b40b-74f9-4568-a8e1-43772b976b9d.png)

**Comment by jsturtevant** [comment]
Technically possible to do but doesn't currently work.  Work is in progress to add support in buildkit and related projects but currently blocked.  The support for buildkit is being tracked: https://github.com/microsoft/Windows-Containers/issues/34

We can use buildx to build Windows images today, but comes with limitations like no RUN commands, no registry edits, and others so isn't likely going to meet the same requirements you have for building  a majority of windows containers and only works on Linux hosts I beleive.

**Comment by jsturtevant** [comment]
fyi @weijuans-msft

**Comment by slonopotamus** [comment]
I'd like to shamelessly suggest looking at my [Stevedore](https://github.com/slonopotamus/stevedore) project as a free way to continue to use Docker engine on Windows without relying on `DockerMsftProvider` or Mirantis paid offering.
