### ISSUE TITLE
Support prune command for images, containers, volumes and system

### ISSUE THREAD

**Issue by mcekovic** [containerd/nerdctl#648]
Nerdctl is a great tool, but when used for experimenting it is often needed to quickly delete the remains of experiments.
Support for:
- nerdctl image prune (--all --force)
- nerdctl container prune (--force)
- nerdctl volume prune (--force)
- nerdctl system prune  (--all --force --volumes)

like in Docker would much help.

**Comment by AkihiroSuda** [comment]
SGTM, but needs to make sure:

- Non-nerdctl objects must not be pruned
- `nerdctl system prune` should not prune networks because networks are not namespaced objects

**Comment by AkihiroSuda** [comment]
Alternatively we can just have `nerdctl namespace rm` and call it a day.

**Comment by mcekovic** [comment]
`nerdctl namespace rm` seems could do the job and is probably easier to implement.

**Comment by AkihiroSuda** [comment]
https://github.com/containerd/nerdctl/releases/tag/v0.22.0

nerdctl v0.22.0 supports `nerdctl image prune --all`, `nerdctl container prune`, and `nerdctl volume prune`.
No support for `nerdctl network prune` and `nerdctl system prune` yet though.

**Comment by junnplus** [comment]
`nerdctl network prune` and `nerdctl system prune` already support and should be released in v0.22.1.
