### ISSUE TITLE
Encrypted image could be run as key removed

### ISSUE THREAD

**Issue by lannyyip** [containerd/nerdctl#654]
nerdctl version : 0.15.0

Steps to reproduce:
1. install full version of nerdctl to `/usr/local`
2. generate key and public key as instructed.
3. use public key to encrypt image
4. delete keys
5. run the image
the detailed log is shown below:

weizhi@weizhivm:~/rkeys$ sudo nerdctl images
REPOSITORY    TAG       IMAGE ID        CREATED           PLATFORM       SIZE
nginx         alpine    12aa12ec4a8c    42 minutes ago    linux/amd64    26.2 MiB
weizhi@weizhivm:~/rkeys$ ls
mykey.pem  mypubkey.pem
weizhi@weizhivm:~/rkeys$ sudo nerdctl image encrypt --recipient=jwe:mypubkey.pem --platform=linux/amd64 nginx:alpine nginx:encrypted
sha256:c9437e2bf0654a94c834c20d931609d6bb67e798fa08e68e30ed1863f58db220
weizhi@weizhivm:~/rkeys$ sudo nerdctl images
REPOSITORY    TAG          IMAGE ID        CREATED           PLATFORM       SIZE
nginx         alpine       12aa12ec4a8c    43 minutes ago    linux/amd64    26.2 MiB
nginx         encrypted    c9437e2bf065    4 seconds ago     linux/amd64    26.2 MiB
weizhi@weizhivm:~/rkeys$ rm *
weizhi@weizhivm:~/rkeys$ sudo nerdctl run nginx:encrypted
WARN[0000] kernel support for cgroup blkio weight missing, weight discarded 
time="2021-12-29T03:13:37.591522168Z" level=info msg="starting signal loop" namespace=default path=/run/containerd/io.containerd.runtime.v2.task/default/79bbb7ea88f4b0d22fd86ab0bccd8513623abe93600e6e9b1f963bfbc045d235 pid=8228
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2021/12/29 03:13:37 [notice] 1#1: using the "epoll" event method
2021/12/29 03:13:37 [notice] 1#1: nginx/1.21.4
2021/12/29 03:13:37 [notice] 1#1: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424) 
2021/12/29 03:13:37 [notice] 1#1: OS: Linux 5.4.0-91-generic
2021/12/29 03:13:37 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1024:1024
2021/12/29 03:13:37 [notice] 1#1: start worker processes
2021/12/29 03:13:37 [notice] 1#1: start worker process 32
2021/12/29 03:13:37 [notice] 1#1: start worker process 33
2021/12/29 03:13:37 [notice] 1#1: start worker process 34
2021/12/29 03:13:37 [notice] 1#1: start worker process 35

Expected result:
Encryped image could not be run if the key is not exited.

**Comment by AkihiroSuda** [comment]
Expected behavior.
Encryption does not affect local images.

**Comment by lannyyip** [comment]
> Expected behavior. Encryption does not affect local images.

Thank you for quick response. Is there any plan to support local image encryption? Or any concern not implementing this support?
As I know imgcrypt support local image encryption. Thank you.

**Comment by lannyyip** [comment]
> Expected behavior. Encryption does not affect local images.

I am a bit confused, I tried to encrypt the image direct from docker.io, but it is promted that image is not exited. So I have to pull before encrypt.

weizhi@weizhivm:~/keys$ sudo nerdctl image list
REPOSITORY    TAG    IMAGE ID    CREATED    PLATFORM    SIZE
weizhi@weizhivm:~/keys$ sudo nerdctl image encrypt --recipient=jwe:mypubkey.pem --platform=linux/amd64 nginx:latest nginx:encrypted
FATA[0000] image "docker.io/library/nginx:latest": not found 
weizhi@weizhivm:~/keys$ sudo nerdctl image pull nginx:latest

**Comment by joaopfg** [comment]
@AkihiroSuda  Why encryption does not affect local images ? In my use case, I need to protect my local images from access by other people that use the same computer later. So I would need that encryption affects local images. I would like to try a PR myself to support it since I need it a bit urgently. Could you kindly indicates me in what place of the source code this feature would fit better, please ?

**Comment by AkihiroSuda** [comment]
"does not affect local images" was slightly incorrect; local image blobs are affected but already-unpacked local image snapshots are not affected.

I'd rather suggest to use rootless mode for hiding your local images from other users on the same host.
