### ISSUE TITLE
Provide binary for nerdctl-compose

### ISSUE THREAD

**Issue by romanimm** [containerd/nerdctl#655]
Many existing tools assume that docker and docker-compose are two different tools (binaries). To migrate from docker to nerdctl it would be easier if nerdctl would provide two binaries as well.
This would mean a separat `nerdctl-compose` binary which would just call `nerdctl compose`.

**Comment by AkihiroSuda** [comment]
You can create by yourself

```bash
#!/bin/sh
set -eu
exec nerdctl compose “$@“
```
