### ISSUE TITLE
Add support for mirrors

### ISSUE THREAD

**Issue by sathieu** [containerd/nerdctl#668]
`containerd` can use mirrors., but as the [FAQ tells](https://github.com/containerd/nerdctl/blob/master/docs/faq.md#nerdctl-ignores-pluginsiocontainerdgrpcv1cri-config):

> ### nerdctl ignores `[plugins."io.containerd.grpc.v1.cri"]` config
> 
> Expected behavior, because nerdctl does not use CRI (Kubernetes Container Runtime Interface) API.
> 
> See the questions below for how to configure nerdctl.

How to configure registry mirrors in nerdctl?

( Triggered by https://github.com/kubernetes-sigs/kubespray/issues/8375).

(NB: this is similar to older issue #199)

**Comment by AkihiroSuda** [comment]
PR:
- https://github.com/containerd/nerdctl/pull/642

**Comment by sathieu** [comment]
@AkihiroSuda Looking at the code, it does'nt support:

```toml
#$ sudo cat /etc/containerd/certs.d/quay.io/hosts.toml
# server = "https://quay.io"

[host."https://gitlab-registry.k8s.example.org/v2/external-registries/quay.io"]
  capabilities = ["pull", "resolve"]
  override_path = true
```

Does it?

**Comment by AkihiroSuda** [comment]
Implemented in PR https://github.com/containerd/nerdctl/pull/642 , but not merged yet
