### ISSUE TITLE
Refactor pkg/netutil to support more network parameters

### ISSUE THREAD

**Issue by Junnplus** [containerd/nerdctl#671]
https://github.com/containerd/nerdctl/blob/master/pkg/netutil/netutil_unix.go#L37-L56

Now the cni plugin is generated through a fixed template, it is difficult to be extended to support more network parameters, like `--ip-range`.

I think we can refactor it in the follow way:
```go
const ConfigListTemplate = `{
  "cniVersion": "0.4.0",
  "name": "{{.Name}}",
  "nerdctlID": {{.ID}},
  "nerdctlLabels": {{.Labels}},
  "plugins": {{.Plugins}}
}`

type ConfigListTemplateOpts struct {
	ID      int
	Name    string // e.g. "nerdctl"
	Labels  string // e.g. `{"version":"1.1.0"}`
	Plugins string
}

func GenerateConfigList(e *CNIEnv, labels []string, id int, name, cidr string) (*NetworkConfigList, error) {
...
    	plugins := []CNIPlugin{bridge, NewPortMapPlugin()...]
    	pluginJson, err := json.Marshal(plugins)
	if err != nil {
		return nil, err
	}

}
```

**Comment by fahedouch** [comment]
I assume that is the strict that we should have. you extends 
 plugin list with custom plugin using `ExtraPlugins` https://github.com/containerd/nerdctl/blob/7b9a9aacdb15f5ea163fc46b91410b02c0f00361/pkg/netutil/netutil_unix.go#L68

**Comment by Junnplus** [comment]
> I assume that this is the default conf that we should have. you can extends
plugin list with custom plugin using ExtraPlugins

Like `nerdctl network create --ip-range xxx`, Should take effect on the first bridge plugin.
