### ISSUE TITLE
[OpenVZ] mount failed when run container (`failed to mount /run/user/0/containerd-mount1714843215: operation not permitted`)

### ISSUE THREAD

**Issue by LGinC** [containerd/nerdctl#690]
```bash
root@srv26350:/run/user# nerdctl run --rm -it alpine
FATA[0068] failed to mount /run/user/0/containerd-mount1714843215: operation not permitted
root@srv26350:/run/user# ls -l
total 0
drwx--x--x 4 root root 80 Jan 11 02:52 0
```

**Comment by AkihiroSuda** [comment]
Please provide `nerdctl info` and `nerdctl version`

**Comment by LGinC** [comment]
```bash
root@srv26350:~# nerdctl info
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.5.8
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Log: json-file
  Storage: native overlayfs
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.123-1.el7.elrepo.x86_64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 976.6MiB
 Name: srv26350
 ID: e9dd9914-9165-437c-acf0-e27f2877459f
```

```bash
root@srv26350:~# nerdctl version
Client:
 Version:       v0.15.0
 Git commit:    b72b5ca14550b2e23a42787664b6182524c5053f

Server:
 containerd:
  Version:      v1.5.8
  GitCommit:    1e5ef943eb76627a6d3b6de8cd1ef6537f393a71

```

**Comment by AkihiroSuda** [comment]
```
> Kernel Version: 5.4.123-1.el7.elrepo.x86_64
> Operating System: Debian GNU/Linux 10 (buster)
```

Are you running a Debian 10 container on CentOS 7?
Then you have to run the container with `--privileged` (for Kubernetes `securityContext.privileged: true`)

**Comment by LGinC** [comment]
> ```
> > Kernel Version: 5.4.123-1.el7.elrepo.x86_64
> > Operating System: Debian GNU/Linux 10 (buster)
> ```
> 
> Are you running a Debian 10 container on CentOS 7? Then you have to run the container with `--privileged` (for Kubernetes `securityContext.privileged: true`)

not centos, another server, just user root
`--privileged` not work
```bash
root@srv26350:~# nerdctl run --rm -it --privileged alpine

FATA[0066] failed to mount /run/user/0/containerd-mount2067442936: operation not permitted

```

**Comment by AkihiroSuda** [comment]
> not centos

Why are you running Debian userspace with "el7" kernel?
You might be using Virtuozzo or OpenVZ ? Or another container engine?

> --privileged not work

You have to run the "host" OS in privileged mode (assuming your host is running inside a container)

**Comment by LGinC** [comment]
> > not centos
> 
> Why are you running Debian userspace with "el7" kernel? You might be using Virtuozzo or OpenVZ ? Or another container engine?
> 
> > --privileged not work
> 
> You have to run the "host" OS in privileged mode (assuming your host is running inside a container)

a virtual server in [euserv](https://www.euserv.com/en/virtual-private-server/index.php),based on OpenVZ / Virtuozzo

**Comment by AkihiroSuda** [comment]
> a virtual server in euserv,based on OpenVZ / Virtuozzo

Unsupported. Please use a real VM.
