### ISSUE TITLE
[enhancement] support the `--mount` option

### ISSUE THREAD

**Issue by tarfeef101** [containerd/nerdctl#713]
To further increase the UI/UX parity with `Docker`, supporting the `--mount` flag would help towards that, trying to evaluate options to move away from `Docker for Desktop`, and we've got internal script, etc. using that option which fail when using `nerdctl` due to the presence of `--mount` in `docker run`, etc. commands. 

Plus, as described [here](https://docs.docker.com/storage/bind-mounts/#choose-the--v-or---mount-flag), it does provide different options/features vs `--volume`, and looking at recent issues some like non-bind-mount types (e.g. `tmpfs`) are coming, or at least requested?

**Comment by liubin** [comment]
@AkihiroSuda @tarfeef101 I just evaluated it, can I take this issue?

**Comment by AkihiroSuda** [comment]
Yes plz

**Comment by liubin** [comment]
@AkihiroSuda can this be closed since https://github.com/containerd/nerdctl/pull/801 has been merged.
