### ISSUE TITLE
`nerdctl inspect` faild to  get {{.Id}} but `docker` did

### ISSUE THREAD

**Issue by tanguofu** [containerd/nerdctl#736]
[root@VM-141-67-centos ~]# nerdctl inspect registry:latest  --format '{{.Id}}'
FATA[0000] template: :1:2: executing "" at <.Id>: can't evaluate field Id in type *dockercompat.Image 
[root@VM-141-67-centos ~]# docker inspect registry:latest  --format '{{.Id}}'
sha256:b8604a3fe8543c9e6afc29550de05b36cd162a97aa9b2833864ea8a5be11f3e2

**Comment by AkihiroSuda** [comment]
Workaround: `nerdctl image inspect docker.io/library/alpine:latest | jq -r .[0].Id` 
(This works for `docker` too)

**Comment by tanguofu** [comment]
> 

ok ， thanks very much！

**Comment by AkihiroSuda** [comment]
Fixed in https://github.com/containerd/nerdctl/pull/743
