### ISSUE TITLE
ACR login 400

### ISSUE THREAD

**Issue by Junnplus** [containerd/nerdctl#737]
> > Looks like an issue with the aliyun registry service, but `docker login` is working.
> 
> I'm seeing the same issue with the Azure container registry (ACR). Login via docker / moby works.

I'm facing the same issue with ACR. Have cloned and built nerdctl on my env, after #718 merge, and it's still not working for me at least.

_Originally posted by @paulorpdlitss in https://github.com/containerd/nerdctl/issues/717#issuecomment-1022709071_

**Comment by Junnplus** [comment]
```
N] ❯ nerdctl login junnplus.azurecr.io -u junnplus --debug
Enter Password:
DEBU[0002] Ignoring hosts dir "/etc/containerd/certs.d"  error="stat /etc/containerd/certs.d: no such file or directory"
DEBU[0002] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0002] len(regHosts)=1
DEBU[0003] no scope specified for token auth challenge   host=junnplus.azurecr.io
DEBU[0003] token request failed                          body= status="400 Bad Request"
ERRO[0003] failed to call tryLoginWithRegHost            error="failed to call rh.Authorizer.Authorize: failed to fetch oauth token: unexpected status: 400 Bad Request" i=0
FATA[0003] failed to call rh.Authorizer.Authorize: failed to fetch oauth token: unexpected status: 400 Bad Request
```

**Comment by Junnplus** [comment]
https://github.com/Azure/acr/blob/main/docs/Token-BasicAuth.md
ACR use GET method to fetch access token.

and containerd use POST request.
https://github.com/containerd/containerd/blob/main/remotes/docker/auth/fetch.go#L98

**Comment by Junnplus** [comment]
https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md#calling-post-oauth2token-to-get-an-acr-access-token
Calling POST /oauth2/token to get an ACR access token

**Comment by AkihiroSuda** [comment]
@Junnplus Thanks for looking into this

> ACR use GET method to fetch access token.

Do we have to add `|| errStatus.StatusCode == 400` check here?

https://github.com/containerd/containerd/blob/3f5d789dfb30410df18d0cedbec94f519c480392/remotes/docker/authorizer.go#L314

**Comment by Junnplus** [comment]
> Do we have to add || errStatus.StatusCode == 400 check here?

@AkihiroSuda Thank for advice, I tested locally and it worked, I will make a patch to containerd later.

**Comment by paulorpdlitss** [comment]
Have downloaded and built my own version with @Junnplus fix on containerd/containerd#6481, but i'm still getting errors.

After adding some debugging lines on containerd/containerd, they allow me to find that the second request to oauth is going without a username, so the access_token received from the first call is not working. After changing login.go, loginClientSide, to also return auth.Username when using IdentityToken, it works for me. 
https://github.com/containerd/nerdctl/blob/2f0cf7586ed6763df2a6252d6f97d5512f8fc2f4/cmd/nerdctl/login.go#L218

**Comment by Junnplus** [comment]
> Have downloaded and built my own version with @Junnplus fix on containerd/containerd#6481, but i'm still getting errors.

I can't reproduce this, for me it was working. 

```
[N] ❯ nerdctl login junnplus.azurecr.io -u junnplus --debug
Enter Password:
DEBU[0004] Ignoring hosts dir "/etc/containerd/certs.d"  error="stat /etc/containerd/certs.d: no such file or directory"
DEBU[0004] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0004] len(regHosts)=1
DEBU[0005] no scope specified for token auth challenge   host=junnplus.azurecr.io
DEBU[0005] Ignoring hosts dir "/etc/containerd/certs.d"  error="stat /etc/containerd/certs.d: no such file or directory"
DEBU[0005] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0005] len(regHosts)=1
DEBU[0006] no scope specified for token auth challenge   host=junnplus.azurecr.io
Login Succeeded
```

and push image sucessful.

**Comment by paulorpdlitss** [comment]
I was not using username/password but `az acr login --expose-token` access token, where username is `00000000-0000-0000-0000-00000000000`

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Junnplus** [comment]
> I was not using username/password but `az acr login --expose-token` access token, where username is `00000000-0000-0000-0000-00000000000`

Thanks, this is a useful information.

**Comment by Junnplus** [comment]
@paulorpdlitss Hi, 400 issue should be fixed by https://github.com/containerd/nerdctl/pull/753, I'll close this issue first.
