### ISSUE TITLE
host.docker.internal equivalent

### ISSUE THREAD

**Issue by endlesslycurious** [containerd/nerdctl#747]
Hello,

I've been porting over a micro service stack from running docker desktop to nerdctl, its gone pretty smoothly but I've hit a snag in one of our use cases where we've been using the special `host.docker.internal` dns name that [resolves to the IP of the host](https://docs.docker.com/desktop/windows/networking/#use-cases-and-workarounds) on docker desktop for Windows.

For example with our backend database and task executors running in containers the task executors can still communicate with the service process using the `host.docker.internal` DNS name. This is useful during development as it lets us run the service from an IDE with debugger attached..

Is there an existing equivalent to `host.docker.internal` available? I had a search around and didn't find anything..

Cheers!

**Comment by midhunkrishna** [comment]
From lima docs. 

> The loopback addresses of the host is 192.168.5.2 and is accessible
> from the guest as host.lima.internal.

So instead of providing host.docker.internal, you can provide `192.168.5.2`

I have tested this with nerdctl distributed via Rancher and works!

reference: https://github.com/lima-vm/lima/blob/master/docs/network.md

**Comment by Junnplus** [comment]
Thanks @midhunkrishna
