### ISSUE TITLE
ACR oauth login without username

### ISSUE THREAD

**Issue by Junnplus** [containerd/nerdctl#755]
Have downloaded and built my own version with @Junnplus fix on containerd/containerd#6481, but i'm still getting errors.

After adding some debugging lines on containerd/containerd, they allow me to find that the second request to oauth is going without a username, so the access_token received from the first call is not working. After changing login.go, loginClientSide, to also return auth.Username when using IdentityToken, it works for me. 
https://github.com/containerd/nerdctl/blob/2f0cf7586ed6763df2a6252d6f97d5512f8fc2f4/cmd/nerdctl/login.go#L218

_Originally posted by @paulorpdlitss in https://github.com/containerd/nerdctl/issues/737#issuecomment-1023501850_

**Comment by paulorpdlitss** [comment]
Looking on how podman implementation do the login to ACR, they sent the username as an query parameter called account, like this:

https://paulorpdl.azurecr.io/oauth2/token?account=00000000-0000-0000-0000-000000000000&service=paulorpdl.azurecr.io

**Comment by fahedouch** [comment]
the fact that we are doing a double connection causes it to visit this line  which is not valid  https://github.com/containerd/nerdctl/blob/2f0cf7586ed6763df2a6252d6f97d5512f8fc2f4/cmd/nerdctl/login.go#L218 
 based on the description in this ticket https://github.com/containerd/nerdctl/issues/755

**Comment by flyinprogrammer** [comment]
not sure if this is helpful, but I can also validate that oauth login to azure is still broken. i just spent this evening 🤞 that 0.16.1 had this oauth login fixed, it does not, which now i see is a known issue 🤦

**Comment by Junnplus** [comment]
Fixed by #774
