### ISSUE TITLE
[`nerdctl.lima`] nerdctl is  chocking on newlines on     nerdctl run

### ISSUE THREAD

**Issue by jdblack** [containerd/nerdctl#769]
OS: MacOSX  11.6.2 (Big Sur)
Version: lima 0.8.1

I was attempting to use nercdtl to run a  build container from the go-carbon project ( https://github.com/go-graphite/go-carbon/blob/master/packages.sh  )  via a symlink from  /usr/local/bin/nerdctl.lima  to ~/bin/docker.  nerdctl, however , fails  on the multi-line command. It appears to me that the backslash for newline is somehow getting eaten up

```
~/go-carbon$ ./packages.sh
++ dirname ./packages.sh
+ cd .
+ ROOT=/Users/jblackwell/go-carbon
+ docker run -ti --rm -v /Users/jblackwell/go-carbon:/root/go/src/github.com/go-graphite/go-carbon ubuntu:20.04 bash -c '
    cd /root/
    export GO_VERSION=1.14
    apt-get update
    apt-get install -y rpm ruby ruby-dev wget make git gcc

    wget https://dl.google.com/go/go.linux-amd64.tar.gz
    tar -C /usr/local -xzf go.linux-amd64.tar.gz
    ln -s /usr/local/go/bin/go /usr/local/bin/go

    # newer fpm is broken https://github.com/jordansissel/fpm/issues/1612
    gem install rake
    gem install fpm:1.10.2

    go get github.com/mitchellh/gox
    ln -s /root/go/bin/gox /usr/local/bin/gox

    cd /root/go/src/github.com/go-graphite/go-carbon

    make gox-build
    make fpm-deb
    make fpm-rpm
'
bash: n: command not found


```

**Comment by AkihiroSuda** [comment]
Is this an issue of nerdctl or lima?
What if you execute `nerdctl` directly, inside the `lima` shell?

**Comment by buu700** [comment]
I'm running into this as well (currently a blocker). It looks like it isn't newlines specifically; seems to also apply to tabs, backslashes, dollar signs, and likely other special or escaped characters.

**Comment by AkihiroSuda** [comment]
Seems an issue of `lima`, not `nerdctl`: https://github.com/lima-vm/lima/issues/632

Linux-native nerdctl doens't seem to have the issue:
```
$ nerdctl run debian bash -c "$(echo -e '\n\techo balls\n')"
balls

$ nerdctl -v
nerdctl version 0.16.1
```

**Comment by AkihiroSuda** [comment]
Locking this issue to avoid side discussion, but please feel free to continue discussion in https://github.com/lima-vm/lima/issues/632 

Thanks!
