### ISSUE TITLE
[Linux] --insecure-registry option not works for some circumstances 

### ISSUE THREAD

**Issue by Zheaoli** [containerd/nerdctl#775]
For example, I have a docker registry with the hostname `registry.manjusaka.me`. I just open 80 port to support normal HTTP, not HTTPS. And now if I use `nerdctl --insecure-registry=true push registry.manjusaka.me/demo:v0.1` to push the image. There will be an error here bellow

```text
failed to do request: Head "xxxx": dial tcp x.x.x:443: connect: connection refused
```

I think the root cause is here

https://github.com/containerd/nerdctl/blob/master/cmd/nerdctl/push.go#L186

The `IsErrHTTPResponseToHTTPSClient` will check the error message is `server gave HTTP response to HTTPS client` or not.

In the real environment, people may close the 443 port and only use the 80 port. I think we need compact with this situation.

**Comment by Ghostwritten** [comment]
me,too,
```
[root@bastion01 ~]# nerdctl --insecure-registry=true  push registry.demo:35000/envoyproxy/envoy:v1.22.5 
INFO[0000] pushing as a reduced-platform image (application/vnd.docker.distribution.manifest.list.v2+json, sha256:8fba6a3d40f33a7ee436bf02e1c5635211821efaed6644b3542b8b0cf82a2789) 
WARN[0000] skipping verifying HTTPS certs for "registry.demo:35000" 
index-sha256:8fba6a3d40f33a7ee436bf02e1c5635211821efaed6644b3542b8b0cf82a2789:    waiting        |--------------------------------------| 
manifest-sha256:727d10228de2f9895f9dddb7c11883672f462db3744c56fd5c8d83e4afa81f55: waiting        |--------------------------------------| 
config-sha256:e9c4ee2ce7207ce0f446892dda8f1bcc16cd6aec0c7c55d04bddca52f8af280d:   waiting        |--------------------------------------| 
elapsed: 0.3 s                                                                    total:   0.0 B (0.0 B/s)                                         
FATA[0000] failed to do request: Head "https://registry.demo:35000/v2/envoyproxy/envoy/blobs/sha256:7dcdb29d804aa1a6a09607656fc277b92ac7ba07df814cb2e340e5e45141a406": EOF 
[root@bastion01 ~]# nerdctl -v
nerdctl version 1.5.0

```

**Comment by fahedouch** [comment]
> me,too,
> 
> ```
> [root@bastion01 ~]# nerdctl --insecure-registry=true  push registry.demo:35000/envoyproxy/envoy:v1.22.5 
> INFO[0000] pushing as a reduced-platform image (application/vnd.docker.distribution.manifest.list.v2+json, sha256:8fba6a3d40f33a7ee436bf02e1c5635211821efaed6644b3542b8b0cf82a2789) 
> WARN[0000] skipping verifying HTTPS certs for "registry.demo:35000" 
> index-sha256:8fba6a3d40f33a7ee436bf02e1c5635211821efaed6644b3542b8b0cf82a2789:    waiting        |--------------------------------------| 
> manifest-sha256:727d10228de2f9895f9dddb7c11883672f462db3744c56fd5c8d83e4afa81f55: waiting        |--------------------------------------| 
> config-sha256:e9c4ee2ce7207ce0f446892dda8f1bcc16cd6aec0c7c55d04bddca52f8af280d:   waiting        |--------------------------------------| 
> elapsed: 0.3 s                                                                    total:   0.0 B (0.0 B/s)                                         
> FATA[0000] failed to do request: Head "https://registry.demo:35000/v2/envoyproxy/envoy/blobs/sha256:7dcdb29d804aa1a6a09607656fc277b92ac7ba07df814cb2e340e5e45141a406": EOF 
> [root@bastion01 ~]# nerdctl -v
> nerdctl version 1.5.0
> ```

it is not exactly the above error.
EOF" indicates that the client-side of the HTTP request encountered an "EOF" (End of File) error while trying to communicate with the server. Please check Network Connectivity: Ensure that that nerctl has a stable network connection and can reach the registry.
