### ISSUE TITLE
BASH completion failing with null byte error

### ISSUE THREAD

**Issue by jbaribeault** [containerd/nerdctl#780]
nerdctl 0.16.0 and 0.16.1 via Rancher Desktop 1.0.0 and 1.0.1 on Windows 11. 

WSL integrated into Ubuntu 18.04, 20.04 and Community Preview as well as home rolled Arch. All 4 yield same behavior.

```source <(nerdctl completion bash)```
or placing the result in /usr/share/bash-completion/completions/ 

Then typing
```nerdctl <TAB>```

Results in a bash error about command completion and a null byte:
```nerdctl -bash: warning: command substitution: ignored null byte in input```

**Comment by AkihiroSuda** [comment]
This might be an issue of Rancher Desktop's nerdctl wrapper, could you reopen https://github.com/rancher-sandbox/rancher-desktop/issues/1486 ?
