### ISSUE TITLE
nerdctl login fails (where docker login works)

### ISSUE THREAD

**Issue by gabor-lbl** [containerd/nerdctl#792]
Hello, I'm using rancher-desktop on a mac. nerdctl login fails against [portus](http://port.us.org/) v2.1.0-dev:

```
nerdctl login -u gtorok -p $PW xxxhostnamexxx --debug
WARN[0000] WARNING! Using --password via the CLI is insecure. Use --password-stdin.
DEBU[0000] Ignoring hosts dir "/etc/containerd/certs.d"  error="stat /etc/containerd/certs.d: no such file or directory"
DEBU[0000] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0000] len(regHosts)=1
DEBU[0000] no scope specified for token auth challenge   host=xxxhostnamexxx
ERRO[0000] failed to call tryLoginWithRegHost            error="failed to call rh.Authorizer.Authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized" i=0
FATA[0000] failed to call rh.Authorizer.Authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized
```

also fails against [harbor](https://goharbor.io/) (api v2.0):
```
nerdctl login -u gtorok xxxhostnamexxx --debug
Enter Password:
DEBU[0003] Ignoring hosts dir "/etc/containerd/certs.d"  error="stat /etc/containerd/certs.d: no such file or directory"
DEBU[0003] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0003] len(regHosts)=1
ERRO[0033] failed to call tryLoginWithRegHost            error="failed to call rh.Client.Do: Get \"https://xxxhostnamexxx/v2/\": dial tcp xxxipxxx:8443: i/o timeout" i=0
FATA[0033] failed to call rh.Client.Do: Get "https://xxxhostnamexxx:8443/v2/": dial tcp xxxipxxx:8443: i/o timeout
```

Docker login works against both of these. I'm not sure if this is a problem with rancher-desktop or the supplied version of nerdctl (0.16.1).

Thank you!

**Comment by Junnplus** [comment]
This seems to be two problems, the harbor's issue is duplicated with [773](https://github.com/containerd/nerdctl/issues/773).

**Comment by fahedouch** [comment]
the second error ([portus](http://port.us.org/)) is related to this https://github.com/containerd/nerdctl/pull/774
I am testing this PR in multiple registries, we will merge it very as soon as possible!

**Comment by Junnplus** [comment]
@gabor-lbl I think the harbor problem may be related to the configuration of your harbor server. `external_url` may be configured with an address of 8443.

**Comment by Junnplus** [comment]
> Could it be that is fixed in 0.16.1?

I'm not sure, you can upgrade and try again.

**Comment by hermitmaster** [comment]
I'm seeing a similar issue logging into a jfrog.io repo. docker-cli works fine in my case as well.
`nerdctl --version                                                 
nerdctl version 0.17.0`

**Comment by junnplus** [comment]
I closed it, feel free to reopen it if you still have problems.

**Comment by teksuo** [comment]
Hi, I'm facing this exact same problem with a private Gitlab registry. Docker also works without a problem for same user/pass. 

Currently using  Rancher Desktop 1.3.0 and nerdctl 0.19.0

`nerdctl login --debug` output:

`DEBU[0000] Ignoring hosts dir "/etc/containerd/certs.d"  error="stat /etc/containerd/certs.d: no such file or directory"
DEBU[0000] Ignoring hosts dir "/etc/docker/certs.d"      error="stat /etc/docker/certs.d: no such file or directory"
DEBU[0000] len(regHosts)=1                              
DEBU[0000] no scope specified for token auth challenge   host=registry.gitlab.com
ERRO[0000] failed to call tryLoginWithRegHost            error="failed to call rh.Authorizer.Authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized" i=0
FATA[0000] failed to call rh.Authorizer.Authorize: failed to fetch oauth token: unexpected status: 401 Unauthorized `
