### ISSUE TITLE
bypass4netns: "10.0.0.0/8" shouldn't be hardcoded

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#811]
> "10.0.0.0/8" shouldn't be hardcoded.
> But you may add a documentation about this and call it a day.
>
>Eventually, this should be passed from (equivalent of ) `nerdctl network list` and `nerdctl network inspect`.

_Originally posted by @AkihiroSuda in https://github.com/containerd/nerdctl/pull/808#discussion_r805558562_

**Comment by alegrey91** [comment]
@AkihiroSuda any news?

**Comment by AkihiroSuda** [comment]
Contribution is welcome.
The CIDR list should be fetched from the CNI configs.
