### ISSUE TITLE
rootless: run the puller/pusher in the host netns (but still in the userns)

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#814]
With the upcoming bypass4netns integration, rootless containers no longer needs to be slowed down with slirp, however, the puller and the pusher are still slowed down.

We should now look into possibility of running the puller/pusher in the host netns to avoid the slirp overhead.

**Comment by AkihiroSuda** [comment]
@fahedouch 

The idea is to add a new flag like `--detach-netns` to `rootlesskit`.
When this flag is specified, RootlessKit mounts the new NetNS to `$ROOTLESSKIT_STATE_DIR/netns` and launches slirp4netns (or pasta) for that netns, but leaves the command process in the host NetNS (w/ unshared UserNS and MountNS). 
nerdctl and BuildKit have to support running CNI in the `$ROOTLESSKIT_STATE_DIR/netns` namespace.

**Comment by fahedouch** [comment]
@AkihiroSuda 

> RootlessKit mounts the new NetNS to `$ROOTLESSKIT_STATE_DIR/netns`

* are you pointing to the new NetNS created by [unshare()](https://github.com/rootless-containers/rootlesskit/blob/master/pkg/parent/parent.go#L156) ? Or previously created netns (outside rootlesskit) which will be mounted when invoke `--detach-netns` and then passed to [slirp4netns](https://github.com/rootless-containers/rootlesskit/blob/master/pkg/network/slirp4netns/slirp4netns.go#L207) . I beleive that in this case we should drop [unshared](https://github.com/rootless-containers/rootlesskit/blob/master/pkg/parent/parent.go#L156)  NetNS , right ?

> launches slirp4netns (or pasta) for that netns, but leaves the command process (i.e., containerd) in the host NetNS  (w/ unshared UserNS and MountNS)

once we disable unsharing netns for [/proc/self/exec ](https://github.com/rootless-containers/rootlesskit/blob/master/pkg/parent/parent.go#L150) , process will run into new MountNS and new UserNS which are already [cloned](https://github.com/rootless-containers/rootlesskit/blob/master/pkg/parent/parent.go#L153) , So why should I unshare them ?

**Comment by AkihiroSuda** [comment]
>  are you pointing to the new NetNS created by [unshare()](https://github.com/rootless-containers/rootlesskit/blob/master/pkg/parent/parent.go#L156) ?

yes
