### ISSUE TITLE
credsHelper is replace by token login

### ISSUE THREAD

**Issue by fahedouch** [containerd/nerdctl#831]
Based in this issue https://github.com/containerd/nerdctl/issues/826 . The `credsHelper` login authConfig is replace by auth token after  a success `nerdctl login` which is not consistent whit docker login process

**Comment by Junnplus** [comment]
Fixed by https://github.com/containerd/nerdctl/pull/847

**Comment by fahedouch** [comment]
@Junnplus not sure but that seems to be unrelated, I will check this tomorrow :-)
