### ISSUE TITLE
[Rancher Desktop for Windows] nerdctl connection timeout

### ISSUE THREAD

**Issue by kiransterling** [containerd/nerdctl#859]
Any nerdctl command gives me the following error. I was previously using docker desktop on windows. I have uninstalled it and installed rancher desktop  . Do I need to change anything in the host file.I can see these entries in the host file in windows

# Added by Docker Desktop
192.168.0.104 host.docker.internal
192.168.0.104 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section

nerdctl run hello-world

docker.io/library/hello-world:latest: resolving      |--------------------------------------|
elapsed: 9.9 s                        total:   0.0 B (0.0 B/s)
INFO[0010] trying next host                              error="failed to do request: Head \"https://registry-1.docker.i
o/v2/library/hello-world/manifests/latest\": dial tcp: lookup registry-1.docker.io on 172.18.64.1:53: read udp 172.18.70
.2:46614->172.18.64.1:53: i/o timeout" host=registry-1.docker.io
FATA[0010] failed to resolve reference "docker.io/library/hello-world:latest": failed to do request: Head "https://regis
try-1.docker.io/v2/library/hello-world/manifests/latest": dial tcp: lookup registry-1.docker.io on 172.18.64.1:53: read
udp 172.18.70.2:46614->172.18.64.1:53: i/o timeout
https://github.com/containerd/nerdctl/tree/master/docs/faq.md

**Comment by AkihiroSuda** [comment]
https://github.com/rancher-sandbox/rancher-desktop/discussions seems better place to ask this
