### ISSUE TITLE
make fail (`cmd/nerdctl/run_network.go:33:2: //go:build comment without // +build comment`)

### ISSUE THREAD

**Issue by ningmingxiao** [containerd/nerdctl#879]
after this commit https://github.com/containerd/nerdctl/commit/d4fb38c4701e68110cb52185fbb95ab61b7f1d59 when use golang 1.16
```
cmd/nerdctl/run_network.go:33:2: //go:build comment without // +build comment
make: *** [Makefile:50：nerdctl] 
```

**Comment by Zheaoli** [comment]
I guess you build the nerdctl in a non-Linux platform (such as macOS/Windows/Freebsd). It will trigger a build process by using https://github.com/containerd/nerdctl/commit/3f1ffe214daf63b632fea05b9b797d72f42d6c0c#diff-9145d3e6b0041f24b980c1854a2a3990436700a3b646438d787b7dc8d32bc294R1-R25

`//go:build` tag is a new feature in Go 1.17, FYI https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md#abstract and https://go.dev/doc/go1.17

Maybe you can try to upgrade the Go version to 1.17.

Should we add this information to the contribute guideline? cc @AkihiroSuda

**Comment by ningmingxiao** [comment]
wil fix by https://github.com/containerd/nerdctl/pull/886/files

**Comment by ningmingxiao** [comment]
> I guess you build the nerdctl in a non-Linux platform (such as macOS/Windows/Freebsd). It will trigger a build process by using [3f1ffe2#diff-9145d3e6b0041f24b980c1854a2a3990436700a3b646438d787b7dc8d32bc294R1-R25](https://github.com/containerd/nerdctl/commit/3f1ffe214daf63b632fea05b9b797d72f42d6c0c#diff-9145d3e6b0041f24b980c1854a2a3990436700a3b646438d787b7dc8d32bc294R1-R25)
> 
> `//go:build` tag is a new feature in Go 1.17, FYI https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md#abstract and https://go.dev/doc/go1.17
> 
> Maybe you can try to upgrade the Go version to 1.17.
> 
> Should we add this information to the contribute guideline? cc @AkihiroSuda

thank you
