### ISSUE TITLE
nerdctl stats --no-stream --format "{{.Name}}"

### ISSUE THREAD

**Issue by Boruson** [containerd/nerdctl#880]
return container name is "--",name field is missing, I want to why?

# nerdctl stats --no-stream --format "{{.Name}}"
# --
client:
version: v0.17.0
server:
containerd:
version: v1.6.0

host OS, linux 5.10.38-21.01.el7.x86_64 #1

I could get solution, could you help me?

**Comment by Zheaoli** [comment]
The nerdctl is not supported for `--format` arg with `nerdctl stats --no-stream` yet, I will make a PR for this

**Comment by Boruson** [comment]
1. what is PR ?
2. nerdctl stats --no-stream result as follow:
CONTAINER ID    NAME   CPU%    MEM USAGE/LIMIT     MEM %     NET I/O             BLOCK I/O        PIDS
2132dha9765s    --           0.05%     188KiB/8EiB               0.00%       139MB/55MB      0B/0B                22
8283nsdh91sd    --           0.00%     19KiB/8EiB                0.00%          8GB /1GB          79MB/0B            16

**Comment by Zheaoli** [comment]
I think we found the issue: the container origin name is '--' ..

**Comment by fahedouch** [comment]
if len (container name)  <=  1  ==> the name is replaced by `--` https://github.com/containerd/nerdctl/blob/354d03acb11a1649f0f3aec73218b8d8e2d9e062/pkg/statsutil/stats.go#L142

**Comment by venkatasandeeplade** [comment]
@fahedouch @Zheaoli @Boruson  How is the issue fixed ? I am also facing same issue
