### ISSUE TITLE
Support --ip argument when run the container

### ISSUE THREAD

**Issue by Zheaoli** [containerd/nerdctl#882]
Related #852 

I think if we want to support `ipv4_address` in `nerdctl compose`, we should support `--ip` argument before.

FYI https://docs.docker.com/config/containers/container-networking/#ip-address-and-hostname

I would like to make a try to impl it before v0.19.0 or more quickly

**Comment by fahedouch** [comment]
plz go ahead.

a PR is initiated here https://github.com/containerd/nerdctl/pull/436
