### ISSUE TITLE
http registry login (`http: server gave HTTP response to HTTPS client`)

### ISSUE THREAD

**Issue by Maddin-619** [containerd/nerdctl#887]
I found this question #224 but setting the `--insecure-registry` flag only skips tls verfiy and does not affect the https://github.com/containerd/nerdctl/blob/354d03acb11a1649f0f3aec73218b8d8e2d9e062/pkg/imgutil/dockerconfigresolver/dockerconfigresolver.go#L39 option (anymore?).

I figured out plainHTTP is only accepted on localhost. That's totally fine in terms of security not sending credentials in plain text over the network. Nevertheless I have to do it (even though VPN) ...

Can we provide a new flag for http? Or could we parse the protocol form the host input for example `nerdctl login http://registry.com` ?

**Comment by AkihiroSuda** [comment]
`--insecure-registry` supports falling back to HTTP when "server gave HTTP response to HTTPS client".

https://github.com/containerd/nerdctl/blob/41ceb2944209a7232a49356f0d7fd293854bac98/pkg/imgutil/imgutil.go#L145-L164
https://github.com/containerd/nerdctl/blob/41ceb2944209a7232a49356f0d7fd293854bac98/pkg/imgutil/imgutil.go#L195-L202

Isn't this working? What's your registry implementation?

**Comment by Maddin-619** [comment]
Yes for push/pull there is a fallback but for login not (as far as I understood the code). 
```
ERRO[0001] failed to call tryLoginWithRegHost            error="failed to call rh.Client.Do: Get \"https://nexus.de:18080/v2/\": http: server gave HTTP response to HTTPS client" i=0
FATA[0001] failed to call rh.Client.Do: Get "https://nexus.de:18080/v2/": http: server gave HTTP response to HTTPS client
```

**Comment by Zheaoli** [comment]
The login logic doesn't have a fallback for HTTP

I will make a PR today

/assign
