### ISSUE TITLE
`go mod tidy` fails with Go 1.18: `../go-hostsfile: "../go-hostsfile" is relative, but relative import paths are not supported in module mode`

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#900]
```
$ go version
go version go1.18 linux/amd64

$ go mod tidy
github.com/containerd/nerdctl/pkg/dnsutil/hostsstore imports
        github.com/jaytaylor/go-hostsfile tested by
        github.com/jaytaylor/go-hostsfile.test imports
        ../go-hostsfile: "../go-hostsfile" is relative, but relative import paths are not supported in module mode
```

3d2b1c8e0b3119ab1825b3287ad61e403decf312

**Comment by Junnplus** [comment]
@AkihiroSuda 

As if we only depend on https://github.com/containerd/nerdctl/blob/12a06bb8ad29dddc5d9ade7e26caad268ab8d129/pkg/dnsutil/hostsstore/updater.go#L134

Why not consider us to maintain it.

**Comment by Junnplus** [comment]
looks like jaytaylor has been inactive for a long time. :(

I opened https://github.com/containerd/nerdctl/pull/914 for build with Go 1.18.
