### ISSUE TITLE
Help wanted: test `nerdctl login` v0.18.0-beta.0 with as many registries as possible

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#931]
In v0.18.0-beta.0, we had several non-trivial fixes in `nerdctl login` .

Help wanted for testing `nerdctl login` v0.18.0-beta.0, with as many registry implementations as possible: https://github.com/containerd/nerdctl/blob/v0.18.0-beta.0/docs/registry.md#using-managed-registry-services

https://github.com/containerd/nerdctl/releases/tag/v0.18.0-beta.0

**Comment by Zheaoli** [comment]
I have a test passed with harbor/nexus based on the code in the master branch.

**Comment by Junnplus** [comment]
```
[N] ❯ sudo nerdctl version
Client:
 Version:       v0.18.0-beta.0
 Git commit:    57b2e040c2ceb26b389abfee96c02d1c6f530f93
```

I did the following test locally:

- [x] GHCR
- [x] ECR
- [x] ACR
- [x] Docker Hub
- [x] Quay.io

**Comment by AkihiroSuda** [comment]
Thank you @Zheaoli @Junnplus !

**Comment by Zheaoli** [comment]
I have already tested the following registry

- [ ] AWC ECR
- [ ] Azure
- [ ] DockerHub
- [ ] jfrog.io
- [ ] quay.io

All works fine!
