### ISSUE TITLE
nerdctl push with cosign throw error: cosign executable not found in path $PATH

### ISSUE THREAD

**Issue by xmlking** [containerd/nerdctl#943]
### Description

Unable to  `nerdctl push --sign=cosign` 
Throw `cosign executable not found in path $PATH`

### Steps to reproduce the issue

❯  nerdctl images                                                                                                                                                                                              
REPOSITORY                               TAG       IMAGE ID        CREATED              PLATFORM       SIZE         BLOB SIZE
ghcr.io/xmlking/grpc-starter-kit/base    latest    324e109cc7be    8 minutes ago        linux/arm64    510.9 MiB    163.2 MiB
ghcr.io/xmlking/grpc-starter-kit/base    v0.2.0    324e109cc7be    About an hour ago    linux/arm64    510.9 MiB    163.2 MiB

grpc-starter-kit on  develop [!?] via  v1.18 
❯  nerdctl push --sign=cosign ghcr.io/xmlking/grpc-starter-kit/base:v0.2.0                                                                                                                                     
INFO[0000] pushing as a reduced-platform image (application/vnd.docker.distribution.manifest.v2+json, sha256:324e109cc7be4da6b75472a8bcad17e2d26321c1555d42f45f200c5efa7dd96c) 
manifest-sha256:324e109cc7be4da6b75472a8bcad17e2d26321c1555d42f45f200c5efa7dd96c: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:5fa59ceebdc83ddb6d2f9d89dbbff1b2c9c993b1a1462bb391247f904d2c48e7:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:39b0b4c4587fbfa6f0755490bb53175932c8f0348926efd629b5e26b281aaa57:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:63bc71a7e8dd1d9668121710be981aa07a74660d94ff3bc08a49ec70e7654c7f:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:2181fcbd23f5e0713060e43861d743633976a8d285a397d13d27b814d260a9b1:   done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:a5e44472bb1f0d721d23f82fa10a4c3d25994790238a173c1de950a649eb9a90:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:fed9433fc6d8e566eec66aee9ebc5da9ac21d7d778ab84cd14bf6d72f922d370:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:0737e68e4ee86ac8d2a8aa22d80614528a5898719ff6f2daecca562573202969:    done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 1.3 s                                                                    total:  163.2  (125.5 MiB/s)                                     
ERRO[0001] cosign executable not found in path $PATH     error="exec: \"cosign\": executable file not found in $PATH"
INFO[0001] you might consider installing cosign from: https://docs.sigstore.dev/cosign/installation 
FATA[0001] exec: "cosign": executable file not found in $PATH 

grpc-starter-kit on  develop [!?] via  v1.18 
❯  which cosign                                                                                                                                                                                                
/opt/homebrew/bin/cosign

grpc-starter-kit on  develop [!?] via  v1.18 
❯  nerdctl --version                                                                                                                                                                                           
nerdctl version 0.17.1

grpc-starter-kit on  develop [!?] via  v1.18 
❯  cosign version                                                                                                                                                                                              
   ____    ___    ____    ___    ____   _   _
  / ___|  / _ \  / ___|  |_ _|  / ___| | \ | |
 | |     | | | | \___ \   | |  | |  _  |  \| |
 | |___  | |_| |  ___) |  | |  | |_| | | |\  |
  \____|  \___/  |____/  |___|  \____| |_| \_|
cosign

GitVersion:    1.6.0
GitCommit:     4b2c3c0c8ee97f31b9dac3859b40e0a48b8648ee
GitTreeState:  "clean"
BuildDate:     2022-03-03T17:59:06Z
GoVersion:     go1.17.8
Compiler:      gc
Platform:      darwin/arm64

### Describe the results you received and expected

 nerdctl push --sign=cosign ghcr.io/xmlking/grpc-starter-kit/base:v0.2.0                                                                                                                                     ☸ rancher-desktop on ☁️  
INFO[0000] pushing as a reduced-platform image (application/vnd.docker.distribution.manifest.v2+json, sha256:324e109cc7be4da6b75472a8bcad17e2d26321c1555d42f45f200c5efa7dd96c) 
manifest-sha256:324e109cc7be4da6b75472a8bcad17e2d26321c1555d42f45f200c5efa7dd96c: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:5fa59ceebdc83ddb6d2f9d89dbbff1b2c9c993b1a1462bb391247f904d2c48e7:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:39b0b4c4587fbfa6f0755490bb53175932c8f0348926efd629b5e26b281aaa57:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:63bc71a7e8dd1d9668121710be981aa07a74660d94ff3bc08a49ec70e7654c7f:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:2181fcbd23f5e0713060e43861d743633976a8d285a397d13d27b814d260a9b1:   done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:a5e44472bb1f0d721d23f82fa10a4c3d25994790238a173c1de950a649eb9a90:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:fed9433fc6d8e566eec66aee9ebc5da9ac21d7d778ab84cd14bf6d72f922d370:    done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:0737e68e4ee86ac8d2a8aa22d80614528a5898719ff6f2daecca562573202969:    done           |++++++++++++++++++++++++++++++++++++++| 
elapsed: 1.3 s                                                                    total:  163.2  (125.5 MiB/s)                                     
ERRO[0001] cosign executable not found in path $PATH     error="exec: \"cosign\": executable file not found in $PATH"
INFO[0001] you might consider installing cosign from: https://docs.sigstore.dev/cosign/installation 
FATA[0001] exec: "cosign": executable file not found in $PATH 

### What version of nerdctl are you using?

0.17.1

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

Rancher Desktop for macOS

**Comment by fahedouch** [comment]
I think you should open a ticket in rancher repo, it looks like $PATH is not visible for rancher desktop

**Comment by AkihiroSuda** [comment]
Yes, please ask Rancher Desktop maintainers to install    cosign inside the VM
