### ISSUE TITLE
we should support   restart policy,like --restart=on-failure:5,but no we don't support

### ISSUE THREAD

**Issue by ningmingxiao** [containerd/nerdctl#945]
### What is the problem you're trying to solve

docker support restart   policy  no,on-failure,on-failure:3,always，unless-stopped.but nerdctl just support   no,always.

### Describe the solution you'd like

nerdctl support restart  policy  no,on-failure,on-failure:3,always

**Comment by Zheaoli** [comment]
Emmmm, I think this feature is hard to support. because `nerdctl` don't have a daemon process to support listen the container state

**Comment by fuweid** [comment]
There is restart plugin in containerd. We can consider to make it easy to integrate with nerdctl.

**Comment by ningmingxiao** [comment]
Does container  support this feature?  now i can't find it in container 1.5.9 @fuweid

**Comment by fuweid** [comment]
> Does containerd  support this feature?  now i can't find it in containerd 1.5.9 @fuweid 

https://github.com/containerd/containerd/blob/main/runtime/restart/monitor/monitor.go 

Yes. But I think it needs to be enhanced before use it in nerdctl

**Comment by AkihiroSuda** [comment]
We have been already using the restart monitor for `--restart=always`, but the restart monitor doesn't seem to support `on-failure` mode.

**Comment by Junnplus** [comment]
> Yes. But I think it needs to be enhanced before use it in nerdctl

@fuweid Maybe we can extend the restart policy by adding a containerd label, like `containerd.io/restart.policy`.

But I don't know where to record the count of restarts of the container. Perhaps the annotations of the container.

**Comment by Junnplus** [comment]
Append: I will try to enhance containerd's restart manager by adding a label:
`containerd.io/restart.policy`, `containerd.io/restart.count`.

**Comment by ningmingxiao** [comment]
thank you

> Append: I will try to enhance containerd's restart manager by adding a label: `containerd.io/restart.policy`, `containerd.io/restart.count`.



> Append: I will try to enhance containerd's restart manager by adding a label: `containerd.io/restart.policy`, `containerd.io/restart.count`.

thank you
