### ISSUE TITLE
nerdctl read from stdin will stuck forever.

### ISSUE THREAD

**Issue by laixintao** [containerd/nerdctl#973]
### Description

nerdctl won't exit after reading from stdin, with `-i` arg.

### Steps to reproduce the issue

`echo 123 | ./nerdctl run -i --network none ubuntu cat -`

run this command, it will stuck:

<img width="863" alt="image" src="https://user-images.githubusercontent.com/9675939/162602396-3a88f5e5-e63e-4833-a4fd-61b190479c5c.png">

ctrl + C and ctrl + D didn't work. I can not exit.

### Describe the results you received and expected

If i replace nerdctl with `docker` cli, then it is ok:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/9675939/162602432-695c0d22-f959-4ff0-8fb0-532b600bab55.png">

### What version of nerdctl are you using?

```
root@vagrant:/home/vagrant# ./nerdctl --version
nerdctl version 0.18.0
```

### Host information

```
root@vagrant:/home/vagrant# uname -a
Linux vagrant 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

tested in Fedora, same behaviour:

```
[root@fedora-s-1vcpu-1gb-sgp1-01 ~]# uname -a
Linux fedora-s-1vcpu-1gb-sgp1-01 5.14.10-300.fc35.x86_64 #1 SMP Thu Oct 7 20:48:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jschwinger233** [comment]
It's actually the same behavior as Docker, you may want to try `docker run -it --rm --net host bash cat -` which will ignore sigint as well.
And this has nothing to do with container runtime or the exec(2)-ed binary, because it's the kernel responsibility to repress the sigint for pid 1 of every pid namespace.

**Comment by jschwinger233** [comment]
Let me demonstrate this behavior as followed:

```python
import os
import ctypes
import ctypes.util

CLONE_NEWPID = 0x20000000
libc = ctypes.CDLL(ctypes.util.find_library("c"), use_errno=True)
libc.unshare(CLONE_NEWPID)
pid = os.fork()
if pid == 0:
    os.execve("/bin/sleep", ("sleep", "1000"), {})
```

Run this script using root, and you'll find it impossible to kill by 2.

Here is the man2: https://man7.org/linux/man-pages/man7/pid_namespaces.7.html
![image](https://user-images.githubusercontent.com/6435624/162604704-e3ba085c-cb04-40b8-818c-4292a6ffe261.png)

**Comment by Zheaoli** [comment]
It seems we got some issues here. PTAL https://github.com/containerd/nerdctl/blob/master/pkg/taskutil/taskutil.go#L72-L80 

In this case, when the command `echo 123` has been executed, the result `123+EOF` has been used in `nerdctl run -i --network none ubuntu cat`. but in our code, we close container stdin directly when we get the EOF error. 

But for some of the commands such as `cat -` or else, closing the process stdin will not cause an existing event unless the command has got an EOF error.

So maybe we need to redirect the error we got. PTAL https://github.com/moby/moby/blob/master/pkg/ioutils/readers.go#L107-L127

**Comment by jschwinger233** [comment]
Even `echo asdf | nerdctl run -it --rm --net none bash cat -` is still reading from pty....

**Comment by Junnplus** [comment]
> It seems we got some issues here. PTAL https://github.com/containerd/nerdctl/blob/master/pkg/taskutil/taskutil.go#L72-L80

Emm. `Closer` is created after the task is created https://github.com/containerd/nerdctl/blob/master/pkg/taskutil/taskutil.go#L60-L62

**Comment by AkihiroSuda** [comment]
Should be fixed in : 
- https://github.com/containerd/nerdctl/pull/726

**Comment by Zheaoli** [comment]
> Emm. `Closer` is created after the task is created https://github.com/containerd/nerdctl/blob/master/pkg/taskutil/taskutil.go#L60-L62

Yes, the `Closer` will be triggered when the stdin close by EOF, but the default Closer don't redirect the EOF to container process stdin

**Comment by junnplus** [comment]
Fixed: https://github.com/containerd/nerdctl/pull/1014
